### ISSUE TITLE
Wrong startOffset in HardLineBreak

### ISSUE THREAD

**Issue by JFormDesigner** [vsch/flexmark-java#10]
The startOffset in `HardLineBreak` is wrong in two cases:

a) if using **backslash** at the end of line, the startOffset does not include the backslash

example from ast_spec.md (line 7332):
```
foo\
bar
.
<p>foo<br />
bar</p>
.
Document[0, 9]
  Paragraph[0, 9]
    Text[0, 3] chars:[0, 3, "foo"]
    HardLineBreak[4, 5]
    Text[5, 8] chars:[5, 8, "bar"]
```
HardLineBreak starts at 4, but it should start at 3 where the backslash is.

b) if using **more than two space characters** at the end of a line, only the last two space characters are included in HardLineBreak, but it would IMO make more sense to include all trailing space characters in HardLineBreak

example from ast_spec.md (line 12564):
```
foo       
baz
.
<p>foo<br />
baz</p>
.
Document[0, 15]
  Paragraph[0, 15]
    Text[0, 3] chars:[0, 3, "foo"]
    HardLineBreak[8, 11]
    Text[11, 14] chars:[11, 14, "baz"]
```
HardLineBreak starts at 8, but it should start at 3 where the first trailing space character is

**Comment by vsch** [comment]
@JFormDesigner, thank you for the report.

In the case of a) it is definitely a but and I will fix it shortly. I have been due for an update.

in the case of b) I will make the hard break include all spaces by default but add an option to override the behaviour.  I use it in the plugin to syntax highlight the last two spaces.

**Comment by vsch** [comment]
@JFormDesigner, fixed. Maven Central updated. Thanks for the find. I added the option to only use last 2 spaces for the node, it is disabled by default. I forgot to add tests for when the option is enabled but that will make it into then next release.

**Comment by JFormDesigner** [comment]
@vsch  Thx 👍
