### ISSUE TITLE
Bracket '>' on new line not parsed as part of HTML-tag, but as Block Quote instead

### ISSUE THREAD

**Issue by Elmervc** [vsch/flexmark-java#101]
Example:

```
<span
class="abc"
data-role="example"
>
some content here
</span>
```

When option `Parser.BLOCK_QUOTE_INTERRUPTS_PARAGRAPH` is set to `true` (=default), the parser prefers parsing a block quote instead of greedily include it in the opening HTML-tag:

```
<p>&lt;span<br>class="abc"<br>data-role="example"</p> 
<blockquote> 
 <p>some content here<br></p> 
</blockquote>
```

**Comment by vsch** [comment]
@Elmervc, thank you for reporting this. I will add logic to not let block quotes interrupt active HTML blocks.

**Comment by vsch** [comment]
@Elmervc, I took a look at the code and realized that this detection would be problematic.

Block parsing is done before inline parsing. Therefore at the time a block quote prefix is detected, the paragraph text is not parsed for inline HTML. Therefore it is not possible to with the CommonMark architecture to correctly parse dangling closing `>` of an HTML tag.

The only workarounds are to either disable block quotes interrupting paragraphs, requiring block quotes to be at the start of a block or to not leave dangling `>` at the start of a line.

**Comment by Elmervc** [comment]
Thanks for investigating. Not sure how HTML-block's (not the inline ones) are parsed. But I understand that this cannot be done easily before block-quote parsing. We go for disabling  the "block quote interrupting paragraphs" option now.

**Comment by vsch** [comment]
@Elmervc, fixed in pegdown compatibility mode with deep html parsing. 0.22.2
