### ISSUE TITLE
Any way to allow whitespace between `link text` and `link ref` (Pegdown comp.) ?

### ISSUE THREAD

**Issue by Elmervc** [vsch/flexmark-java#102]
Pegdown allowed having `[some text]<whitespace>(http://somelink.com)`  to be parsed as link.

This is different from common-mark spec

>An inline link consists of a link text followed _immediately_ by a left parenthesis `(`

Unfortunately, many user-entered items in our application contain inline links with a whitespace after `]`. Is there an easy way to allow this? If so, this may become part of the Pegdown options adapter.

ps. As I'm investigating, I'm finding more issues related to migration from Pegdown to commonmark/flexmark. Do you want me to share them  in this issue tracker? These issues are not particularly bugs, but often related to differences between pegdown and commonmark parse strategies. But it's sometimes hard to find out if it's easy to fixed with extension-options. I don't want to add too much noise from these kind of issues in the flexmark tracker.

**Comment by vsch** [comment]
@Elmervc, I will add an option to allow spaces between parts of a link element and add it as a default option for pegdown adapter if it does not cause issues with parsing of other elements. You should add this option manually once it is implemented, just to be on the safe side.

**Comment by vsch** [comment]
@Elmervc, please open all issues you find with pegdown migration. Even if some cannot be fixed due to differences in parsers it will be good to have a list of issues that need to be addressed in the Markdown source.

**Comment by vsch** [comment]
@Elmervc, new version 0.19.5 released. Maven central update may take some time.

**Comment by Elmervc** [comment]
Great, will update to latest version
