### ISSUE TITLE
how to add attribute for the <a>

### ISSUE THREAD

**Issue by Hxuhao233** [vsch/flexmark-java#103]
My Project has used the [PegDown](https://github.com/sirthias/pegdown) to transfer markdown text to html text.In the PegDown , 
I use a custom class extends[LinkRenderer] (https://github.com/sirthias/pegdown/blob/master/src/main/java/org/pegdown/LinkRenderer.java) and  override the `render()` methods to achieve the aim to add some attribute for different links(likes image link common link);
So how can i do it by flexmark?

**Comment by vsch** [comment]
Please take a look at the samples provided for attributes: [AttributeProviderSample](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/AttributeProviderSample.java) and [AttributeProviderSample2](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/AttributeProviderSample2.java)

If you need to change the URL of a link then you need a `LinkResolver` and the sample for it: [PegdownCustomLinkResolverOptions](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/PegdownCustomLinkResolverOptions.java)

**Comment by Hxuhao233** [comment]
I have solved it.Thank a lot!
