### ISSUE TITLE
problem about "<code class = "language-">"

### ISSUE THREAD

**Issue by Hxuhao233** [vsch/flexmark-java#104]
hi, i have encountered another problem. I render the markdown text:

\```php

   public function Test(){
     echo "hello";
   }
 
\``` 

and get the result text:
"\<code class="language-php"> ."
But i don't need the prefix "language" of the <code class>,i want "\<code class="php">" ,could you help me?

here is my code

``` java
        String markdownText = "```php\n"+
	"public function tcpTest(){\n"+
	 "  echo \"hello\";\n"+
	"}\n" + 
        "```";

    	DataHolder OPTIONS= PegdownOptionsAdapter.flexmarkOptions(
    			Extensions.ALL_WITH_OPTIONALS
        );
        Parser parser = Parser.builder(OPTIONS).build();
        HtmlRenderer renderer = HtmlRenderer.builder(OPTIONS).build();
        Node node = parser.parse(markdownText);
        String processedHtml = renderer.render(node);
```

result :          

\<pre>\<code class="language-php">public function tcpTest(){
  \echo &quot;hello&quot;;
\}
\</code>\</pre>

**Comment by vsch** [comment]
@Hxuhao233, core node rendering options are listed in https://github.com/vsch/flexmark-java/wiki/Extensions#renderer. You need to set  `HtmlRenderer.FENCED_CODE_LANGUAGE_CLASS_PREFIX` option to an empty string `""`.

**Comment by vsch** [comment]
@Hxuhao233, here is how you can do that:

```java
    static final DataHolder OPTIONS = PegdownOptionsAdapter.flexmarkOptions(
            Extensions.ALL_WITH_OPTIONALS
    ).toMutable()
            .set(HtmlRenderer.FENCED_CODE_LANGUAGE_CLASS_PREFIX,"")
            ;
```

**Comment by Hxuhao233** [comment]
oh i think i should read the wiki carefully ，thanks a lot!
