### ISSUE TITLE
problem about a task of some line in front

### ISSUE THREAD

**Issue by Hxuhao233** [vsch/flexmark-java#107]
hi @vsch ,i want to parse the text 
```
String markdownText1 ="test1\n"+
					"- [ ] test2\n"+
					"- [x] test2\n"+
					"test3";
```
to

\<p>test1\</p>
\<ul>
 \<li>[ ] test2 \</li>
  \<li>[x] test2\<br/>
test3\</li>
\</ul>

but ，i get 
\<p>test1\<br />
\- [ ] test2 \<br />
\- [x] test2 \<br />
test3 \</p>

It means that i can't parse the task,how can i solve it?
The same problem arises in a list of some line in front
e.g.

"test1\n"+
"1. test2\n"+
"2. test2\n"+
"test3";

**Comment by Hxuhao233** [comment]
Oh i think i should set both `Parser.LISTS_ORDERED_ITEM_INTERRUPTS_PARAGRAPH`  and  `Parser.LISTS_BULLET_ITEM_INTERRUPTS_PARAGRAPH` to `true`

**Comment by vsch** [comment]
@Hxuhao233, yes. This will allow task list items to start a list without a preceding blank line.

You also have additional flags to control if empty items can interrupt paragraphs and whether sub-list items can interrupt paragraphs of parent items. https://github.com/vsch/flexmark-java/wiki/Extensions#list-item-paragraph-interruption-options

**Comment by Hxuhao233** [comment]
@vsch good job！
