### ISSUE TITLE
problem of the list of some Space in font

### ISSUE THREAD

**Issue by Hxuhao233** [vsch/flexmark-java#108]
hi @vsch ，i want to parse this text 
```
String markdownText = 	                "  1. **download**  \n"+
    					"  2. **abc**  		\n"+
    					"  3. **999**";
```
you can see that there are some whitespace(2 space pre line) in font。
so the result is
\<ol>
  \<li>\<strong>download\</strong>
    \<ol>
      \<li>\<strong>abc\</strong>\</li>
      \<li>\<strong>999\</strong>\</li>
    \</ol>
  \</li>
\</ol>

but what i wish is

\<ol>
  \<li>\<strong>download\</strong>
  \<li>\<strong>abc\</strong>\</li>
  \<li>\<strong>999\</strong>\</li>
  \</li>
\</ol>

It means that i don't need the sub list.
here is my code 
        
```
     
        OPTIONS = PegdownOptionsAdapter.flexmarkOptions(
        		(Extensions.ALL_WITH_OPTIONALS & ~Extensions.SMARTYPANTS & ~Extensions.TASKLISTITEMS) | Extensions.EXTANCHORLINKS
    			)
    			.toMutable()
    			.set(HtmlRenderer.FENCED_CODE_LANGUAGE_CLASS_PREFIX,"")
    			.set(HtmlRenderer.INDENT_SIZE, 2)
    			.set(Parser.LISTS_ITEM_INDENT, 2)
    			.set(Parser.LISTS_ORDERED_ITEM_INTERRUPTS_PARAGRAPH,true)
    			.set(Parser.LISTS_BULLET_ITEM_INTERRUPTS_PARAGRAPH,true);

        parser = Parser.builder(OPTIONS).build();
        renderer = HtmlRenderer.builder(OPTIONS).build();
```

What should i do to solve it

**Comment by vsch** [comment]
@Hxuhao233, you should not set `Parser.LISTS_ITEM_INDENT` to 2, the proper indent for pegdown compatibility is 4. You are getting the subsequent items as a sub-items because they are indented by 2 which you configured to be the indent level for list items, making them sub-items of the first item.

**Comment by Hxuhao233** [comment]
Thank you @vsch，But i have to set `Parser.LISTS_ITEM_INDENT` to 2 because of the other need.So i want to set other options to achieve the goal.
