### ISSUE TITLE
Parse / render Markdown in HTML block

### ISSUE THREAD

**Issue by marzn** [vsch/flexmark-java#110]
Is it possible to render Markdown which is contained in a HTML block or can I achieve that by some custom code?

Example:
```
<div>
# H1
</div>
```

I want to have the following result:
```
<div>
<h1>H1</h1>
</div>
```

**Comment by vsch** [comment]
@marzn, parser is based on CommonMark in which an HTML block ends on a blank line. So if you add a blank line after the `<div>` and before the `</div>` you will get what you want. GitHub comments are also CommonMark so you can test it in your browser:

```markdown
<div>

# H1

</div>
```
Results in:

<div>

# H1

</div>

**Comment by marzn** [comment]
Thank you :)
