### ISSUE TITLE
Thread safety question

### ISSUE THREAD

**Issue by knes1** [vsch/flexmark-java#111]
I found in the docs that Parser parse method is thread-safe, but found no references about thread safety and the render method of the Renderer. Is render method thread-safe as well? (Can we share the Renderer instance among multiple threads after it's initialized?)

Thanks

**Comment by vsch** [comment]
@knes1, the renderer uses static storage only for constants so other than the Appendable for output there is nothing shared between instances and if you use the render(Node) version it allocates the Appendable on the stack so you can re-use renderer and use renderer.render(Node) for convenience.

**Comment by knes1** [comment]
Ok thanks!
