### ISSUE TITLE
Potential bug: Node.getChildOfType always returns null unless parent is an instance of the desired class

### ISSUE THREAD

**Issue by colindean** [vsch/flexmark-java#112]
I would expect that `Node.getChildOfType(Class)` would return me the first child in the given list of classes. Instead, as of v0.19.3, it always looks at the node's parent's class. The end result is that this should basically always be null.

I think this is a bug.

```java
    public Node getChildOfType(Class... classes) {
        Node child = getFirstChild();
        while (child != null) {
            for (Class nodeType : classes) {
                if (nodeType.isInstance(parent)) return child;
            }
            child = child.getNext();
        }
        return null;
    }
```

should be

```java
    public Node getChildOfType(Class... classes) {
        Node child = getFirstChild();
        while (child != null) {
            for (Class nodeType : classes) {
                if (nodeType.isInstance(child)) return child; // the change is here
            }
            child = child.getNext();
        }
        return null;
    }
```

**Comment by colindean** [comment]
Realized that I'm out of date, but v0.19.6 is still exhibiting this behavior.

**Comment by colindean** [comment]
The workaround is simply to use `Node.getFirstChildAny(Class)`.

**Comment by vsch** [comment]
@colindean, thank you for catching this. It is fixed for the next release.

**Comment by vsch** [comment]
@colindean, repo updated. Maven updated, version 0.19.8
