### ISSUE TITLE
[Question] Migration from pegdown to flexmar

### ISSUE THREAD

**Issue by marib15** [vsch/flexmark-java#119]
Hi,
I used pegdown library in my project and now I have started use flexmark. I have 2 question.
1. In pegdown, I could override method printImageTag() from class ToHtmlSerializer.  I can't find where are images rendered in flexmar. Can you help me?
2. Can be defined new mark simply? I want to users can use same new mark, for example $text, where this will be changed with something what i defined before. For example same special url.

P.S. Sorry for my English

**Comment by vsch** [comment]
@marib15, the architecture is a bit different in flexmark. Rendering uses custom attribute providers to customize attributes for generated HTML or in the case of links (wiki, image or plain) you can also do that in the custom link resolver.

This is covered in detail with sample code links in #105.

For implementing custom text processing you can take a look at https://github.com/vsch/flexmark-java/wiki/Writing-Extensions. In your case for text replacement you can probably implement it using the `InlineParserExtension` to find the text `$text` and either insert a custom node into the AST that you will render with a custom node renderer or to add a standard node into the AST to be rendered by the library provided node renderer.

There are a few samples in the `flexmark-java-samples` module in this repo showing link resolvers, custom link parsers and custom renderers to help you get started. https://github.com/vsch/flexmark-java/tree/master/flexmark-java-samples/src/com/vladsch/flexmark/samples

**Comment by vsch** [comment]
@marib15, there is a new module to process GitHub issues of the format: `#\d+(?:\s+|\n|$)` and GitHub user strings: `@text` which is similar to handling your example `$text`. 

The source is in modules [`flexmark-ext-gfm-issues`](https://github.com/vsch/flexmark-java/tree/master/flexmark-ext-gfm-issues) and [`flexmark-ext-gfm-users`](https://github.com/vsch/flexmark-java/tree/master/flexmark-ext-gfm-users)

You can probably start with one of these modules and change the names, options and regex used to recognize the elements.
