### ISSUE TITLE
Ampersand between link query parameters is escaped

### ISSUE THREAD

**Issue by SilentGert** [vsch/flexmark-java#121]
Hi,

I have a markdown link which includes an ampersand between the query parameters in the link:
```markdown
[my link](http://foo.bar?param1=foo&param2=bar)
```
When I convert the markdown I get the following output:
```
<p><a href="http://foo.bar?param1=foo&amp;param2=bar">my link</a></p>
```

However, I was expecting the following output:
```
<p><a href="http://foo.bar?param1=foo&param2=bar">my link</a></p>
```

It looks like the ampersand is escaped although it shouldn't. Is this in any way related to issue #1 ?

I tested it with version 0.20.2.

**Comment by vsch** [comment]
@SilentGert, thank you for reporting this. It is a bug. I will make a fixed release shortly.

**Comment by vsch** [comment]
@SilentGert, actually I checked and `&` is supposed to be replaced since it is could also be the start of an HTML entity and should be escaped. So this is the correct behaviour.

**Comment by SilentGert** [comment]
Ah yes, you are right. I was confused by my debug output containing the escaped character ignoring the fact it is rendered in HTML... Sorry for the disturbance. :)
