### ISSUE TITLE
 Dependent class Exception when useing  com.vladsch.flexmark.ext.tables.TablesExtension;

### ISSUE THREAD

**Issue by Hxuhao233** [vsch/flexmark-java#123]
Hi,@vsch
I want to use TablesExtension in the options but it throw the exception:
Caused by: java.lang.IllegalStateException: Dependent class class com.vladsch.flexmark.ext.tables.internal.TableParagraphPreProcessor$2 is duplicated. Only one instance can be present in the list

Here is my code 

``` java
private static final DataHolder OPTIONS = PegdownOptionsAdapter.flexmarkOptions(
			(Extensions.ALL_WITH_OPTIONALS & ~Extensions.SMARTYPANTS & ~Extensions.TASKLISTITEMS) | Extensions.EXTANCHORLINKS, 
			CustomLinkExtension.create(),
			CustomAnchorLinkExtension.create(),
			TablesExtension.create()
			).toMutable()
			.set(HtmlRenderer.FENCED_CODE_LANGUAGE_CLASS_PREFIX,"")		
			.set(HtmlRenderer.INDENT_SIZE, 2)							
			.set(Parser.LISTS_ITEM_INDENT, 2)							
			.set(Parser.LISTS_ORDERED_ITEM_INTERRUPTS_PARAGRAPH,true)	
			.set(Parser.LISTS_BULLET_ITEM_INTERRUPTS_PARAGRAPH,true);	
``` 

Could you give me some advice?

**Comment by vsch** [comment]
@Hxuhao233, your pegdown options already include the table extension so you adding it into the extension list is causing the duplication.

**Comment by Hxuhao233** [comment]
Ok，i get it thank you!
