### ISSUE TITLE
Table with less than 3 chars in header separator doesn't get rendered correctly

### ISSUE THREAD

**Issue by Apoorva-GA** [vsch/flexmark-java#125]
Table with less than 3 char in header separator is not getting rendered correctly.

ex: The below table 

```
|Vowels|dd|
|------|--|
|aeiou |a |
|AEIOU |e |
```

is getting rendered as 

|Vowels|dd|
|——|–|
|aeiou |a |
|AEIOU |e |

where as tables with 3 or more chars in header separator is getting rendered properly.
Is there a way to accommodate less than 3 chars in header separator?

**Comment by vsch** [comment]
@Apoorva-GA, I added a new option to control this behaviour.

* Add: `TablesExtension.MIN_SEPARATOR_DASHES` to control how many dashes minimum before
  separator column is recognized as a table separator.

set this option to 2 or 1 to allow less dashes to be treated as a valid table separator.

Repo updated. Maven update in progress.

**Comment by Apoorva-GA** [comment]
Wow..!! That was quick. Thanks for the fix.
