### ISSUE TITLE
Code in table can't be rendered

### ISSUE THREAD

**Issue by Hxuhao233** [vsch/flexmark-java#126]
Hi,@vsch
I want to render the text :

\|header1\|header2\|header3\|
\|-------\|----\|------\|
\| line \| \`\`\`\{
    "key1": "xxx",
    "key2": [
        "xxx",
        "zzz"
    ]
} \`\`\` 
\| \`\`\`\{
    "key1": "xxx",
    "key2": "xxx"
}\`\`\`\|

But it can't render correctly.
Could you give me some advice?

**Comment by vsch** [comment]
@Hxuhao233, table rows are supposed to be contained on a single line and cannot include other block elements.

The only way to handle such formatting in a table is to convert the cell text to HTML, with HTML entity for line break:

```markdown
|header1|header2|header3|
|-------|----|------|
| line | <pre><code>&#10;"key1": "xxx",&#10;"key2": \[&#10;    "xxx",&#10;    "zzz"&#10;\]</code></pre> |<pre><code>"key1": "xxx",&#10;"key2": "xxx"&#10;</code></pre>|
```

Resulting in:

|header1|header2|header3|
|-------|----|------|
| line | <pre><code>&#10;"key1": "xxx",&#10;"key2": \[&#10;    "xxx",&#10;    "zzz"&#10;\]</code></pre> |<pre><code>"key1": "xxx",&#10;"key2": "xxx"&#10;</code></pre>|

**Comment by Hxuhao233** [comment]
But when i use pegdown ,it can work.Could you update flexmark to support mult-line code?

**Comment by vsch** [comment]
@Hxuhao233, I will take a look at adding this as an option.

In the mean time you can also use the following, a bit less awkward format

```markdown
|header1|header2|header3|
|-------|----|------|
| line | `{`<br>`  "key1": "xxx",`<br>` "key2": [ "xxx", "zzz" ]`<br>`}`| `{`<br>` "key1": "xxx",`<br>` "key2": "xxx"`<br>`}`|
```
Effectively breaking up the inline code lines and inserting a `<br>` html tag.

**Comment by Hxuhao233** [comment]
Oh @vsch, it's so cool. I am looking forward.

**Comment by vsch** [comment]
@Hxuhao233, added [Macros Extension](https://github.com/vsch/flexmark-java/wiki/Macros-Extension) to allow arbitrary markdown content to be  inserted as block or inline elements, allowing block elements to be used where only inline  elements are allowed by syntax.

It is a much cleaner and easier way to include block elements in table cells, including other tables.

Repo updated, maven updated. Version 0.34.46 is the one where it is implemented.

**Comment by Hxuhao233** [comment]
Oh,I am sorry to see it so late. 
It is really a good way to handle table.Thanks!!!
