### ISSUE TITLE
Render links with target="_blank"?

### ISSUE THREAD

**Issue by dflorey** [vsch/flexmark-java#127]
Hi!
First of all congrats to this great library!
Question: Is there a way to override the link renderer to render all links with target="_blank"?

**Comment by vsch** [comment]
@dflorey, you need to implement a custom attribute provider. See: [AttributeProviderSample2.java] 

You can use the same provider to add/remove/change attributes for any node being rendered. So it
can be used for issue #128

[AttributeProviderSample2.java]: https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/AttributeProviderSample2.java#L36-L57

**Comment by dflorey** [comment]
Wow, that was easy ;-)
Thanks so much for your help!

**Comment by ST-DDT** [comment]
The example is now located here: [AttributeProviderSample2.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/AttributeProviderSample2.java#L37-L58)

**Comment by vsch** [comment]
@ST-DDT, thank you for the fix. There will be a lot of old links that will break due to shuffling of directory structure in master.

I will see if I can get a list of all comments with links to repository files. I may be able to get them fixed up as a batch or at least have a list to fix manually.
