### ISSUE TITLE
Feature request: COLUMN_CLASS_NAME and HEADER_CLASS_NAME

### ISSUE THREAD

**Issue by dflorey** [vsch/flexmark-java#128]
It would be great to have additional options for the table extension to specify class names for th and td tags.
Thanks again for the great work!

**Comment by vsch** [comment]
@dflorey, you need to implement a custom attribute provider. See: [AttributeProviderSample2.java] 

You can use the same provider to add/remove/change attributes for any node being rendered. So it
can be used for issue #128

[AttributeProviderSample2.java]: https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/AttributeProviderSample2.java#L36-L57
