### ISSUE TITLE
Hard line breaks do not work if markdown text/files uses CR LF as line separator

### ISSUE THREAD

**Issue by JFormDesigner** [vsch/flexmark-java#13]
flexmark seems not handle CR characters in markdown text/files, which breaks hard-line-breaks (and maybe other things?). If a file uses CR LR as line separator, hard line breaks do not work.

With CR:
```java
Parser parser = Parser.builder().build();

Node document = parser.parse("aaa  \r\nbbb\\\r\nccc");
System.out.println(new AstCollectingVisitor().collectAndGetAstText(document));
```
Outputs (not hard line breaks; CR in text):
```
Document[0, 16]
  Paragraph[0, 16]
    Text[0, 6] chars:[0, 6, "aaa  \r"]
    SoftLineBreak[6, 7]
    Text[7, 12] chars:[7, 12, "bbb\\r"]
    SoftLineBreak[12, 13]
    Text[13, 16] chars:[13, 16, "ccc"]
```

Without CR:
```java
Node document2 = parser.parse("aaa  \nbbb\\\nccc");
System.out.println(new AstCollectingVisitor().collectAndGetAstText(document2));
```
Outputs (correct):
```
Document[0, 14]
  Paragraph[0, 14]
    Text[0, 3] chars:[0, 3, "aaa"]
    HardLineBreak[3, 6]
    Text[6, 9] chars:[6, 9, "bbb"]
    HardLineBreak[9, 11]
    Text[11, 14] chars:[11, 14, "ccc"]
```

**Comment by JFormDesigner** [comment]
Forgot to note that this works in commonmark-java

**Comment by vsch** [comment]
@JFormDesigner, I will fix it. The reason it works in commonmark-java is that the input is normalized to '\n' before parsing, which cannot be done in flexmark because of the need to track source.

I will add more tests for this.
