### ISSUE TITLE
order list <ol> without "start=" ?

### ISSUE THREAD

**Issue by Hxuhao233** [vsch/flexmark-java#132]
Hi,@vsch
I want to render the text:
```
- 1. list1

- 2. list2

- 3. list3
```
But i get the result 
```
<ul>
  <li>
    <ol>
      <li>list1</li>
    </ol>
  </li>
  <li>
    <ol>
      <li>list2</li>
    </ol>
  </li>
  <li>
    <ol>
      <li>list3</li>
    </ol>
  </li>
</ul>
```

i want to add the "start" attr to the \<ol> except first \<ol>,like:
```
<ul> 
 <li> 
  <ol> 
   <li>list1</li> 
  </ol> 
 </li> 
 <li> 
  <ol start="2"> 
   <li>list2</li> 
  </ol> 
</li> 
 <li> 
  <ol start="3"> 
   <li>list3</li> 
  </ol> 
 </li> 
 <li> 
<ul>
```

My code
``` java
	
   private static final DataHolder OPTIONS = PegdownOptionsAdapter.flexmarkOptions(
			(Extensions.ALL_WITH_OPTIONALS )
			).toMutable()
			.set(HtmlRenderer.FENCED_CODE_LANGUAGE_CLASS_PREFIX,"")	
			.set(HtmlRenderer.INDENT_SIZE, 2)							
			.set(Parser.LISTS_ITEM_INDENT, 2)							
			.set(TablesExtension.MIN_SEPARATOR_DASHES, 1)				

    private static final Parser parser = Parser.builder(OPTIONS).build();
    private static final HtmlRenderer renderer = HtmlRenderer.builder(OPTIONS).build();

```

Could you give me some advice?

**Comment by vsch** [comment]
@Hxuhao233, you are using the pegdown options adapter which configures the parser for pegdown compatibility, including pegdown list parsing and rendering, which ignores list start number.

List parsing options are described in https://github.com/vsch/flexmark-java/wiki/Extensions#list-parsing-options. You need to set `Parser.LISTS_ORDERED_LIST_MANUAL_START` to true.

**Comment by Hxuhao233** [comment]
@vsch, It can work.Thank you!

**Comment by GomiGuchi** [comment]
@vsch I am having a similar problem, but I have the default CommonMark options set.

Using the FlexmarkHtmlParser, I have two consecutive ordered lists being rendered into Markdown as:
```
**Ordered**
1. Item 1
2. Item 2
3. Item 3

1. [Example.com](http://www.example.com)
2. [Google](http://www.google.com)
3. [Yahoo!](http://www.yahoo.com)
4. [Another Example.com](http://www.example.com)
```

When using the default Parser and HtmlRenderer, these two lists are turned into one:
```html
<p><strong>Ordered</strong></p>
<ol>
  <li>
    <p>Item 1</p>
  </li>
  <li>
    <p>Item 2</p>
  </li>
  <li>
    <p>Item 3</p>
  </li>
  <li>
    <p><a href="http://www.example.com">Example.com</a></p>
  </li>
  <li>
    <p><a href="http://www.google.com">Google</a></p>
  </li>
  <li>
    <p><a href="http://www.yahoo.com">Yahoo!</a></p>
  </li>
  <li>
    <p><a href="http://www.example.com">Another Example.com</a></p>
  </li>
</ol>
```

I have tried various Parser options to stop this happening, but I am at a loss.

**Comment by vsch** [comment]
@GomiGuchi, a blank line does not end a list, it only makes the list items loosely spaced.

The right way to end a list is to insert another element in between. An HTML comment serves this purpose without inserting a visible element.

```markdown
**Ordered**
1. Item 1
2. Item 2
3. Item 3
<!-- -->
1. [Example.com](http://www.example.com)
2. [Google](http://www.google.com)
3. [Yahoo!](http://www.yahoo.com)
4. [Another Example.com](http://www.example.com)
```

Resulting in:

```html
<p><strong>Ordered</strong></p>
<ol>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ol>
<!-- -->
<ol>
  <li><a href="http://www.example.com">Example.com</a></li>
  <li><a href="http://www.google.com">Google</a></li>
  <li><a href="http://www.yahoo.com">Yahoo!</a></li>
  <li><a href="http://www.example.com">Another Example.com</a></li>
</ol>
```

The other option is to enable double blank line ending a list option `Parser.LISTS_END_ON_DOUBLE_BLANK` by setting it to `true`, then insert two blank lines to end a list but this is not compatible with standard CommonMark.

```markdown
**Ordered**
1. Item 1
2. Item 2
3. Item 3


1. [Example.com](http://www.example.com)
2. [Google](http://www.google.com)
3. [Yahoo!](http://www.yahoo.com)
4. [Another Example.com](http://www.example.com)
```

Resulting in:

```html
<p><strong>Ordered</strong></p>
<ol>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ol>
<ol>
  <li><a href="http://www.example.com">Example.com</a></li>
  <li><a href="http://www.google.com">Google</a></li>
  <li><a href="http://www.yahoo.com">Yahoo!</a></li>
  <li><a href="http://www.example.com">Another Example.com</a></li>
</ol>
```

**Comment by GomiGuchi** [comment]
@vsch Thank you very much for your reply. I'm trying to parse HTML to store it as markdown, and still be able to display it as HTML again, so I really need to output of `FlexmarkHtmlParser` to result in the same HTML when read by `Parser`.

As far as I can tell, none of the Parser options I set affect `FlexmarkHtmlParser`, but maybe I am not setting the options correctly. Do Parser options have an effect on `FlexmarkHtmlParser`? Is there a way to get the consistent flow through flexmark with lists like this?

**Comment by vsch** [comment]
@GomiGuchi, in general it is impossible to convert HTML to Markdown and have the markdown generate the same HTML. Markdown down is much more limited.

The HTML Parser is not intended as a 100% accurate conversion because it is not possible. It is more of a convenience for converting HTML to Markdown that should be examined and edited for desired results.

That said, if something obvious is messed up like the HTML to Markdown converter generating two consecutive lists without an intervening HTML comment then this is a bug in the HTML to Markdown converter. This needs its own issue. I'll open it.

**Comment by vsch** [comment]
@GomiGuchi, issue opened #138
