### ISSUE TITLE
flexmark-profile-pegdown dependency related

### ISSUE THREAD

**Issue by rkanumola** [vsch/flexmark-java#137]
@vsch , we are using `flexmark-profile-pegdown ` module for our migration, In that jar dependency tree we could see that **junit** is included because of  `com.vladsch.flexmark:flexmark-test-util:jar:0.22.18`. We would like to know is this is intentional/required or something we can exclude? And also is there any  other jars which are part of this dependency can be excluded part of our migration, please suggest?

```
[INFO] \- com.vladsch.flexmark:flexmark-profile-pegdown:jar:0.22.18:compile
[INFO]    +- com.vladsch.flexmark:flexmark:jar:0.22.18:compile
[INFO]    |  \- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-abbreviation:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark-ext-autolink:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark-ext-typographic:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile
[INFO]    |     +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |     \- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-anchorlink:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-aside:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- com.vladsch.flexmark:flexmark-jira-converter:jar:0.22.18:compile
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-ext-gfm-strikethrough:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-ext-tables:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-ext-wikilink:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-ext-ins:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-ext-superscript:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  |  \- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-autolink:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- org.nibor.autolink:autolink:jar:0.6.0:compile
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-definition:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-emoji:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark-jira-converter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-escaped-character:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-footnotes:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-gfm-strikethrough:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-gfm-tasklist:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-ins:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-jekyll-front-matter:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- com.vladsch.flexmark:flexmark-ext-yaml-front-matter:jar:0.22.18:compile
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-spec-example:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- com.vladsch.flexmark:flexmark-test-util:jar:0.22.18:compile
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  |  \- junit:junit:jar:4.12:compile
[INFO]    |  |     \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-superscript:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-tables:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-toc:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-typographic:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-wikilink:jar:0.22.18:compile
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:compile - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:compile - omitted for duplicate)
[INFO]    \- com.vladsch.flexmark:flexmark-util:jar:0.22.18:compile

```
This is related to https://github.com/vsch/flexmark-java/issues/105
Let me know if you are not clear and need any other input. Thanks.

**Comment by vsch** [comment]
@rkanumola, the pegdown profile  module includes `flexmark-test-util` only for the `test` scope as it uses it for the tests. For distribution you don't need its jar.

**Comment by bobswift** [comment]
Vlad, maybe I am doing something wrong, but, I am still seeing this with runtime scope. Seems to be coming from com.vladsch.flexmark:flexmark-ext-spec-example

[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ appfire-flexmark ---
[INFO] com.appfire.common:appfire-flexmark:jar:0.22.18
[INFO] \- com.vladsch.flexmark:flexmark-profile-pegdown:jar:0.22.18:runtime
[INFO]    +- com.vladsch.flexmark:flexmark:jar:0.22.18:runtime
[INFO]    |  \- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-abbreviation:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark-ext-autolink:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark-ext-typographic:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime
[INFO]    |     +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |     \- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-anchorlink:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-aside:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- com.vladsch.flexmark:flexmark-jira-converter:jar:0.22.18:runtime
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-ext-gfm-strikethrough:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-ext-tables:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-ext-wikilink:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-ext-ins:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-ext-superscript:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  |  \- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-autolink:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- org.nibor.autolink:autolink:jar:0.6.0:runtime
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-definition:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-emoji:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark-jira-converter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-escaped-character:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-footnotes:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-gfm-strikethrough:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-gfm-tasklist:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-ins:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-jekyll-front-matter:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- com.vladsch.flexmark:flexmark-ext-yaml-front-matter:jar:0.22.18:runtime
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-spec-example:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- com.vladsch.flexmark:flexmark-test-util:jar:0.22.18:runtime
[INFO]    |  |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  |  \- junit:junit:jar:4.12:runtime
[INFO]    |  |     \- org.hamcrest:hamcrest-core:jar:1.3:runtime
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-superscript:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-tables:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-toc:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-typographic:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    +- com.vladsch.flexmark:flexmark-ext-wikilink:jar:0.22.18:runtime
[INFO]    |  +- (com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  +- (com.vladsch.flexmark:flexmark:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    |  \- (com.vladsch.flexmark:flexmark-formatter:jar:0.22.18:runtime - omitted for duplicate)
[INFO]    \- com.vladsch.flexmark:flexmark-util:jar:0.22.18:runtime

**Comment by vsch** [comment]
@rkanumola, sorry about that. It is caused by the `flexmark-ext-spec-example` module.

* Fix: remove `flexmark-ext-spec-example` module from `flexmark-all` dependencies because it  would cause junit to be included in runtime scope.

Making a release in a few minutes.

**Comment by vsch** [comment]
@rkanumola, repo updated. Maven update in progress.

**Comment by bobswift** [comment]
Thanks much!!!

**Comment by vsch** [comment]
@bobswift, you are welcome.

**Comment by bobswift** [comment]
It is still in flexmark-profile-pegdown. Not a big deal as I am excluding flexmark-ext-spec-example  now anyway.

**Comment by vsch** [comment]
@bobswift, you are right. It is there in error. It isn't used by the module.  

Making a release now.
