### ISSUE TITLE
HTML to Markdown converter missing list end for two consecutive lists

### ISSUE THREAD

**Issue by vsch** [vsch/flexmark-java#138]
```html
<p><strong>Ordered</strong></p>
<ol>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ol>
<ol>
  <li><a href="http://www.example.com">Example.com</a></li>
  <li><a href="http://www.google.com">Google</a></li>
  <li><a href="http://www.yahoo.com">Yahoo!</a></li>
  <li><a href="http://www.example.com">Another Example.com</a></li>
</ol>
```

Is converted to:

```markdown
**Ordered**
1. Item 1
2. Item 2
3. Item 3

1. [Example.com](http://www.example.com)
2. [Google](http://www.google.com)
3. [Yahoo!](http://www.yahoo.com)
4. [Another Example.com](http://www.example.com)
```

instead of:

```markdown
**Ordered**
1. Item 1
2. Item 2
3. Item 3

<!-- -->
1. [Example.com](http://www.example.com)
2. [Google](http://www.google.com)
3. [Yahoo!](http://www.yahoo.com)
4. [Another Example.com](http://www.example.com)
```

**Comment by vsch** [comment]
@GomiGuchi, repo updated. Maven release in progress. Sample for changing URLs and output using formatter:   [FormatterWithMods.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/FormatterWithMods.java)

**Comment by vsch** [comment]
motivated by discussion in #132

**Comment by GomiGuchi** [comment]
@vsch That was incredible! I never expected to wake up to a fix already being deployed. Thank you so much for addressing the issue I was having!

**Comment by vsch** [comment]
@GomiGuchi, thank the time zone differences. 😀

**Comment by praneethrreddy** [comment]
@vsch I am facing similar issue while trying to convert md file to HTML. Ordered list is being rendered into first unordered list. Added double blank line to end the list as suggested here, https://github.com/vsch/flexmark-java/issues/132, but no luck. 
My md file data
```
Body

 * Bullet
    * Bullet
       * Bullet
 
 
1. Number
    1. Number
    2. Number  
```
Output:

```
<p>Body</p>
<ul>
<li>
<p>Bullet</p>
<ul>
<li>Bullet
<ul>
<li>Bullet</li>
</ul>
</li>
</ul>
</li>
<li>
<p>Number</p>
<ol>
<li>Number</li>
<li>Number</li>
</ol>
</li>
</ul>
```

Without adding a HTML comment in md file, is there any parsing option that I should try to solve this. Tried different List parsing options from here,  https://github.com/vsch/flexmark-java/wiki/Extensions#list-parsing-options. But no luck. Could you please give some advice.
