### ISSUE TITLE
Setting a custom link string

### ISSUE THREAD

**Issue by bobswift** [vsch/flexmark-java#140]
I am converting a custom link renderer from pegdown to flexmark. Under certain conditions, I need to construct my own link string (it happens to be xhtml) instead of a standard link. In pegdown that was accomplished by using **new Rendering("", link)** where link was the exact string I wanted. How can I do the same thing in flexmark?

**Comment by bobswift** [comment]
Just to clarify, I have a CustomLinkResolver that implements LinkResolver in flexmark from what use to be a CusotmLinkRenderer that extended LinkRendered in pegdown.

**Comment by vsch** [comment]
@bobswift, in flexmark-java the only way to do this is to create a custom node renderer and register the nodes it will handle. See [NodeRendererSample](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/NodeRendererSample.java)

I would recommend overriding Link, Image, LinkRef and ImageRef since these all generate links by starting with the code for these in `CoreNodeRenderer`, at the moment the API does not have a way to handle some rendering and passing the rest to the previously registered renderer. It has been on my to do list and I will be adding it. Giving a custom handler stack that will allow handling of special cases without having to worry about every nuance.

**Comment by vsch** [comment]
@bobswift, changes made to the API to allow node rendering to handle special cases with the rest passed on to the "usual" renderer.

Sample code modified to add a conditional custom renderer [PegdownCustomLinkResolverOptions](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/PegdownCustomLinkResolverOptions.java#L94-L132)


* API Change: add node renderer API for delegating rendering to previously registered node
  renderer stack, allowing partial node rendering customizations with non-customized rendering
  passed to previous renderer.

  * `NodeRendererContext.delegateRender()` to delegate current node rendering to previously
    registered handler for the current node. Should only be called from handler's `render()`
    method. If there is no renderer to which to delegate then the node will not be rendered.
  * `NodeRendererContext.getDelegatedSubContext(Appendable, boolean)` to get a sub-context to be
    used in delegated rendering, this context inherits current node rendering handler and node
    information needed for `delegateRender()` method.
  * Added `DelegatingNodeRendererFactory` which should be implemented by custom renderers which
    rely on delegating some rendering of their nodes to existing renderers. It provides a set of
    `NodeRendererFactory` classes to which this renderer may delegate to provide a controlled
    ordering of renderers independent of registration order.

Making release now.

**Comment by vsch** [comment]
@bobswift, repo updated. Maven update in progress.

**Comment by bobswift** [comment]
Wow! Thanks for the pointers. My understanding of this is very superficial, so even with the tips, it will take me a while to sort out how to make this work. I will have to get back to it later.

**Comment by vsch** [comment]
@bobswift, I can sympathize with the learning curve for the library when it comes to customizations it is more flexible but also more complex than pegdown. 

Based on your description, the sample [PegdownCustomLinkResolverOptions](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/PegdownCustomLinkResolverOptions.java#L94-L132) has condition based on the link node to override standard rendering to make it easier to customize some links while passing others through for standard rendering. 

If you give me more information about what your custom rendering did with pegdown or the pegdown code used, I will be able to give your more usable sample code.

**Comment by bobswift** [comment]
It was really simplistic and I think it was just trial and error to get to making it work with new Rendering("", link) 

```
public class ConfluenceWikiLinkRenderer extends LinkRenderer {
    ...
    @Override
    public Rendering render(WikiLinkNode node) {
        Matcher matcher = CONFLUENCE_WIKI_LINK.matcher(node.getText());
        if (matcher.find()) {
            String link = "..." 
            return new Rendering("", link); // the blank url seems to get ignored
        } else {
            return super.render(node); // do whatever the default is
        }
}
```

**Comment by vsch** [comment]
@bobswift, I am assuming that the link in your code refers to the complete HTML you want to generate for it. For that you can use the `HtmlWriter.raw()` methods.

You would need to change [PegdownCustomLinkResolverOptions.java Lines 117-128](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/PegdownCustomLinkResolverOptions.java#L117-L128)

To:

```
set.add(new NodeRenderingHandler<WikiLink>(WikiLink.class, new CustomNodeRenderer<WikiLink>() {
    @Override
    public void render(WikiLink node, NodeRendererContext context, HtmlWriter html) {
        // test the node to see if it needs overriding
        Matcher matcher = CONFLUENCE_WIKI_LINK.matcher(node.getChars());
        if (matcher.find()) {
            String link = "...";
            html.raw(link);
        } else {
            // otherwise pass it for default rendering
            context.delegateRender();
        }
    }
}));
```

**Comment by bobswift** [comment]
Thanks! I will have a try at that tomorrow. I appreciate your help.

**Comment by bobswift** [comment]
So, I think it is roughly changing from a CustomLinkResolver to a CustomLinkRenderer where I can use the html.raw(link) as you have above ...  . That seems pretty straightforward now.  Seems to be working!!!public class CustomLinkRenderer implements NodeRenderer {

    public static class Factory implements DelegatingNodeRendererFactory {
        @Override
        public NodeRenderer create(final DataHolder options) {
            return new CustomLinkRenderer();
        }

        @Override
        public Set<Class<? extends NodeRendererFactory>> getDelegates() {

            Set<Class<? extends NodeRendererFactory>> set = new HashSet<Class<? extends NodeRendererFactory>>();
            // add node renderer factory classes to which this renderer will delegate some of its rendering
            // core node renderer is assumed to have all depend it so there is no need to add it
            set.add(WikiLinkNodeRenderer.Factory.class);
            return set;

            // return null if renderer does not delegate or delegates only to core node renderer
            // return null;
        }
    };

    @Override
    public Set<NodeRenderingHandler<?>> getNodeRenderingHandlers() {

        HashSet<NodeRenderingHandler<?>> set = new HashSet<NodeRenderingHandler<?>>();

        set.add(new NodeRenderingHandler<WikiLink>(WikiLink.class, new CustomNodeRenderer<WikiLink>() {
            @Override
            public void render(WikiLink node, NodeRendererContext context, HtmlWriter html) {

                // custom link generation logic goes here - return a link string if we match the node to something we need to act on
                String link = getLink(node);
                if (link != null) {
                    html.raw(link);
                } else {
                    // otherwise pass it along for default rendering
                    context.delegateRender();
                }
            }
        }));
        return set;
    }
   ...
}
```

**Comment by vsch** [comment]
@bobswift, yes. If you are not using standard link rendering then there is no point in implementing a link resolver since you will render the link yourself. Link resolver is only needed to make default link rendering generate the right URL.

The changes from pegdown to flexmark-java are only serious in parsing extensions. The rest is usually easier in flexmark-java.

**Comment by bobswift** [comment]
Just to be clear, I am only handling one specific case where I will provide the link directly. Otherwise, every other case should just be handled normally. And this appears to be what is happening. The logic is virtually the same as before and even a bit easier with flexmark - it just bails out (link == null) to get back to the default handling as soon as the special case matching fails. 

Anyway, thanks very much for all the help. I have more testing to do, but, I think this is it.

**Comment by vsch** [comment]
@bobswift, you are welcome. Don't hesitate to open an issue if you find anything else.
