### ISSUE TITLE
Cannot Use on Android

### ISSUE THREAD

**Issue by christopherperry** [vsch/flexmark-java#142]
When I try to build and deploy I get the following error:

<img width="921" alt="screen shot 2017-08-07 at 12 21 02 pm" src="https://user-images.githubusercontent.com/1331096/29042249-02c6d7bc-7b6b-11e7-9fa1-0a415462a07d.png">

**Comment by vsch** [comment]
@christopherperry, unfortunately I don't know anything about Android development. I will tag this with help wanted and hope someone can help you.

Setting up android development and adding tests to make sure this library can work is on my to do list.

**Comment by rshah** [comment]
I decided to use this library in my android app and created a simple android app (empty activity) with min api level 21 (android 5) and target sdk level 27.

I used sample code from the readme then run the app, and it was running without problem.
I could see the html string result.
