### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Diomac13** [vsch/flexmark-java#145]
How do I implement this in Confluence (if possible) and can you specify the steps for the installation. I want to integrate confluence and markdown so that it displays markdown in my confluence pages. 

Is there any special configuration necessary or a working application link between confluence and bitbucket is enough?

**Comment by vsch** [comment]
@Diomac13, don't know anything about Confluence or what you mean about "installation".  This repo is a Java library for parsing Markdown to an AST and then rendering it to HTML, Markdown.
