### ISSUE TITLE
Generate single Javadoc encompassing all sub-projects

### ISSUE THREAD

**Issue by StrangeNoises** [vsch/flexmark-java#148]
It's very difficult to actually get a Javadoc for flexmark-java allowing one to navigate between classes on different sub-projects of the main project. eg: from com.vladsch.flexmark.parser.Parser.parse() to com.vladsch.flexmark.ast.Document, the return type of the parse() methods, which is in the flexmark-util subproject. The external link in this case from the former to the latter is: https://github.com/vsch/flexmark-java/flexmark-util/apidocs/com/vladsch/flexmark/ast/Document.html?is-external=true which is dead. This makes it inconvenient to try to follow the API as you're having to track across potentially numerous different generated apidocs.

It would be appreciated if the javadocs could be generated somewhere in complete form, say, in mave-central under flexmark-all. Or at least that the external links work. The fact the external links get generated implies there's a way that's expected to work. Even if there's a maven target to do so oneself for local use only, that would help.

If such a thing already exists, apologies, I couldn't find it. This issue report then becomes one to make it more prominent in the documentation. :-)

**Comment by vsch** [comment]
@StrangeNoises, java docs now available on https://www.javadoc.io/doc/com.vladsch.flexmark/flexmark/0.34.22
