### ISSUE TITLE
no anchor links in HTML

### ISSUE THREAD

**Issue by JFormDesigner** [vsch/flexmark-java#15]
The AnchorLink extension does not add anchor links to rendered HTML, but they are in the AST.

```java
String markdown = "# head1\n\n## head2\n\nsome text";

Parser parser = Parser.builder()
		.extensions(Arrays.asList(AnchorLinkExtension.create()))
		.build();
Node document = parser.parse(markdown);
System.out.println(new AstCollectingVisitor().collectAndGetAstText(document));

HtmlRenderer renderer = HtmlRenderer.builder()
		.extensions(Arrays.asList(AnchorLinkExtension.create()))
		.build();
System.out.println(renderer.render(document));
```

The AST (with anchor links):
```
Document[0, 28]
  Heading[0, 7] textOpen:[0, 1, "#"] text:[2, 7, "head1"]
    AnchorLink[2, 7]
      Text[2, 7] chars:[2, 7, "head1"]
  Heading[9, 17] textOpen:[9, 11, "##"] text:[12, 17, "head2"]
    AnchorLink[12, 17]
      Text[12, 17] chars:[12, 17, "head2"]
  Paragraph[19, 28]
    Text[19, 28] chars:[19, 28, "some text"]
```

The HTML output (not anchor links):
```
<h1>head1</h1>
<h2>head2</h2>
<p>some text</p>
```

**Comment by vsch** [comment]
@JFormDesigner, I added the following to extensions wiki:

> :warning: This extension will only render an anchor link for headers that have an id attribute
> associated with them. You need to have the `HtmlRenderer.GENERATE_HEADER_ID` option to set to
> `true` so that header ids are generated.
> 

You may also want to turn of rendering of header id's so that you don't have two elements with the same id. The test does this: [ComboAnchorLinkSpecTest.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-anchorlink/src/test/java/com/vladsch/flexmark/ext/anchorlink/ComboAnchorLinkSpecTest.java#L20-L21)

**Comment by JFormDesigner** [comment]
@vsch many thanks, with `GENERATE_HEADER_ID=true` it works 😃 

However, the need to set an additional option is a little bit unexpected.
The other extensions simply work without any options.

BTW the description of `GENERATE_HEADER_ID` here https://github.com/vsch/flexmark-java/wiki/Extensions#renderer seems incomplete. It ends with
> Use this when an

Could you please complete this. Thanks.

**Comment by vsch** [comment]
@JFormDesigner, docs fixed. I also realized that the problem is the default value for `GENERATE_HEADER_ID`. It should be `true` by default. Fixed it for next version.
