### ISSUE TITLE
render mathematical formula

### ISSUE THREAD

**Issue by Hxuhao233** [vsch/flexmark-java#150]
Hi,@vsch
I found a JavaScript display engine for mathematics, [mathjax](https://www.mathjax.org/)
Do you plan to add some extensions to render the mathematical formula ?
such as
```
\\[ x = {-b \pm \sqrt{b^2-4ac} \over 2a} \\] 
```
to 
![image](https://user-images.githubusercontent.com/15798755/29924224-e4ec087a-8e8e-11e7-90a9-53cced1d95a3.png)

**Comment by vsch** [comment]
@Hxuhao233, it is on my to do list. My plugin users have been requesting this too. idea-https://github.com/vsch/idea-multimarkdown/issues/467

**Comment by vsch** [comment]
@Hxuhao233, GitLab Flavoured Markdown extension added. It supports inline and fenced code math blocks with LaTeX in HTML via Katex and charts via Mermaid.

https://github.com/vsch/flexmark-java/wiki/Extensions#gitlab-flavoured-markdown

**Comment by Hxuhao233** [comment]
Wow,This is really a good extension ！

**Comment by vsch** [comment]
@Hxuhao233, I agree. 

Took me a while to settle on math extension that was popular and fit well into the CommonMark/Markdown philosophy.
