### ISSUE TITLE
XHTML support

### ISSUE THREAD

**Issue by madhead** [vsch/flexmark-java#151]
Not really an issue, just a question: what is the state of XHTML support in flexmark. Looks like the output is XHTML compliant without any moves from my side (e.g. single `<img>`s are closed and so on), but I was not able to quickly find any official info about XHTML support. Can you please clarify?

Thanks!

**Comment by vsch** [comment]
@madhead, the core node renderer generates XHTML compliant output. If you find an occasion where it does not then please report it as a bug.

**Comment by madhead** [comment]
@vsch thanks for a quick reply. No, I don't see any XHTML violations in the output, and that's cool. Just wanted to be sure.
