### ISSUE TITLE
Non-code info blocks

### ISSUE THREAD

**Issue by olyas** [vsch/flexmark-java#152]
Hello!

Before I go and write my own extension, I want to validate if there is already a way to extend something existing to create non-code info blocks.

Currently info blocks are something like this:
```
~~~info
my code
~~~

```
which converts into

```
<pre><code class="language-info"> 
my code
</code>
</pre>
```

Where as I am looking to make something that will do:
```
<p class="my-info">
my code
</p>
```

The intention is to standardize how we do alerts, warnings and other non-code call-outs within documentation.

Many thanks for any advice on what's the right path for this.

Cheers,
Olya

**Comment by vsch** [comment]
@olyas, there is not an extension for this but you can easily create an extension with a custom fenced code renderer that renders only `info` tagged ones and passes the rest to the core renderer.

You can use [PegdownCustomLinkResolverOptions](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/PegdownCustomLinkResolverOptions.java#L114-L145) as an example but change the rendering part to:

```java
@Override
public Set<NodeRenderingHandler<?>> getNodeRenderingHandlers() {
    HashSet<NodeRenderingHandler<?>> set = new HashSet<NodeRenderingHandler<?>>();
    set.add(new NodeRenderingHandler<FencedCodeBlock>(FencedCodeBlock.class, new CustomNodeRenderer<FencedCodeBlock>() {
        @Override
        public void render(FencedCodeBlock node, NodeRendererContext context, HtmlWriter html) {
            // test the node to see if it needs overriding
            if (node.getInfo().equals("info")) {
                html.attr("class", "my-info").withAttr().tag("p").line();
                html.text(node.getContentChars().normalizeEOL());
                html.closeTag("p").line();
            } else {
                context.delegateRender();
            }
        }
    }));
    return set;
}
```

Only use what you need from the sample. It is made for pegdown migration sample so you don't need any of the pegdown related stuff.

**Comment by olyas** [comment]
@vsch That's awesome. Thank you for the fast response and the great example.

Kudos on creating a great markdown parser with great documentation and easy implementation. I migrated us from Pegdown with zero experience of dealing with parsers and below-average Java knowledge - and it went _super_ smoothly.  👍

**Comment by vsch** [comment]
@olyas, thank you for the compliment. I wrote the library to migrate my JetBrains markdown  plugin [Markdown Navigator](https://plugins.jetbrains.com/plugin/7896-markdown-navigator) from pegdown. Ease of migration from pegdown was a necessary feature of the library.

**Comment by olyas** [comment]
Thank you Vladimir! I have your example working, so I'm good for the MVP/get it working.

One thing I only now realized: the difference between FencedCodeBlock vs Blockquote - even though both extend Block, once will render HTML/tags (e.g. bold or headers), the other won't.

Ideally, the contents of the node could include bold/italic, headers, and lists. 

I spent some time validating this, but wanted to check. Is the correct approach here is extending/customizing FencedCodeBlockParser, instead of FencedCodeBlock? Or is there another approach that's architecturally more correct?

Many thanks :)

**Comment by vsch** [comment]
@olyas, the fenced code blocks in Markdown treat the content as plain text, this includes all markdown and html tags. This is the limitation of Markdown. Pegdown did the same thing.

Block quotes are Markdown block elements which contain other markdown. So all rendering is passed through.

**Comment by olyas** [comment]
Understood. I rewrote it so that I build a custom full extension: parser, render.
I've used FencedCodeBlock + Aside to build something that takes:


```
|@info
| #### This is my information
|
| Hello world
|
```

and adds a `<span class="aside-info">` around the expected content.

However, I don't understand how to make the Parser not render the `@info` ahead of the rest.

```java
    private static class BlockFactory extends AbstractBlockParserFactory {
        BlockFactory(DataHolder options) {
            super(options);
        }

        public BlockStart tryStart(ParserState state, MatchedBlockParser matchedBlockParser) {
            int nextNonSpace = state.getNextNonSpaceIndex();
            BasedSequence line = state.getLine();
            BasedSequence trySequence = line.subSequence(nextNonSpace, line.length());

            if (isInfoTag(line)) {
            	block.setInfo(line.subSequence(2,line.length()).trim());
                return BlockStart.none(); // I think this has to change, but to what? I shoudn't be parsing this line
            }
            if (isMarker(state, nextNonSpace) && !endsWithMarker(state.getLine())) {
                int newColumn = state.getColumn() + state.getIndent() + 1;
                // optional following space or tab
                if (Parsing.isSpaceOrTab(state.getLine(), nextNonSpace + 1)) {
                    newColumn++;
                }
                return BlockStart.of(new CustomSpecialNoteParser(state.getProperties(),  state.getLine().subSequence(nextNonSpace, nextNonSpace + 1))).atColumn(newColumn);
            } else {
                return BlockStart.none();
            }
        }
    }
```

**Comment by vsch** [comment]
@olyas, it is caused by the `return BlockStart.none` when you parse the info tag. You are effectively telling the parser that you did not want that line.

Am I right to guess that you are keeping a state of the fact that you saw your info line, so you can start your custom parser on the next line? 

You should not rely on your internal saved state in the block parser factory. You can examine the parser's state but keeping one in parallel to the parser is bound to break in the future.

What you really want to return is `return BlockStart.of(parser).atIndex(state.getLineEndIndex());` after seeing the first line and then handle the next line(s) in your custom parser.

With the above line you are telling the parser that you are starting the new block parser and want further parsing to continue after the end of the current line. Effective, you have absorbed and accepted the line with the info.

**Comment by olyas** [comment]
Thank you! With some more clean up and great help from a coworker as well as your comment we got it to work. It's delightful :)
