### ISSUE TITLE
Markdown to docx Conversion extension

### ISSUE THREAD

**Issue by vsch** [vsch/flexmark-java#153]
Conversion from Markdown to docx using docx4j library. Development of this extension is sponsored by **Johner Institut GmbH**

Progress so far:

* [x] Paragraph
* [x] Headings
* [x] Bold and italic text
* [x] Tables
  * [x] multiple header rows, column spans, markdown alignments
  * [x] Table captions are not yet supported by docx4j API
* [x] Ordered and unordered lists
  * [ ] restart numbering on a short to do list
* [x] Images
  * [x] Images get embedded into the document, even remote ones (using http: or https: links)
  * [x] Max Image width property available in options
* [x] Links
* [x] Inline Code
* [x] Fenced Code 
* [x] Block Quotes
* [x] Strike-through, Subscript, Superscript, Underline (Ins) text

Sample doc:

[generated-sample-doc.docx](https://github.com/vsch/flexmark-java/wiki/resources/generated-sample-doc.docx)  
[generated-sample-doc.xml](https://github.com/vsch/flexmark-java/wiki/resources/generated-sample-doc.xml)  
[sample-doc.html](https://github.com/vsch/flexmark-java/wiki/resources/sample-doc.html)  
[sample-doc.md](https://github.com/vsch/flexmark-java/wiki/resources/sample-doc.md)

**Comment by vsch** [comment]
repo updated, maven release in progress.

**Comment by yaytul** [comment]
Seems a bit confusing to find a simple example of markdown to docx in your examples page.
Can you post the code to convert this md file to docx?

**Comment by vsch** [comment]
@yaytul, the documentation for the extension can be found in the wiki: [Docx-Renderer-Extension](https://github.com/vsch/flexmark-java/wiki/Docx-Renderer-Extension)

It also points to working sample code that you can use as a starting point.

The rest, as they say, is left as an exercise for the reader.
