### ISSUE TITLE
[Question] Is it possible to use Sublists inside TaskLists?

### ISSUE THREAD

**Issue by sladkoff** [vsch/flexmark-java#155]
We don't seem to be able to create nested TaskLists or put normal Sublists inside TaskLists by default.

Here are two examples that demonstrate the behavior:

### Input:
```
- [ ] TaskListElement 1
  - Sub 1
  - Sub 2
    - Sub Sub 1
```

### Desired Output

- [ ] TaskListElement 1
  - Sub 1
  - Sub 2
    - Sub Sub 1

### Actual Output

- [ ] TaskListElement 1
- Sub 1
- Sub 2
  - Sub Sub 1

Note the second level elements are actually on the same level as the first-level TaskListElement.

### Input:
```
- [ ] TaskListElement1
  - [ ] Sub TaskListElement1
    - [ ] Sub Sub TaskListElement 1
```

### Desired Output

- [ ] TaskListElement1
  - [ ] Sub TaskListElement1
    - [ ] Sub Sub TaskListElement 1

### Actual Output

- [ ] TaskListElement1
- [ ] Sub TaskListElement1
- [ ] Sub Sub TaskListElement 1

All TaskList elements are on the same level.

Is this the expected behavior or a bug? 

Thank you.

**Comment by vsch** [comment]
@sladkoff, it is an indentation issue. Task lists treated the `[ ]` as part of the item prefix, so the content column was used as the indent for child elements. The sub-items needed to be indented to the text of the item, just like regular list items:

```
- [ ] TaskListElement 1
      - Sub 1
      - Sub 2
        - Sub Sub 1
```

Get the new release 0.27.0 it has an option to choose the behavior for task lists and by default does not treat the task item marker as part of the list item prefix:

From [VERSION.md](https://github.com/vsch/flexmark-java/blob/master/VERSION.md)

* Add: `Parser.LISTS_ITEM_CONTENT_AFTER_SUFFIX`, default `false`, set to `true` to treat the item suffix as part of the list item marker after which the content begins for indentation purposes. Gfm Task List uses the default setting.

**Comment by sladkoff** [comment]
Oops, should have checked the releases first!

Sorry for bothering. It works like a charm now!

I'll let you decide if you want to keep this up for reference or close the issue.

**Comment by vsch** [comment]
@sladkoff, it was easy to miss. Only released last night.
