### ISSUE TITLE
Dependency Conflict - SLF4J

### ISSUE THREAD

**Issue by neverness74** [vsch/flexmark-java#157]
In ```v0.27```, flexmark-java seems to expose a dependency on ```org.slf4j:slf4j-log4j12:jar:1.7.25:compile```, which causes problems for example when using Spring Boot 1.5.6 due to a conflicting dependency.

The symptom is SLF4J warning about multiple bindings, such as:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/.m2/repository/ch/qos/logback/logback-classic/1.1.11/logback-classic-1.1.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```

Per the SLF4J documentation:

```
Embedded components such as libraries or frameworks should not
declare a dependency on any SLF4J binding but only depend on slf4j-api.
```
https://www.slf4j.org/codes.html#multiple_bindings

Any chance flexmark-java could be changed to avoid exposing a full dependency on slf4j? (Note that things still function correctly, in my app at least. The multiple bindings warning is just that, a warning. So this is a low-impact issue... I just don't like the extra warnings when launching my app!)

BTW ```flexmark-java``` is fantastic, keep up the good work!

-- neverness

**Comment by vsch** [comment]
@neverness74, the dependency is coming from docx4j library. If you exclude the `flexmark-docx-converter` module then there should be no dependency on slf4j and a lot more. That library pulls in a lot of dependencies.
