### ISSUE TITLE
Inline extension with different, multiple character delimiters

### ISSUE THREAD

**Issue by drownedincoffee** [vsch/flexmark-java#159]
Hi Vladimir,

We are using pegdown in one of our projects to create our own macros and we are evaluating flexmark as an alternative library, since pegdown is deprecated.

With few prove-of-concepts we found out, that we are able to migrate most of our macros to flexmark. However, there is still one case we were not able to solve. Therefore, we would be grateful if you could point us in the right direction.

We have an inline macro, which has the following syntax:
```
Blah di blah {glossary-ref:appointment}you have to call **first** to get see the doctor.{glossary-ref} blah bli blah blub.
```
* The macro surrounds the text `you have to call **first** to get see the doctor.` with a HTML span-tag
* Other markdown in the macro body will get rendered as well. E.g. the word `**first**`
* Upon mouse-hover, a tooltip shows the definition of the glossary term `appointment`

As far as we could see, flexdown inline extensions start with one or more characters that are defined by an implementation of the DelimiterProcessor:
```
    @Override
    public char getOpeningCharacter() {
        return ':';
    }

    @Override
    public char getClosingCharacter() {
        return ':';
    }

    @Override
    public int getMinLength() {
        return 1;
    }
```
Is there a way to define inline opening and closing delimiters, that consist of more then just one or more of the same character?

Any help is greatly appreciated. Thank you in advance.
Thomas

**Comment by vsch** [comment]
@drownedincoffee, a delimiter is a single character construct so it is the wrong extension in your case.

You should look at the code for `flexmark-ext-xwiki-macros` it has very similar syntax to what you are looking for and handles inline macro elements.

**Comment by vsch** [comment]
@drownedincoffee, specifically the [MacroInlineParser.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-xwiki-macros/src/main/java/com/vladsch/flexmark/ext/xwiki/macros/internal/MacroInlineParser.java) file implements the inline parser.

The [overview](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-xwiki-macros/src/main/javadoc/overview.md) describes the extension.

**Comment by drownedincoffee** [comment]
@vsch , thank you very much for your quick reply. I'm currently not at the office, but I'll look into your tips this Wednesday.
