### ISSUE TITLE
MD - Ast - MD Roundtripping ?

### ISSUE THREAD

**Issue by spand** [vsch/flexmark-java#160]
Is it possible to parse markdown to an ast and then output that back to markdown ? And if so, can I expect it to be identical to the initial markdown text? I figure there might be a lossy process somewhere

**Comment by vsch** [comment]
@spand, the AST is loss-less with offsets into original source available for every part of a parsed element, not only the element itself. 

The parser can be setup to include blank line nodes in the AST, which by default are not included. With this option the AST is complete with all elements in your source. Set `Parser.BLANK_LINES_IN_AST` to `true` to have blank line nodes in AST.

As for outputting identical markdown is concerned, it is up to you. I don't see why you would want identical as opposed to syntactically identical but cleaned up, as done by the `flexmark-formatter` module.

You can look at the `flexmark-formatter` module implementation for details on how it is used. 

It does a lot more than just output the same markdown. It can re-arrange non-rendered elements: references, footnotes, abbreviations; renumber ordered items, sort list items, change format for different parser rules, etc. 

It will give you a good start for idiosyncrasies of rendering AST to Markdown.

**Comment by spand** [comment]
I intend to rewrite certain custom nodes while a user is in the process of writing his document so the lossless aspect is to minimize disruption of her writing process.

Is there anything else I should be aware of while altering the ast ?

Thanks for the quick response!

**Comment by vsch** [comment]
Since all strings in the AST are fragments of the original string there is a bit of overhead of modifying strings in the AST.

All strings are an instances of `BasedSequence` whose base string is the original full parse text. 

An example of inserting an element into the AST with a string you can find in [SyntheticLinkSample](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/SyntheticLinkSample.java#L67-L76)

**Comment by vsch** [comment]
@spand, you are probably better off using the AST for the user text but then building your replacement text the way formatter does it. That way you will not need to modify the AST and can generate whatever replacement text you want.

Unless you are using the AST afterwards for something other than generating the replacement markdown, you are better off with the second approach. If you need the AST with modified text then you are still better off building the "modified" markdown text (formatter style) and just re-parsing it to get the AST with modifications.
