### ISSUE TITLE
How to parse latex?

### ISSUE THREAD

**Issue by CQU-CST-WuErli** [vsch/flexmark-java#161]
I try to find some options to parse latex but failed.

**Comment by vsch** [comment]
Flexmark-java does not parse latex and does not yet have a latex extension which would allow wrapping of latex text.

**Comment by AndreVanDelft** [comment]
Could you indicate about when you expect LaTeX support to be ready?
I am using FlexMark in a [PowerPoint generator](www.slidemight.com), and would like to support math formulas.

**Comment by vsch** [comment]
@AndreVanDelft, I don't know if this will help but GitLab Flavoured Markdown extension added to next version. It supports inline and fenced code math blocks with LaTeX in HTML via Katex and charts via Mermaid.

https://github.com/vsch/flexmark-java/wiki/Extensions#gitlab-flavoured-markdown
