### ISSUE TITLE
BasedSequenceImpl.prefix seems broken. Unable to handle zero length string as other

### ISSUE THREAD

**Issue by spand** [vsch/flexmark-java#163]
In most other code I have encountered prefixes and suffixes can be empty also. In this case I would expect the 1 to be a prefix of the empty string between 1 and 2. This is specified in the second assert. The first passes.

```
    @Test
    public void basedPrefix(){
        BasedSequence of = BasedSequenceImpl.of("12");
        assertEquals(BasedSequenceImpl.of("1"), of.baseSubSequence(0, 2).prefixOf(of.subSequence(1, 2)));
        assertEquals(BasedSequenceImpl.of("1"), of.baseSubSequence(0, 1).prefixOf(of.subSequence(1, 1)));
    }
```

**Comment by vsch** [comment]
@spand, I will add a fix for this.

**Comment by spand** [comment]
Thank you. Your library is much appreciated :)
