### ISSUE TITLE
Error orrured when parsing  C++ code

### ISSUE THREAD

**Issue by CQU-CST-WuErli** [vsch/flexmark-java#165]
I write some C++ code in my article but it will add some '#' before '#' or '%', for example '#incluede<cmath>' ==> '##include<cmath>', 'scanf("%d", &a);' ==> 'scanf("#%d", &a);'

**Comment by vsch** [comment]
@CQU-CST-WuErli, by "add some `#` do you mean in the rendered HTML or somewhere else.

Can you please be a bit more specific about what you are doing?

**Comment by CQU-CST-WuErli** [comment]
Sorry for my poor English. I mean there is a sentence like '#include<iostream>' in markdown and it will be rendered into '<code><pre>##include<iostream></pre></code>'. It also happened to 'scanf("%d", &a);'. just like I said before.

**Comment by vsch** [comment]
@CQU-CST-WuErli, your english is fine.

Can you please provide the actual markdown text you are using and also the resulting HTML. It will make use of English or any other language superfluous.

The best way to report an issue is to include the markdown source. For example use this to show markdown:

    ```markdown
    #include abc.h
    
    void test(int n) {
        sprintf("%d", n);
    }
    ```

So it will look like this:

```markdown
#include abc.h

void test(int n) {
    sprintf("%d", n);
}
```

Then to include what you are getting, for example for HTML:

    ```html
    <p>#include abc.h</p>
    <p>void test(int n) {
    sprintf(&ldquo;%d&rdquo;, n);
    }</p>
    ```

It will show up as:

```html
<p>#include abc.h</p>
<p>void test(int n) {
sprintf(&ldquo;%d&rdquo;, n);
}</p>
```

Then if possible to state what you are expecting to see:

    ```html
    <p>#include abc.h</p>
    <p>void test(int n) {
    sprintf(&ldquo;%d&rdquo;, n);
    }</p>
    ```

It will show up as:

```html
<p>#include abc.h</p>
<p>void test(int n) {
sprintf(&ldquo;%d&rdquo;, n);
}</p>
```

By the way this is what I get when I use the sample markdown text.

**Comment by CQU-CST-WuErli** [comment]
```
```html
<p>#include abc.h</p>
<p>void test(int n) {
sprintf(&ldquo;%d&rdquo;, n);
}</p>
```

**Comment by CQU-CST-WuErli** [comment]
Finally I solve the problem by checking the text in my database. I changed the table's character set and that's the reason for this problem. By the way flexmark-java is good and thanks for telling me how to report an issue. :）

**Comment by vsch** [comment]
@CQU-CST-WuErli, just trying to make solving issues easier for both of us. ;)
