### ISSUE TITLE
Prevent wrapping in <p> tags

### ISSUE THREAD

**Issue by dflorey** [vsch/flexmark-java#166]
Is there a simple way to prevent the nesting `<p>` tags when generating html from markdown?

**Comment by vsch** [comment]
@dflorey, can you give me the source markdown you are converting and what HTML result you are getting?

It should not create nested `p` tags since this is not valid HTML and is a bug that I need to address.

**Comment by dflorey** [comment]
Sorry for the confusion - I was just talking about the enclosing `<p> </p>` tags.
E.g. when converting markdown `hello` to markup `<p>hello</p>`
I'd like to get the html without enclosing paragraph (of course I can just remove it by using substring, but probably there is a simple command to avoid generating it in the first place?)
Thanks again for your great software!!

**Comment by vsch** [comment]
@dflorey, there is no option for this but you can easily do this by creating a custom node renderer for paragraphs.

Take a look at the `flexmark-java-samples` module it has a `NodeRendererSample`. Keep in mind that paragraphs are also used to wrap loose list items so you may have to check the paragraph node's context to see if you want it to wrap its children in `<p>` tags.
