### ISSUE TITLE
Help with migrating from pegdown to flexmark-java

### ISSUE THREAD

**Issue by paladox** [vsch/flexmark-java#170]
Hi, could we have some help with migrating from pegdown to flexmark-java please?

I've read the migration docs but it dosen't really say what to do if you do something like https://github.com/GerritCodeReview/gerrit/blob/master/java/com/google/gerrit/server/documentation/MarkdownFormatter.java

That file is then read into https://github.com/GerritCodeReview/gerrit/blob/09786353f76b778a76a61a092adf60a41fbc3cfd/java/com/google/gerrit/httpd/plugins/HttpPluginServlet.java#L498

**Comment by paladox** [comment]
I've managed to do it here https://gerrit-review.googlesource.com/#/c/gerrit/+/138774/

though how do i migrate it so it works for finding a children for the title please?

**Comment by vsch** [comment]
@paladox, the heading search to determine the document title can be found in the maven doxia project which recently migrated to flexmark-java from pegdown.

Specifically the code traversing the AST can be found here: https://github.com/vsch/maven-doxia/blob/63a9e0de2d4012b5eacc965413017b379640822f/doxia-modules/doxia-module-markdown/src/main/java/org/apache/maven/doxia/module/markdown/MarkdownParser.java#L214-L235

Above link is to my fork since I am not sure at what stage the merging process is at in the main project.

The [`flexmark-java-samples`](https://github.com/vsch/flexmark-java/tree/master/flexmark-java-samples/src/com/vladsch/flexmark/samples) module has samples for many API features of the library, including samples created to help users migrate from pegdown. The visitor sample has a generic visitor example which can be used to visit any and all nodes in the AST.

**Comment by paladox** [comment]
Thankyou :).

I will try that.

**Comment by paladox** [comment]
It manages to find something but it is finding for example <ul> and <li>

with a bullet point that link to another page.

It does <title> but then it is hidden.

**Comment by paladox** [comment]
<img width="1439" alt="screen shot 2017-11-06 at 00 31 10" src="https://user-images.githubusercontent.com/5727000/32420896-d8704b22-c289-11e7-9bb1-28f44e796834.png">

this is what i see ^^.

Though i am expecting it to do it to "Plugin commit-message-length-validator" for example.

**Comment by vsch** [comment]
Can you give me the snippet of the actual markdown that is being parsed up to and including the "Documentation" heading as fenced-code in a comment
 

    ```markdown
    # Plugin commit-message.....
    ....
    ```
    
and the java code used to parse for the heading too. For example:

    ```java
            if ( !haveTitle && rootNode.hasChildren() )
            {
                // use the first (non-comment) node only if it is a heading
                Node firstNode = rootNode.getFirstChild();
                while ( firstNode != null && !( firstNode instanceof Heading ) )
                {
                    if ( !( firstNode instanceof HtmlCommentBlock ) )
                    {
                        break;
                    }
                    firstNode = firstNode.getNext();
                }
    
    
                if ( firstNode instanceof Heading )
                {
                    html.append( "<title>" );
                    TextCollectingVisitor collectingVisitor = new TextCollectingVisitor();
                    String headingText = collectingVisitor.collectAndGetText( firstNode );
                    html.append( StringEscapeUtils.escapeXml( headingText ) );
                    html.append( "</title>" );
                }
            }
    ```

Note that the maven doxia looks for the first non-comment node and if it is a heading, it will use it. Your criteria may be different.

**Comment by paladox** [comment]
Hi, im not exactly sure what markdown is being used as we use HttpPluginServlet to generate the index.html file. The rest is generated in the .md file ext.

The java code i use is

```java
    if (root.hasChildren()) {
      Node firstNode = root.getFirstChild();
      while ( firstNode != null && !( firstNode instanceof Heading ) ) {
        if ( !( firstNode instanceof HtmlCommentBlock ) ) {
          break;
        }
        firstNode = firstNode.getNext();
      }
      if ( firstNode instanceof Heading ) {
        StringBuilder b = new StringBuilder();
        b.append("<title>");
        TextCollectingVisitor collectingVisitor = new TextCollectingVisitor();
        String headingText = collectingVisitor.collectAndGetText(firstNode);
        b.append(headingText);
        b.append("</title>");
        return b.toString();
      }
    }
```

https://gerrit-review.googlesource.com/#/c/gerrit/+/138774/

**Comment by paladox** [comment]
This is what it looks like when using the old pegdown parser

<img width="1440" alt="screen shot 2017-11-06 at 00 49 12" src="https://user-images.githubusercontent.com/5727000/32421078-61ad8f7e-c28c-11e7-864e-f959014c3be4.png">

**Comment by paladox** [comment]
This is what the prevous code was

```java
    if (root instanceof HeaderNode) {
      HeaderNode h = (HeaderNode) root;
      if (h.getLevel() == 1 && h.getChildren() != null && !h.getChildren().isEmpty()) {
        StringBuilder b = new StringBuilder();
        for (Node n : root.getChildren()) {
          if (n instanceof TextNode) {
            b.append(((TextNode) n).getText());
          }
        }
        return b.toString();
      }
    }

    for (Node n : root.getChildren()) {
      String title = findTitle(n);
      if (title != null) {
        return title;
      }
    }
    return null;
```

**Comment by vsch** [comment]
Give me a few minutes to create a new sample specific to your requirements for title search.

**Comment by vsch** [comment]
@paladox, I added a [TitleExtract.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/TitleExtract.java#L20-L41) sample which does what the old pegdown code used to do but with flexmark-java AST.

The input is based on your screenshots as best as I could figure it out:

```markdown
# Plugin commit-message-length-validator

Vendor
:  Gerrit Code Review

Version
:  v2.15-rc2

## About

This plugin checks the length of a commit's commit message subject and body, and reports warnings and errors to the git client if the lentghts are exceeded.

## Documentation

* [Commit Message Length Configuration](config.md)
* More Items

```

The output of the code extracts the title and outputs the HTML:

```
Title: Plugin commit-message-length-validator
<h1><a href="#plugin-commit-message-length-validator" id="plugin-commit-message-length-validator">Plugin commit-message-length-validator</a></h1>
<dl>
  <dt>Vendor</dt>
  <dd>Gerrit Code Review</dd>
  <dt>Version</dt>
  <dd>v2.15-rc2</dd>
</dl>
<h2><a href="#about" id="about">About</a></h2>
<p>This plugin checks the length of a commit&rsquo;s commit message subject and body, and reports warnings and errors to the git client if the lentghts are exceeded.</p>
<h2><a href="#documentation" id="documentation">Documentation</a></h2>
<ul>
  <li><a href="config.md">Commit Message Length Configuration</a></li>
  <li>More Items</li>
</ul>
```

**Comment by vsch** [comment]
Hope this helps.

**Comment by paladox** [comment]
Hi thankyou so much for that :)

But still not adding <title></title> to "Plugin commit-message-length-validator"

<img width="1440" alt="screen shot 2017-11-06 at 01 53 17" src="https://user-images.githubusercontent.com/5727000/32422027-8a5c542e-c295-11e7-9c26-b7abcc4f04ab.png">

**Comment by vsch** [comment]
@paladox, can you open the `<head>...</head>` node so we can see its content. That is where the `<title>` tag goes.

**Comment by paladox** [comment]
Yep title is there

<img width="1440" alt="screen shot 2017-11-06 at 01 58 45" src="https://user-images.githubusercontent.com/5727000/32422101-13a299aa-c296-11e7-9a09-44acb9018656.png">

But in the old parser it was making "Plugin commit-message-length-validator" not a hyperlink, in the new one it is making it a hyperlink. (sorry just noticed that now).

thankyou so much for your help too:).

**Comment by paladox** [comment]
I wonder how do I get “Plugin commit-message-length-validator” to not be a hyper link please? (Like in the pegdown parser)

**Comment by vsch** [comment]
@paladox, making the heading into a link was pegdown's default behavior and I don't remember having any exclusions for heading level 1.

This leads me to believe that there could be some customization for the html serializer in the old pegdown implementation that removes the anchor link wrapper for the heading text when it is a level 1 heading.

**Comment by paladox** [comment]
Ah that would also explain why other headings are hyperlink in pegdown too. Could this be an option in flexmark please? Or would that be to much to implement? :)

**Comment by paladox** [comment]
Maybe it’s here https://github.com/sirthias/pegdown/blob/2a514555a84f56fe112155748fc24d84046e9c88/src/main/java/org/pegdown/Parser.java#L284 when it does the level 1 thing.

**Comment by vsch** [comment]
I don't think it is in pegdown code but I could be mistaken. pegdown had a lot of idiosyncrasies in the way it generated some elements.

The easiest way to handle this is to create an extension that skips anchor links for headings level 1. I am working on it now to give you a hand.

It looks like this was dumped in your lap and you had nothing to do with the original implementation so it is hard for you to migrate from code you don't know to new code you don't know.

**Comment by vsch** [comment]
@paladox, I modified the [TitleExtract.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/TitleExtract.java) sample to add a custom extension that skips rendering of anchor links for headings level 1

This is implemented in two static classes and addition of the extension to the options so that rendering will be filtered through the custom extension.

The generated code is now:

```html
<h1 id="plugin-commit-message-length-validator">Plugin commit-message-length-validator</h1>
<dl>
  <dt>Vendor</dt>
  <dd>Gerrit Code Review</dd>
  <dt>Version</dt>
  <dd>v2.15-rc2</dd>
  <dt>commitmessage.maxSubjectLength</dt>
  <dd>Maximum length of the commit message&rsquo;s subject line.  Defaults to 50 if not specified or less than 0.</dd>
</dl>
<h2><a href="#about" id="about">About</a></h2>
<p>This plugin checks the length of a commit&rsquo;s commit message subject and body, and reports warnings and errors to the git client if the lentghts are exceeded.</p>
<h2><a href="#documentation" id="documentation">Documentation</a></h2>
<ul>
  <li><a href="config.md">Commit Message Length Configuration</a></li>
  <li>More Items</li>
</ul>
```

I am working on the tab in definition list bug and will make a new release with a fix for that.

**Comment by paladox** [comment]
Thankyou so so much :)

**Comment by paladox** [comment]
@vsch wondering do you know how i can get the toc working?

In the old parser it was adding the toc, in the new one it is showing this

<img width="1436" alt="screen shot 2017-11-06 at 13 45 32" src="https://user-images.githubusercontent.com/5727000/32443966-d9b46116-c2f8-11e7-89e1-7ea2f0dad3ea.png">

Also the same for Overview. It's showing as "[overview]: #overview Overview" but should be "Overview".

**Comment by paladox** [comment]
@vsch i think i found a bug. If i put another space

ie for example

```
end of text

[rules]: #rules
<a name="rules">Rules</a>
```

^^ that fails.

if i do
```

end of text


[rules]: #rules
<a name="rules">Rules</a>
```


(notice the extra space.)

**Comment by vsch** [comment]
@paladox, the parsing between pegdown and CommonMark, which this library is based on, is different.

pegdown syntactically parses the full markdown text. CommonMark parses it for block constructs then parses the blocks for inlines.

This causes a limitation on how constructs are parsed.

However, that said, I cannot duplicate the issue of needing extra blank line before a reference definition. 

In CommonMark reference definitions can be located as the first elements of a paragraph. This means the first reference definition needs to be preceded by a blank line.

The text:

```markdown
[event-properties]: #event-properties
<a name="event-properties">Event Properties</a>
-----------------------------------------------
```

is a level 2 heading that contains a reference link `[event-properties]` followed by text `: #event-properties` and inline HTML.

Reference definitions are not parsed in heading text.

For full reference of CommonMark specification you should reference  http://spec.commonmark.org/0.28/

The markdown generated will have to be adjusted for the difference between pegdown and flexmark-java. It is not possible to convert flexmark-java to be 100% compatible with pegdown implementation due to differences in the parser architecture. This difference in parsing architecture is what allows flexmark-java to resolve parsing issues of pegdown and a 20x improvement of performance.

**Comment by paladox** [comment]
@vsch thanks, it seems doing that kind of works but then clicking on it wont bring you to it.

because doing <a name="event-properties">Event Properties</a> causes it to have <a> twice thus.

And also doing [test][event-properties] fails it seems if i do that.

But if i do

```
[event-properties]: #event-properties
## Event Properties
```

it works
