### ISSUE TITLE
Include the source jar in flexmark-all releases

### ISSUE THREAD

**Issue by paladox** [vsch/flexmark-java#171]
Hi, could releases include the source jar please? Reason why is because gerrit download's the source jar as it uses bazel.

ERROR: /Users/xxx/Documents/workspace/gerrit/lib/BUILD:113:1: no such package '@flexmark-java//jar': failed [/usr/bin/python, /Users/xxx/Documents/workspace/gerrit/tools/download_file.py, "-o", /private/var/tmp/_bazel_xxx/4e4bb427cd475349ab3944ff29048468/external/flexmark-java/jar/flexmark-all-0.28.0-src.jar, "-u", "MAVEN_CENTRAL:/com/vladsch/flexmark/flexmark-all/0.28.0/flexmark-all-0.28.0-sources.jar"]: Download http://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-all/0.28.0/flexmark-all-0.28.0-sources.jar
curl: (22) The requested URL returned error: 404 Not Found
error using curl: Command '['curl', '--proxy-anyauth', '-ksSfLo', '/Users/xxx/.gerritcodereview/buck-cache/downloaded-artifacts/flexmark-all-0.28.0-src.jar-c90c4a37822977dff40e8b6da4e931bed962fab8', 'http://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-all/0.28.0/flexmark-all-0.28.0-sources.jar']' returned non-zero exit status 22
 and referenced by '//lib:flexmark-java'.
ERROR: Analysis of target '//:release' failed; build aborted: Loading failed.

**Comment by paladox** [comment]
Ah never mind. It's included in http://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.28.0/

**Comment by paladox** [comment]
it seems flexmark dosen't include everything whereas flexmark-all does. But the source jar is not in flexmark-all. Could it be included please?

**Comment by vsch** [comment]
@paladox, flexmark-all is a lazy include which takes most but not all modules. It is a wrapper for the jar files.

I recommend you use the `flexmark-profile-pegdown` dependency which has all modules that it needs as its dependencies. 

If you want to include anything extra you should explicitly add the dependency to that module.

flexmark-all was added for lazy people who want to tinker but not for serious projects.

**Comment by paladox** [comment]
Ah ok thanks for explaning :).

**Comment by paladox** [comment]
@vsch hi, when i depend only on flexmark-profile-pegdown it dosen't seem to bring in the other deps as it fails with

java/com/google/gerrit/server/documentation/MarkdownFormatter.java:23: error: cannot find symbol
import com.vladsch.flexmark.Extension;
                           ^
  symbol:   class Extension
  location: package com.vladsch.flexmark
java/com/google/gerrit/server/documentation/MarkdownFormatter.java:24: error: package com.vladsch.flexmark.ast does not exist
import com.vladsch.flexmark.ast.Block;
                               ^
java/com/google/gerrit/server/documentation/MarkdownFormatter.java:25: error: package com.vladsch.flexmark.ast does not exist
import com.vladsch.flexmark.ast.Heading;
                               ^
java/com/google/gerrit/server/documentation/MarkdownFormatter.java:26: error: package com.vladsch.flexmark.ast does not exist
import com.vladsch.flexmark.ast.Node;
                               ^
java/com/google/gerrit/server/documentation/MarkdownFormatter.java:27: error: package com.vladsch.flexmark.ast.util does not exist
import com.vladsch.flexmark.ast.util.TextCollectingVisitor;
                                    ^
java/com/google/gerrit/server/documentation/MarkdownFormatter.java:28: error: package com.vladsch.flexmark.html does not exist
import com.vladsch.flexmark.html.HtmlRenderer;
                                ^
java/com/google/gerrit/server/documentation/MarkdownFormatter.java:29: error: package com.vladsch.flexmark.parser does not exist
import com.vladsch.flexmark.parser.Parser;
                                  ^
java/com/google/gerrit/server/documentation/MarkdownFormatter.java:31: error: package com.vladsch.flexmark.util.options does not exist
import com.vladsch.flexmark.util.options.MutableDataHolder;


+ alot more errors

If i add all the deps it fixes the problem.

Wondering is that expected?

Thank you for all your help to, your very very helpful :).

**Comment by vsch** [comment]
@paladox, the dependencies of module should be included. I don't know if it is a manual setting but the errors you are getting is from the dependencies of `flexmark-pegdown-profile` module's dependencies.

**Comment by paladox** [comment]
Ah, i think it's because we use bazel which is not maven so it will download a jar and not read the pom file.

**Comment by vsch** [comment]
In that case you will need to specify the dependencies manually.
