### ISSUE TITLE
AutolinkExtension does not add http:// to simple urls starting with www.

### ISSUE THREAD

**Issue by dumboxp** [vsch/flexmark-java#178]
The **AutolinkExtension** of flexmark-java supports URLs, WWW and EMAIL type of links. 

Simplified links starting with "www." are correctly detected **but the required protocol is not added**! Web-browses tread those links as a relative path instead of an absolute URL!

"www.example.com" is rendered to `<a href="www.example.com">link</a>` without the required protocol!

=> In case of simplified links, the default-protocol "http://" has to be added to the href-attribute to make the links work correctly!

**Comment by vsch** [comment]
@dumboxp, thanks for catching this. I will add an option for the prefix for simplified links with `http://` being the default.

**Comment by vsch** [comment]
repo updated for 0.28.14, maven update in progress.

**Comment by vsch** [comment]
BTW, the added prefix is defined in `HtmlRenderer.AUTOLINK_WWW_PREFIX` by default it is `"http://"`.
