### ISSUE TITLE
How do I get blank lines in my visitor?

### ISSUE THREAD

**Issue by jessebarnum** [vsch/flexmark-java#179]
I'm trying to parse a document, and I need to know when blank lines appear. I'm using the NodeVisitor to process each chunk of text. How can my visitor know when it encounters a blank line?

**Comment by vsch** [comment]
@jessebarnum, you can take a look at the `flexmark-formatter` module `CoreNodeFormatter`

However, as all other nodes you should include `BlankLine` node class in your nodes of interest.

[VisitorSample](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/VisitorSample.java) shows the basic structure of visitors. Just add more `new VisitorHandler<` *NodeType* `>` lines for each node type of interest and corresponding `visit` methods.

**Comment by jessebarnum** [comment]
This is not working for me. The blank line visitor does not get called. Am I using this incorrectly?

		```
new NodeVisitor( new VisitHandler<>( Text.class, new Visitor<Text>() {
			@Override
			public void visit( Text text ) {
				String s = text.getChars().toString(); //This works fine
			}
		} ), new VisitHandler<>( BlankLine.class, new Visitor<BlankLine>() {
			@Override
			public void visit( BlankLine node ) {
				System.out.println("Hey, it worked"); //This never gets called
			}
		} ) ).visit( document );
```

**Comment by vsch** [comment]
You need to enable the blank line AST generation by the parser by setting `BLANK_LINES_IN_AST` to true.  https://github.com/vsch/flexmark-java/wiki/Extensions#parser

**Comment by jessebarnum** [comment]
Thank you, that solved the problem.

Are the AST parser options documented?
