### ISSUE TITLE
Support for epub and mobi generation via pandoc

### ISSUE THREAD

**Issue by jvican** [vsch/flexmark-java#192]
Hey there, awesome project 👍 

I was looking into a way of generating epub/mobi files out of flexmark. I've seen there's an old mention to pandoc in [this ticket](https://github.com/vsch/flexmark-java/issues/176) and, given how difficult it would be to translate from flexmark's AST to epub/mobi, I'd like to use pandoc under the hood.
  
I wonder, is there some kind of story about pandoc integration? Has anyone tried before?

**Comment by vsch** [comment]
@jvican, as far as I know the ticket you mentioned is the only user I know that uses flexmark-java to re-format commonmark for pandoc.

I don't know the details but think that he uses the commonmark settings for parsing to generate an AST, then uses the formatter with fixed indent options to generate pandoc compatible markdown. You can check the [FormatConverterCommonMark](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/FormatConverterCommonMark.java) for an example of how conversion is done.

**Comment by jvican** [comment]
This is great. I'll try the formatter and I will feed its output to pandoc to see if I can generate these epub/mobi files I wanted. Thank you for the tip.
