### ISSUE TITLE
Support <math> tag as  a block-forming tag

### ISSUE THREAD

**Issue by ssikuro** [vsch/flexmark-java#193]
[Mathematical Markup Language](https://www.w3.org/TR/MathML), also known as MathML, defines `<math>` tag, its end tag, and other tags to be used within the math element, and GitHub markdown seems to support it to a certain degree. Here's an example:
The HTML/MathML code:
```
<math xmlns="http://www.w3.org/1998/Math/MathML">
 <mrow>
   <msup>
     <mfenced>
       <mrow>
         <mi>a</mi>
         <mo>+</mo>
         <mi>b</mi>
       </mrow>
     </mfenced>
     <mn>2</mn>
   </msup>
 </mrow> 
</math>
```
is rendered as:

<math xmlns="http://www.w3.org/1998/Math/MathML">
 <mrow>
   <msup>
     <mfenced>
       <mrow>
         <mi>a</mi>
         <mo>+</mo>
         <mi>b</mi>
       </mrow>
     </mfenced>
     <mn>2</mn>
   </msup>
 </mrow> 
</math>

Flexmark-java seems to work well with math tags except when the math element is on a single line such as:

`<math xmlns="http://www.w3.org/1998/Math/MathML"><mrow><msup><mfenced><mrow><mi>a</mi> <mo>+</mo ><mi>b</mi> </mrow></mfenced><mn>2</mn></msup></mrow></math>
`

In that case, it doesn't recognize `<math>`, `</math>` and text in between the pair of tags as one unit. It divides the text into different pieces. For our application of flexmark-java, it is not desirable. We'd like flexmark-java to return an HTMLBlock even if everything is on a single line.

In our experiment this can be achieved by modifying flexmark/src/main/java/com/vladsch/flexmark/internal/HtmlBlockParser.java and flexmark/src/main/java/com/vladsch/flexmark/internal/HtmlDeepParser.java to add "math|" to the list of the matching patterns.
```
                                     "main|menu|menuitem|meta|" +
+                                   "math|" +
                                     "nav|noframes|" +
```

**Comment by vsch** [comment]
@ssikuro, I will add options to the parser to allow you to define the HTML tags to be recognized as block tags.

**Comment by vsch** [comment]
Updated version 0.28.34 released. Maven update in progress. Now `math` tag is considered a block tag. You can also add/remove block tags from the list to customize the behaviour.

* `Parser.HTML_BLOCK_TAGS` to define the HTML tags treated as HTML block elements, defaults
  are: `address`, `article`, `aside`, `base`, `basefont`, `blockquote`, `body`, `caption`,
  `center`, `col`, `colgroup`, `dd`, `details`, `dialog`, `dir`, `div`, `dl`, `dt`, `fieldset`,
  `figcaption`, `figure`, `footer`, `form`, `frame`, `frameset`, `h1`, `h2`, `h3`, `h4`, `h5`,
  `h6`, `head`, `header`, `hr`, `html`, `iframe`, `legend`, `li`, `link`, `main`, `math`,
  `menu`, `menuitem`, `meta`, `nav`, `noframes`, `ol`, `optgroup`, `option`, `p`, `param`,
  `section`, `source`, `summary`, `table`, `tbody`, `td`, `tfoot`, `th`, `thead`, `title`, `tr`,
  `track`, `ul`

**Comment by ssikuro** [comment]
Thank you for the quick action! I'll close this after verifying the fix.

**Comment by ssikuro** [comment]
The version 0.28.34 worked as expected with respect to math tag handling. Thank you.
