### ISSUE TITLE
com.vladsch.flexmark.ast.Node cannot be resolved

### ISSUE THREAD

**Issue by uptimestar** [vsch/flexmark-java#194]
When I use released jar I get:
The type com.vladsch.flexmark.ast.Node cannot be resolved. It is indirectly referenced from required .class files	MarkdownFilter.java	

Help?

**Comment by vsch** [comment]
@uptimestar, the Node class and many others are in the flexmark-util jar. I think you should include the flexmark.jar with dependencies or specify the flexmark-util.jar dependency explicitly.

**Comment by uptimestar** [comment]
thx

**Comment by uptimestar** [comment]
https://news.google.com/news/amp?caurl=https%3A%2F%2Fnypost.com%2F2018%2F01%2F27%2Fthese-hackers-suicides-are-eerily-similar%2F#pt0-387965

**Comment by vsch** [comment]
@uptimestar, this link works: https://nypost.com/2018/01/27/these-hackers-suicides-are-eerily-similar/

Like inconvenient people, conveniently "suicided" by "Shot twice to the back of the head". We live in a world of illusions and facades.

**Comment by cekvenich** [comment]
Sent my mistake. Can we delete plz?
