### ISSUE TITLE
Add GFM option for more sane nested emphasis delimiter processing than common mark default

### ISSUE THREAD

**Issue by vsch** [vsch/flexmark-java#2]
`**bold*bold-italic*bold**` is parsed in a weird way. 

Default gives completely un-intuitive results: `<em><em>bold</em>bold-italic</em>bold**` which is: <em><em>bold</em>bold-italic</em>bold**

GFM is more intuitive: `<strong>bold<em>bold-italic</em>bold</strong>` which is: <strong>bold<em>bold-italic</em>bold</strong>

If it wasn't part of the spec I would consider it to be a bug.

**Comment by robinst** [comment]
The CommonMark spec changes this in 0.26, see here: http://spec.commonmark.org/dingus/?text=**bold*bold-italic*bold**

See announcement here: https://talk.commonmark.org/t/ann-commonmark-0-26-cmark-0-26-0-commonmark-js-0-26-0/2165

I've implemented the changes in commonmark-java: https://github.com/atlassian/commonmark-java/issues/55

**Comment by vsch** [comment]
@robinst, thanks for the heads up. I will incorporate it.

BTW, the modified parser is working great in the plugin. Still early dev version but I already switched for my use. I absolutely love commonmark-java architecture. 

Every time I have to add an extension, feature or fix a bug I can't help but remark on what a joy it is to work with it. Trying to do the same in pegdown has been giving me Tourette's.

**Comment by vsch** [comment]
merged commonmark-java latest which has this fixed.

**Comment by robinst** [comment]
> BTW, the modified parser is working great in the plugin. Still early dev version but I already switched for my use. I absolutely love commonmark-java architecture. 

Cool, good to hear! I looked at flexmark-java a bit, I might port some things back to commonmark-java :).

**Comment by vsch** [comment]
@robinst, feel free to port anything you like and to comment or make suggestions for improvement.

BTW, the universal options architecture turned out to be of greater benefit than I originally thought. It completely decoupled extension implementation from configuration and allows extensions to really extend all aspects of the document. 

In pegdown, any document wide data had to be added to the RootNode class, equivalent to Document in commonmark-java. There was no way for extensions to add new node collections similar to defined references or add another document property without modifying the RootNode class.

There was also no way to pass context information to inner implementation classes without having to pass it through all intermediate layers. Making for a lot of "useless" parameters at high level that were only needed by lower level implementation code. For example, link resolution in the plugin requires passing environment dependent information like current project, file and other details useless to parser/renderer but needed by the link renderer class, which in pegdown handles any source url to rendered url conversion.

I had to mutilate pegdown source to pass an instance of link renderer that was constructed with these parameters. A maintenance mess. 

With the universal options architecture, I simply define a data key for the needed data and set its value in the options. Extensions pick up what they need in one place. Everything else is handled by the extension architecture. Absolutely simplified and decoupled high-level code from low level configuration needs.
