### ISSUE TITLE
Unique id attribute to correspond with AST object id

### ISSUE THREAD

**Issue by DaveJarvis** [vsch/flexmark-java#20]
Consider the following markdown:

```
# Header 1
Paragraph 1

Paragraph 2, Line 1
Paragraph 2, Line 2
Paragraph 2, Line 3

Paragraph 3, Line 1
#Header 2
```

What effort would be involved in making this generate unique, sequential, IDs that correspond to values in the AST? For example:

```
<h1 id="1">Header 1</h1>
<p id="2">Paragraph 1</p>

<p id="3">
<span id="4">Paragraph 2, Line 1</span>
<span id="5">Paragraph 2, Line 2</span>
<span id="6">Paragraph 2, Line 3</span>
</p>

<p id="7">Paragraph 3, Line 1</p>
<h1 id="8">Header 2</h1>
```

When the user is editing the markdown text:

```
Paragraph 2, Line 2|
```

The AST value for the caret's position would be *5*, which corresponds to the `<span id="5">` value in the HTML document.

**Comment by vsch** [comment]
@DaveJarvis, the place to look is the
`com.vladsch.flexmark.html.renderer.GitHubHeaderIdGenerator`, renamed in the next version to
`com.vladsch.flexmark.html.renderer.HeaderIdGenerator`. 

If you add an extension that registers `HeaderIdGeneratorFactory` using builder's
`HtmlRenderer.Builder.htmlIdGeneratorFactory(HeaderIdGeneratorFactory)` then you can do anything
quite easily. Walk the ast and assign an id to any node you want in a `HashMap<Node, String>`.
Return this id in `HtmlIdGenerator.getId(Node)`

The `HtmlIdGenerator` interface has two methods: `HtmlIdGenerator.generateIds(Document)`, called
before rendering the document so you can prepare all ids, and `HtmlIdGenerator.getId(Node)`, if
it returns a non-empty id then it will be used for the HTML id of the main element of the node.

Registered `AttributeProvider`s can override this also, but the `HtmlIdGenerator` is the best,
most efficient option.

BTW, all configuration options passed to `Parser.Builder` and `HtmlRenderer` are available on
the `Document` node. So you can query for these in `HtmlIdGenerator.generateIds(Document)`. 

I am adding a couple of options to the standard id generator to match ids generated by
`MultiMarkdown`, current one does not use any options. Here is the code to the new one.

Options defined in `HtmlRenderer`:

```java
    final static public DataKey<Boolean> HEADER_ID_GENERATOR_RESOLVE_DUPES = new DataKey<>("HEADER_ID_GENERATOR_RESOLVE_DUPES", true);
    final static public DataKey<String> HEADER_ID_GENERATOR_TO_DASH_CHARS = new DataKey<>("HEADER_ID_GENERATOR_TO_DASH_CHARS", " -_");
```

```java
public class HeaderIdGenerator implements HtmlIdGenerator {
    @Override
    public void generateIds(Document document) {
        final HashMap<String, Integer> headerBaseIds = new HashMap<>();
        final boolean resolveDupes = HtmlRenderer.HEADER_ID_GENERATOR_RESOLVE_DUPES.getFrom(document);
        final String  toDashChars = HtmlRenderer.HEADER_ID_GENERATOR_TO_DASH_CHARS.getFrom(document);

        new AnchorRefTargetBlockVisitor() {
            @Override
            protected void visit(AnchorRefTarget node) {
                String text = node.getAnchorRefText();

                if (!text.isEmpty()) {
                    String baseRefId = generateId(text, toDashChars);

                    if (resolveDupes) {
                        if (headerBaseIds.containsKey(baseRefId)) {
                            int index = headerBaseIds.get(baseRefId);

                            index++;
                            headerBaseIds.put(baseRefId, index);
                            baseRefId += "-" + index;
                        } else {
                            headerBaseIds.put(baseRefId, 0);
                        }
                    }

                    node.setAnchorRefId(baseRefId);
                }
            }
        }.visit(document);
    }

    @Override
    public String getId(Node node) {
        return node instanceof AnchorRefTarget ? ((AnchorRefTarget) node).getAnchorRefId() : null;
    }

    @SuppressWarnings("WeakerAccess")
    public static String generateId(CharSequence headerText, String toDashChars) {
        int iMax = headerText.length();
        StringBuilder baseRefId = new StringBuilder(iMax);
        if (toDashChars == null) toDashChars = " -_";

        for (int i = 0; i < iMax; i++) {
            char c = headerText.charAt(i);
            if (Character.isAlphabetic(c)) baseRefId.append(Character.toLowerCase(c));
            else if (Character.isDigit(c)) baseRefId.append(c);
            else if (toDashChars.indexOf(c) != -1) baseRefId.append('-');
        }
        return baseRefId.toString();
    }

    public static class Factory implements HeaderIdGeneratorFactory {
        @Override
        public HtmlIdGenerator create(NodeRendererContext context) {
            return new HeaderIdGenerator();
        }
    }
}

```

**Comment by DaveJarvis** [comment]
Thank you!

**Comment by lpapazow** [comment]
# Heading
asdasd
1. Second Ordered element one
2. ordered element two
3. ordered element four
I want this not to be a part of the list, but it is
asd
