### ISSUE TITLE
How create wrapper for PlantUML in markdown?

### ISSUE THREAD

**Issue by baobab-it** [vsch/flexmark-java#205]
Hello, would you help with creating a simple wrapper for PlantUML. Or maybe same information how creates it.

Something like:

\`\`\`plant-uml#some-hash
@startuml
Bob -> Alice : hello
@enduml
\`\`\`

to get next strings: `some-hash` for cache parsed result and string

```
@startuml
Bob -> Alice : hello
@enduml
```

And will be nice have extension for PlantUML.

**Comment by vsch** [comment]
@baobab-it, your need seems similar to #152, only the purpose a bit different. Please take a look at it.

**Comment by baobab-it** [comment]
I tested your example, all working ideally! Thank you very much!
