### ISSUE TITLE
Issue extension doesn't support windows new lines

### ISSUE THREAD

**Issue by rnveach** [vsch/flexmark-java#207]
https://github.com/vsch/flexmark-java/blob/07b83fb84047f7d9add8c729d1006c46517aecda/flexmark-ext-gfm-issues/src/main/java/com/vladsch/flexmark/ext/gfm/issues/internal/GfmIssuesInlineParserExtension.java#L13
Expression has `\n` but it doesn't have `\r`. Windows new lines are in the form `\r\n`.
This causes text written as `#1\r\n` to not get recognized and converted to links by the Issue extension, but it will recognize `#1\n` and convert it correctly.

**Comment by rnveach** [comment]
`GfmUsersInlineParserExtension` will have the same issue as it has `\n` in it.

https://github.com/vsch/flexmark-java/blob/07b83fb84047f7d9add8c729d1006c46517aecda/flexmark-ext-gfm-users/src/main/java/com/vladsch/flexmark/ext/gfm/users/internal/GfmUsersInlineParserExtension.java#L13

**Comment by vsch** [comment]
@rnveach, thank you for catching it. I used to develop on Windows and was always annoyed when unix utilities failed to work with "\r\n". Now that I am on OS X, I can see how easy it is to miss this.

**Comment by vsch** [comment]
@rnveach, fixed. Repo updated. Maven update in progress.
