### ISSUE TITLE
Footnote after pre-formatted block

### ISSUE THREAD

**Issue by clartaq** [vsch/flexmark-java#211]
Putting a footnote after a block surrounded by `<pre></pre>` tags does not seem to work.

For example

    Some text[^1] with footnotes.
    
    <pre>
    In the twilight rain
    these brilliant-hued hibiscus -
    A lovely sunset.
    </pre>[^2]
    
    And a subsequent footnote[^3] that renders correctly.
    
    [^1]: The first footnote.
    [^2]: After a `pre` tag.
    [^3]: A subsequent line

Produces what is shown in the attached screen shot.

<img width="421" alt="screenshot 2018-02-28 11 04 25" src="https://user-images.githubusercontent.com/5259392/36797913-37075b8e-1c77-11e8-86d1-16ae939b8dd1.png">

Putting the marker on a separate following line allows the footnote to render, but it is detached from the `<pre></pre>` block.

**Comment by vsch** [comment]
@clartaq, CommonMark does not parse text in an HTML block, last line after the closing tag is still considered part of the block. It is somewhere in the spec: http://spec.commonmark.org/0.28/
