### ISSUE TITLE
Can not parse table markdown

### ISSUE THREAD

**Issue by huaminhquang** [vsch/flexmark-java#212]
Hi vsch,

I am very happy when  i am using your library. It's quite good.
But I am facing with problem from my project. The library can not parse table with Markdown string is

\*\*\*List of names :\*\*\*
| Name|Number|Score|X|Total|
|---|---|---|---|---|
|Andy Cole| 40|34|13|47|

So, how can i parse the table on my case? Please help me on this problem

**Comment by huaminhquang** [comment]
***Danh sách cầu thủ có mùa giải đầu tiên cho một đội bóng tại Premier League ấn tượng nhất :***
| Cầu thủ|Số trận|Bàn thắng|Kiến tạo|Tổng số|
|---|---|---|---|---|
|Andy Cole| 40|34|13|47|
|Robin van Persie |38|26|9|35
|Kevin Phillips| 36|30|4|34|
|Alan Shearer| 31|25|7|32|
|Jimmy Floyd Hasselbaink |35|23|9|32|
|Mohamed Salah| 27|23|8|31|
|Les Ferdinand |37|25|6|31|
|Sergio Aguero |34|23|8|31|
|Jurgen Klinsmann| 41|20|10|30|
|Carlos Tevez |35|23|7|30|

**Comment by vsch** [comment]
@huaminhquang, tables are block elements that need a blank line before.

```markdown
\*\*\*List of names :\*\*\*

| Name|Number|Score|X|Total|
|---|---|---|---|---|
|Andy Cole| 40|34|13|47|
```

\*\*\*List of names :\*\*\*

| Name|Number|Score|X|Total|
|---|---|---|---|---|
|Andy Cole| 40|34|13|47|

**Comment by huaminhquang** [comment]
@vsch : I undertand your answer, but from my side, data is returned from server side, they dont want to add more blank line before it. Can we do anything to parse the current string to table without more blank line?

**Comment by vsch** [comment]
@huaminhquang, if the server insists on sending invalid markdown then the only choice you have is to pre-process the text to turn it into valid markdown.

You need to add blank lines before tables, then try to parse the markdown.
