### ISSUE TITLE
Jekyll Tag "include"

### ISSUE THREAD

**Issue by almondtools** [vsch/flexmark-java#220]
I tried a snippet found at https://github.com/vsch/flexmark-java/wiki/Usage#include-markdown-and-html-file-content with a markdown file containing `{% include ... %}`.

JekyllTagExtension.TAG_LIST was empty, so debugged into the code and found out that in my case the `JekyllTagInlineParser` is used. Here I find the line `if (!listIncludesOnly || tagName.equals("includes"))` while `JekyllTagBlockParser` uses the line `if (!listIncludesOnly || tagName.equals("include"))`. 

I am not familiar with Jekyll (I only want to use the include feature), yet it seems suspicious to me that one parser uses `include` and another uses `includes`. Besides ``{% includes ... %}` is not handled properly (nothing is included).

**Comment by vsch** [comment]
@almondtools, thank you for catching it. It looks like a bug.

**Comment by vsch** [comment]
@almondtools, the proper tag is `{% include %}`. Fixed for version 0.34.8
