### ISSUE TITLE
BlankLine nodes within IndentedCodeBlock

### ISSUE THREAD

**Issue by ssikuro** [vsch/flexmark-java#225]
I am using `new MutableDataSet().set(Parser.BLANK_LINES_IN_AST, true)` (and more) to configure the Parser. 
To this input:
```
    indented code line 1

    indented code line 3

End of indented block
```
the Parser generates a node tree like this:
```
Document[0, 74]
 IndentedCodeBlock[4, 51]
 BlankLine[25, 26]
 BlankLine[51, 52]
 Paragraph[52, 74]
  Text[52, 73] chars:[52, 73, "End o … block"]
```
I was expecting one BlankLine node for the line after the indented code block because the blank line after "indented code line 1" is part of the code block and is included in the IntendedCodeBlock node. Is this an intended behavior? Is there any config option to avoid this kind of double counting?

**Comment by vsch** [comment]
@ssikuro, bug. Blank lines should not be part of the indented code or fenced code blocks.

I'll fix it because it can cause all kinds of problems because the nodes are no longer sequential.

**Comment by ssikuro** [comment]
Thank you for fixing this. For some reason I didn't get this update in email. Now I can get rid of a hacky work-around code I wrote. I'll close this after verifying the fix.

**Comment by ssikuro** [comment]
I tested my code after updating flexmark version to 0.32.20 and removing the temporary fix up code, and it worked!

There is one case which I am not sure if it is correct or not.

The input document (in Java string format): `---\n\n` (5 bytes).  

This node tree:
```
Document[0, 5]
 YamlFrontMatterBlock[0, 5]
```
There is no BlankLine node.

I have YamlFrontMatterExtension enabled, and I don't know what is the correct parsing behavior when it sees just `---\n` without Yaml expressions or the closing `---\n` following. If you believe this is the intended behavior, please feel free to close this issue.

p.s. I have not changed my configuration to use Common Mark instead of GitHub as you suggested in #227 yet.

**Comment by vsch** [comment]
@ssikuro, the Yaml front matter extension is from commonmark-java original project and I only updated it for source information in the AST, as such it does not have blank line information but does parse the Yaml. The extension I use is Jekyll front matter and it does no parsing of Yaml, just spans the block. The parsing of yaml can be done outside of the library.

Yaml and Jekyll front matter will absorb the whole document if not terminated. For what it is supposed to do I would suggest documentation for Jekyll. I am not an expert on this.

**Comment by ssikuro** [comment]
Where can I find documentation about Jekyll front matter? In the [Extensions](https://github.com/vsch/flexmark-java/wiki/Extensions) page, I only see Jekyll Tags.

**Comment by vsch** [comment]
@ssikuro, it has been a while since I looked so I don't have all the links and do remember that it is not all in one place. A good place is YAML spec, specifically YAML character streams: http://yaml.org/spec/1.2/spec.html#YAML because that what YAML front matter is.

I never got deep into it but was considering making parsing options such as emulation profile and some element parsing tweaks configurable as YAML front matter meta data. That way parsing nuances of the document would be set by the document and not the parser. I think in the end a standard for specifying how a markdown document expects to be parsed would go a long way to make Markdown predictable.

**Comment by ssikuro** [comment]
Thank you so much!
