### ISSUE TITLE
ATX heading doesn't interrupt the list

### ISSUE THREAD

**Issue by ssikuro** [vsch/flexmark-java#227]
This input document
```
* An ATX heading follows immediately after this list.
### Testing Issue 708
```
is parsed by Flexmark and it generates this node tree:
```
Document[0, 76]
 BulletList[0, 75] isTight
  BulletListItem[0, 75] open:[0, 1, "*"] isTight
   Paragraph[2, 54]
    Text[2, 53] chars:[2, 53, "An AT … list."]
   Heading[54, 75] textOpen:[54, 57, "###"] text:[58, 75, "Testing Issue 708"]
    Text[58, 75] chars:[58, 75, "Testi … e 708"]
```
It is interpreting the heading is part of the list item.  But at least GitHub interpret this as a list, followed by an independent heading. Well I'm not too sure but it looks like it is.

Is there an option to make an ATX heading interrupts the list that it follows (without a blank line) ?

This is the config option I am using, in case it matters:
```
MutableDataHolder OPTIONS = new MutableDataSet()
            .set(Parser.PARSER_EMULATION_PROFILE, ParserEmulationProfile.GITHUB_DOC)
            .set(Parser.EXTENSIONS, Arrays.asList(StrikethroughSubscriptExtension.create(),
                                                  TablesExtension.create(),
                                                  YamlFrontMatterExtension.create()
                                                  ))
            .set(Parser.HEADING_NO_ATX_SPACE, true)
            .set(Parser.BLANK_LINES_IN_AST, true)
            ;
```

**Comment by vsch** [comment]
@ssikuro, GitHub Doc is for Old GitHub markdown implementation. They switched to CommonMark. You should use CommonMark and don't expect crazy markdown like you are providing to parse cleanly. It can be a list item with lazy paragraph continuation with text just happens to have ###. It could be a heading in a list item or a list item with a heading

To see how different processors handle edge cases you can use Babelmark2 https://johnmacfarlane.net/babelmark2/?normalize=1&text=*+An+ATX+heading+follows+immediately+after+this+list.%0A%23%23%23+Testing+Issue+708%0Ais+parsed+by+Flexmark+and+it+generates+this+node+tree%3A%0A

I would say you need cleaner markdown input. Just any old stuff will not always parse as you think at first glance.

**Comment by ssikuro** [comment]
Thank you very much for explanation and introducing me this wonderful tool, babelmark2 !
After removing the use of ParserEmulationProfile.GITHUB_DOC,  the Heading node is a sibling of the BulletList node in the node tree.
