### ISSUE TITLE
List continuation

### ISSUE THREAD

**Issue by spoptchev** [vsch/flexmark-java#232]
Hello, is there a way to configure a formatter to insert a list continuation on a blank line when the previous list item is not blank?

```
* first item
* # continuation
```

```
* first item
* 
# no continuation
```

It would be even better if the empty list item is deleted once there is no continuation.

**Comment by vsch** [comment]
@spoptchev, what do you mean by list continuation?

Do you mean that an empty list item which is followed by a blank line should be deleted?

For example:

```markdown
* list item 1
*

* list item 2
* 
list item 3
```

would be formatted as:

```markdown
* list item 1
* list item 2
* list item 3
```

**Comment by spoptchev** [comment]
Lets say I want to build a markdown editor:

If the user is starting to write a markdown list and hits enter on a list item I want to be able to automatically insert a opening marker for the next line item. If the user hits enter on an empty list item I want to delete it.

As an example:

```
* list item
```

After the user hits enter after `list item` I want to add a new opening marker for the list. The result would be:

```
* list item
* 
```

If the user tabs enter again on the empty list item I want to have the original state:

```
* list item
```

**Comment by vsch** [comment]
@spoptchev, I have the behaviour you describe implemented in my plugin: enter on list item inserts a list item marker on the next line, if enter is hit on an empty item then the marker is deleted.

However, I am doing this by deleting the list item marker text in the editor without using formatter or the markdown AST. I am guessing you are using the formatter to achieve this effect.

I will take a look at the formatter. I think adding an option to delete empty list items would achieve this effect.

**Comment by spoptchev** [comment]
I can think of several hacks to achieve this functionality 😄 . But it would be perfect if it could be done with a formatter. Then I could separate formatting from syntax highlighting.

Is your plugin open source? 😄 Can you share your implementation?

**Comment by spoptchev** [comment]
I understand. Yes, its a completely different environment.

Can you point me in the right direction where I could extend the formatter to implement this kind of functionality?

**Comment by vsch** [comment]
@spoptchev, almost every extension implements a NodeFormatter, however the closest to list items is [TaskListNodeFormatter.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-gfm-tasklist/src/main/java/com/vladsch/flexmark/ext/gfm/tasklist/internal/TaskListNodeFormatter.java)

The formatter extensions use the same concept as the Renderer extensions of the main library except the context and interface is formatter specific.

The formatter code handling list items is found in the formatter module's core node formatter implementation: [CoreNodeFormatter.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-formatter/src/main/java/com/vladsch/flexmark/formatter/internal/CoreNodeFormatter.java#L611-L666)

**Comment by spoptchev** [comment]
Thank you, I will take a look at it

**Comment by vsch** [comment]
@spoptchev, new version released. 

* Fix: #232, List continuation, add `Formatter.LIST_REMOVE_EMPTY_ITEMS`, default `false`. If
  `true` then empty list items or list items which only contain a `BlankLine` node are removed
  from the output.
* Fix: formatter output of empty list items
* Fix: formatter output of empty loose task list items

**Comment by spoptchev** [comment]
Hello again, I know now that I need to use a NodePostProcessor to get the additional `* ` on the next line. And I got a partly working solution, but I do not understand how to add a completely new `BulletListItem` at the end of a `BulletList`. All the code examples from the other projects just create new items from existing parts of the AST.

As a very simple example I have in the `process` method of a `NodePostProcessor`:

```kotlin
val firstChild = node.firstChild as BulletListItem

if (firstChild.childChars.contains("\n") && !node.chars.contains("insert")) {
    val item = BulletListItem(CharSubSequence.of("${firstChild.chars}* insert", firstChild.endOffset))
    firstChild.insertAfter(item)
    state.nodeAdded(item)
}
```

When I execute the code the AST looks like this:

```
Document[0, 7]
                            BulletList[0, 7] isTight
                              BulletListItem[0, 7] open:[0, 1, "*"] isTight
                                Paragraph[2, 7]
                                  Text[2, 6] chars:[2, 6, "test"]
                              BulletListItem[7, 15] isTight
```

As you can see the last `BulletListItem` is not created like the `test` element. What do I have to do to create a new `BulletListItem` that is matching the AST from those of the list and has the correct line numbers and offsets?

**Comment by vsch** [comment]
@spoptchev, most node elements do not parse their text to set sub-sequences. This is done by the element parser since it already has this information.

Here is a sample code from the ListItemParser:

```java
        myBlock = myListData.isNumberedList ? new OrderedListItem() : new BulletListItem();
        myBlock.setOpeningMarker(myListData.listMarker);
        myBlock.setMarkerSuffix(myListData.markerSuffix);
```

The markerSuffix is used by the to do list item to set the `[ ]`. So you don't need to set it.

Also keep in mind that a ListBlockParser traverses all the list items and computes the isTight setting depending on parser settings and list items. This happens during parsing when the list block item is closed. When you are adding the list item the list block element has already resolved its child items. [ListBlockParser.java](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/internal/ListBlockParser.java#L153-L279)
