### ISSUE TITLE
Do LinkRefProcessors that "want exclamation prefix" have to check for '!' manually?

### ISSUE THREAD

**Issue by CorneliaXaos** [vsch/flexmark-java#238]
I was reviewing a lot of the code for flexmark as I'm planning on making an extension in a couple days. I went down the rabbit hole trying to figure out how to do custom prefixes with links "the right way." I know you can do it with a PostProcess.. but I wanted to do this proper. :P

Anyways, I was reviewing exactly how the parser decides to hand off code to a LinkRefProcessor for modification and discovered that if "getWantExclamationPrefix" returns true it collects the node chars for the link in the brackets + whatever character comes immediately before the opening bracket.  It then passes that to the LinkRefProcessor's "isMatch" function.

My question is two-fold:

1. Does the parser indeed not check that the leading character is a '!'? (Thus leaving it to the LinkRefProcessor to determine.)
2. Does this mean I could use it to check for an arbitrary prefix? (i.e. a '@' or '#' or whatever character I desire.)

If that's the case I know exactly how to proceed with my extension. (Examining the Wiki Link extension has been helpful.)

**Comment by CorneliaXaos** [comment]
I see now. I guess I will have to.go with the PostProcess route as I don't need to adjust the syntax.. yet.. still trying to figure out exactly what will be most useful and how much control should be necessary for users.

Thanks for getting back to me. I tried to add the Question label.. seems only contributors can do that. :P

**Comment by vsch** [comment]
@CorneliaXaos, as for adding options for control, it is much easier to get first implementation worked out without complicating it with options.

I tend to first implement a hard-coded version and once it is working and I have skeleton tests, then I add options using `DataKey` as part of the extension, with extension specific options class to make access easier than always going through `DataHolder` and `DataKey`.

You can see these classes in almost every extension module as `ModuleOptions` files where `Module` is replaced by the module name.

**Comment by CorneliaXaos** [comment]
I like to do TDD so I made just a husk of an extension class and then got a test suite up. I've been following the YouTube embedded link extension since it's doing very similar things to what I want.

What took me most of my time (today) was figuring out the AST syntax for using the ComboSpecTestCase. But I have tests now and if all goes well I could be done in, like, a week with something that passes all my tests. I'll make a PR around then.
