### ISSUE TITLE
ComboSpecTestCase output uses non-breaking spaces instead of regular spaces

### ISSUE THREAD

**Issue by CorneliaXaos** [vsch/flexmark-java#240]
I was wondering what was going on with my comparison test cases and why they were having issues with the header for the test case, i.e. the:

```
```````````````````````````````` example Media Tags audio link transformer: 3
< test case here >
```

And here is the output header that it says is not equal to my defined test case header:
```
```````````````````````````````` example Media Tags audio link transformer: 3
< test case here >
```

After doing a bit of looking around and analyzing the character codes for the white-space I discovered that my spec files had actual spaces in the header while the spec tests were outputting "character 160" or the non-breaking space character.

This makes writing the test cases by hand a little difficult as I now need to replace all the spaces in that title string with non-breaking spaces instead.  It seems it's only outputting those in the title string for an example and not any of the example body or anywhere else.

I'm not sure if this is intentional (I can kinda see why it might be knowing how markdown could get converted), but it does make writing test cases annoying since I have to put non-breaking spaces in there myself as the comparison results in a failure otherwise.

**Comment by vsch** [comment]
@CorneliaXaos, there was a reason spaces in the lead-in are converted to `&nbsp;`, I cannot remember it off the top of my head but spaces caused parsing conflicts. 

Since I generate these automatically in IntelliJ IDEA using my plugin I never thought about it from manual creation.

Additionally, using IDEA test difference feature allows copying of the actual output to the file using the IDE compare to clipboard. So my use case for new tests is usually write the tests, get them working, then copy the actual to the test cases so that all test examples are updated.

The plugin also understands flexmark-java test case files while formatting and will fix example numbers, headings, options, etc, while formatting document. This too made me not realize it would cause difficulties if creating these without assistance.

What IDE are you using for development?

**Comment by vsch** [comment]
@CorneliaXaos, additionally some characters are used to visually represent tab and carriage return visually and will be converted to/from these.

`⏎`(`\u23ce`) in input will be converted to `\r` and vice versa for output to make it visually identifiable.

same for `→` (`\u2192`), it is converted to `\t` and vice versa

`⎮` (`\u23ae`) is converted to `\u1f`

**Comment by vsch** [comment]
@CorneliaXaos, if you go to https://vladsch.com/product/markdown-navigator/try and get a trial license for Markdown Navigator, I will upgrade it to developer status, which I am using. It will add flexmark-java specific functionality for test example files and test classes. Some of the functionality is less than polished but works well enough to make life much easier.

It will give you preview of test files with  the three sections, add completions, validation and navigation  for test example options and formatting of test example files. All these make working with tests much easier.

Options can be defined in java test classes and selected for individual test examples using the `options(optionName1,...)` syntax. This allows testing with specific option settings. Useful when you add data keys to modify your extension operation.

If you use the IDEA test functionality then you will get a diff link in the test console for failed tests that you can use to compare/copy actuals.

This will make creating test cases and maintaining them much more comfortable than Java coded tests.

**Comment by CorneliaXaos** [comment]
Oh that's neat.. I've just been reverse engineering the spec test file formats by looking at other tests.  I've actually gotten them updated just now and am reviewing them a bit before I move on to adding DataKey options and such.

I would go ahead and get the trial license for you to upgrade.. but I don't think I have much work remaining for this extension.  And the next thing I was considering doing (an output variant for outputting bbcode) I might not get to for a long time so I don't want to take advantage of your hospitality and get a free license for something I might not use too much in the next year.

**Comment by vsch** [comment]
@CorneliaXaos, the plugin's main function is markdown support for JetBrains IDEs. If you use markdown for documentation, especially for GitHub projects, then you will find it useful.

It adds formatting, completions, refactoring, navigation and more. It makes markdown have the same functionality in the IDE as other languages and provides a preview pretty close to what it will look on GitHub.

It is not a big deal to provide you with a license. Who knows, you might find it useful.

**Comment by CorneliaXaos** [comment]
Alright.  I sent in a request for the trial license.

Also, since it seems the non-breaking spaces are intentional, I'll close this issue.
