### ISSUE TITLE
Request to add CSS class of TOC

### ISSUE THREAD

**Issue by yososs** [vsch/flexmark-java#248]
In TOCExtension(or SimTocExtension), the option that CSS class can be specified for visual adjustment is desirable.

input markdown:

``` markdown
[TOC]
# Heading 1

## Heading 2

### Heading 2-1
```

output html:
``` html
<div class="toc">
<ul>
<li><a href="#heading-2">Heading 2</a>
<ul>
<li><a href="#heading-2-1">Heading 2-1</a></li>
</ul>
</li>
</ul>
</div>
<h1 id="heading-1">Heading 1</h1>
<h2 id="heading-2">Heading 2</h2>
<h3 id="heading-2-1">Heading 2-1</h3>

```

**Comment by vsch** [comment]
@yososs, next version adds options.

* Add: `TocExtension.TOC_CONTENT`, `TocExtension.TOC_LIST`, `SimTocExtension.TOC_CONTENT`,  `SimTocExtension.TOC_LIST` attributable parts for `div` and `ul`/`ol` HTML tags. Documented in  [Table-of-Contents-Extension](../../wiki/Table-of-Contents-Extension) 
  * Fix: `TOC` element to use `TITLE` option if one is defined. Default for `TOC` is `""`, for    sim `TOC` it is `"Table of Contents"`
* Add: `TocExtension.DIV_CLASS` default `""`, class attribute to use on table of content `div` wrapper, duplicated as `SimTocExtension.DIV_CLASS`
* Add: `TocExtension.LIST_CLASS` default `""`, class attribute to use on table of content `ul`  or `ol` element, duplicated as `SimTocExtension.LIST_CLASS`

**Comment by vsch** [comment]
@yososs, repo updated. Maven central update in progress

**Comment by arctrong** [comment]
This doesn't work. The table of context is not wrapped into a div block.
