### ISSUE TITLE
Subscript, superscript, and struck text

### ISSUE THREAD

**Issue by DaveJarvis** [vsch/flexmark-java#25]
Some markdown flavours support subscripts, superscripts, and struck text:

    October 31^st^
    H~2~O
    ~~Commonmark~~ Flexmark is amazing.

Flexmark extensions for these would be useful.

**Comment by vsch** [comment]
@DaveJarvis, the struck text is available now in GitHub format: `~~strikeout~~` ~~strikeout~~ in the `flexmark-ext-gfm-strikethrough` extension.

Which processor has superscript with `^`, subscript with `-` and strikeout with `--`?

**Comment by vmassol** [comment]
Hi, I'm also very interested in having support for subscript and superscript using the following syntax (sine this is what XWiki is already supporting with an extension to pegdown, see https://github.com/xwiki-contrib/syntax-markdown/blob/master/syntax-markdown-markdown11/src/main/java/org/xwiki/contrib/rendering/markdown11/internal/parser/FormattingPegdownPluginParser.java ):

`````
This is ~subscript~
This is ^superscript^
`````

Right now I'm trying to add custom support for this but I find it quite complicated so far, with lots of code to write (I'm looking at the abbreviation extension as an example). I still need to read and understand https://github.com/vsch/flexmark-java/wiki/Writing-Extensions (but there's a lot of reading ;)). A simple example would be nice, maybe it exists somewhere?

Thanks (and merry christmas! :))

BTW: Is there a mailing list/forum somehere for flexmark-java? (should I open an issue whenever I have a question?). Thanks

**Comment by vmassol** [comment]
PS: I don't recall from where we found this MD syntax.

**Comment by vmassol** [comment]
Basically I'll need to provide support for the following (macros, super/subscript, inline xhtml): http://extensions.xwiki.org/xwiki/bin/view/Extension/Markdown+Syntaxes/#HExtraFeatures

This is what we were supporting when using pegdown so I'll need to migrate this to flexmark-java somehow.

**Comment by vmassol** [comment]
> Right now I'm trying to add custom support for this but I find it quite complicated so far, with lots of code to write (I'm looking at the abbreviation extension as an example). I still need to read and understand https://github.com/vsch/flexmark-java/wiki/Writing-Extensions (but there's a lot of reading ;)). A simple example would be nice, maybe it exists somewhere?

Actually seems the strikethrough extension is a better and simpler example than the abbreviation one!

**Comment by vsch** [comment]
@vmassol, the ~subscript~ and ^superscript^ makes more sense than -subscript- since - is used everywhere in regular text.

I will add these since I was interested in adding sub/super script but did not get around to finding syntax that makes sense.

For these extensions, both have to be added as Delimiters. The subscript will need to be merged with gfm-strikethrough since both use ~ and it will resemble bold/italic type of processing, the superscript will be new since the ^ char is not used.

The distinction between various types of processors in CommonMark architecture is very pronounced. Adding the extension in just the right place can make the difference of a dozen lines with some boiler plate and over a hundred lines with a lot of if/else and state information hanging around.

See how emphasis is implemented and you will understand what I mean: https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/internal/inline/EmphasisDelimiterProcessor.java#L52-L53

The gfm/subscript will literally be a copy with the above two lines changed to reflect the different AST nodes to be used. 

The tests in flexmark module are a good source of "how to" examples since they use the API in the tests. The one for delimiters is https://github.com/vsch/flexmark-java/blob/master/flexmark/src/test/java/com/vladsch/flexmark/test/DelimiterProcessorTest.java#L109-L227 and in 100 lines, boiler plate included, has a full implementation of custom delimiter for { } that renders contained text as uppercase.

**Comment by vsch** [comment]
@vmassol, the wiki has a page on writing extensions https://github.com/vsch/flexmark-java/wiki/Writing-Extensions with a picture of the high level process: ![img](https://raw.githubusercontent.com/vsch/flexmark-java/master/assets/images/flexmark-parsing.png) that might help get a bird's eye view.

**Comment by vmassol** [comment]
Thanks @vsch for the explanations and pointers. Cool that you're planning to add support for sub/superscript!

I've just tried using `StrikethroughExtension` and for some reason it's not working for me. Is it supposed to work? By not working, I mean that my `visit(Strikethrough node)`method is not called, even though I've added it as a handler:

`````
        // Handle strikethrough nodes
        StrikethroughNodeVisitor strikethroughNodeVisitor =
            new StrikethroughNodeVisitor(this.visitor, this.listeners);
        this.visitor.addHandlers(
            new VisitHandler<>(Strikethrough.class, strikethroughNodeVisitor::visit)
        );
``````

any idea? Thanks

**Comment by vsch** [comment]
Can you please post the options that you use for the parser and renderer?

**Comment by vmassol** [comment]
I only use a parser (and no renderer):

````
...
    private static final List<Class> DEFAULT_EXTENSIONS = Arrays.asList(
        WikiLinkExtension.class,
        AutolinkExtension.class,
        DefinitionExtension.class,
        TablesExtension.class,
        StrikethroughExtension.class
    );
...

            // Configure options
            MutableDataHolder options = new MutableDataSet();
            options.setFrom(this.configuration.getEmulationFamily().getOptions());

            // Configure extensions
            List<Extension> extensions = new ArrayList<>();
            for (Class extensionClass : this.configuration.getExtensionClasses()) {
                Method method = extensionClass.getMethod("create");
                Extension extension = (Extension) method.invoke(null);
                extensions.add(extension);
            }

            Parser parser = Parser.builder(options).extensions(extensions).build();
            document = parser.parse(IOUtils.toString(source));
...
`````

And `this.configuration.getExtensionClasses()`returns `DEFAULT_EXTENSIONS`.

**Comment by vsch** [comment]
You are not setting the Parser.EXTENSIONS key in your options to the list of extensions but adding it after in builder. Could be a bug in the code, try setting the `option.set(Parser.EXTENSIONS,extensions)`  then just `Parser.builder(options).build()`.

I really should get rid of the old methods in builders that come from commonmark-java. They are not needed since options contain everything without distinction.

**Comment by vmassol** [comment]
I now have:

````
            // Configure options
            MutableDataHolder options = new MutableDataSet();
            options.setFrom(this.configuration.getEmulationFamily().getOptions());

            // Configure extensions
            List<Extension> extensions = new ArrayList<>();
            for (Class extensionClass : this.configuration.getExtensionClasses()) {
                Method method = extensionClass.getMethod("create");
                Extension extension = (Extension) method.invoke(null);
                extensions.add(extension);
            }
            options.set(Parser.EXTENSIONS, extensions);

            Parser parser = Parser.builder(options).build();
            document = parser.parse(IOUtils.toString(source));
````

The problem is fixed, it wasn't a problem on flexmark)java's side. I had some issue with my IDE which wasn't using the correct config class. It's working fine now. Thanks for your help.

**Comment by vsch** [comment]
@vmassol, I will let you know as soon as I have the sub/super script extension ready.

Also noticed that Maven is stuck at 0.7.0 but I updated it to 0.8.0 a few days ago. Nexus was having glitches that day maybe it failed to release to maven even though it claimed to do so.

**Comment by vmassol** [comment]
Thanks. I assume you're using sonatype's nexus to sync with Maven Central. I don't see any open staging repo at https://oss.sonatype.org/#stagingRepositories. Maybe you should try again?

**Comment by vsch** [comment]
Yes, sonatype's nexus with sync to maven. 

I will do it again. I had a staging repo that I released and was notified it might take a few hours, always does. However, it has been a few days.

I'll wait to have the 0.9.0 release. 0.8.0 had just the Java 7 downgrade. 0.9.0 has API changes and major cleanup. Trying to get the API in utilities as clean as possible so I won't have to do it later.

**Comment by DaveJarvis** [comment]
@vsch:

> Which processor has superscript with ^, subscript with - and strikeout with --?

I don't know of any processors that use hyphens and double-dashes in that way. The [original request](https://github.com/vsch/flexmark-java/issues/25#issue-197447594) suggested tildes (`~`) as delimiters, as per Pandoc's usage.

**Comment by vsch** [comment]
@DaveJarvis, my bad. I have zoom set to 90% on my browser to be able to the zillion tabs and saw dashed instead of tildes. These will be added shortly. I am in the middle of a big cleanup but it is almost done. Next release will be with these added.

**Comment by vsch** [comment]
@DaveJarvis, @vmassol, repo updated 0.9.0, Maven released.

Subscript part of flexmark-ext-gfm-strikethrough, which has 3 extensions strikethrough, subscript and strikethrough & subscript.

Added superscript and ins extensions:

<img width="621" alt="screen shot 2016-12-24 at 11 58 35 pm" src="https://cloud.githubusercontent.com/assets/10299086/21469784/12e1782e-ca35-11e6-83ed-b36528123514.png">
<img width="622" alt="screen shot 2016-12-24 at 11 59 11 pm" src="https://cloud.githubusercontent.com/assets/10299086/21469785/15369c80-ca35-11e6-9b52-136e69305c36.png">
<img width="623" alt="screen shot 2016-12-24 at 11 59 38 pm" src="https://cloud.githubusercontent.com/assets/10299086/21469786/179e3974-ca35-11e6-9c7b-852f155190d6.png">

**Comment by vsch** [comment]
```markdown
Just thought I'd try the new extensions in my pluigin with copy Markdown as HTML to clipboard.
H~2~O and X^2^ - 4X = (X - 2)(X + 2)
```

```html
<p style="margin:0 0 1.2em;">Just thought I'd try the new extensions in my pluigin with copy Markdown as HTML to clipboard.
H<sub>2</sub>O and X<sup>2</sup> - 4X = (X - 2)(X + 2)</p>
```

Neat. Can use it with GitHub comments for all extensions that GitHub does not support.

<p style="margin:0 0 1.2em;">Just thought I'd try the new extensions in my pluigin with copy Markdown as HTML to clipboard.
H<sub>2</sub>O and X<sup>2</sup> - 4X = (X - 2)(X + 2)</p>

**Comment by vmassol** [comment]
Thanks @vsch fpr the christmas present! :) I'll try it later today!

**Comment by vmassol** [comment]
Ok I've just tested it by adding the 2 new extensions (SubscriptExtension and SuperscriptExtension) but all my tests are now failing with:

````
Caused by: java.lang.IllegalArgumentException: Delimiter processor conflict with delimiter char '~'
	at com.vladsch.flexmark.internal.InlineParserImpl.addDelimiterProcessorForChar(InlineParserImpl.java:224)
	at com.vladsch.flexmark.internal.InlineParserImpl.addDelimiterProcessors(InlineParserImpl.java:213)
	at com.vladsch.flexmark.internal.InlineParserImpl.calculateDelimiterProcessors(InlineParserImpl.java:153)
	at com.vladsch.flexmark.parser.Parser.<init>(Parser.java:163)
	at com.vladsch.flexmark.parser.Parser.<init>(Parser.java:38)
	at com.vladsch.flexmark.parser.Parser$Builder.build(Parser.java:291)
	at org.xwiki.contrib.rendering.markdown.markdown12.internal.parser.AbstractMarkdownStreamParser.parse(AbstractMarkdownStreamParser.java:79)
````

**Comment by vsch** [comment]
@vmassol, you can only have one of the extensions from flexmark-ext-gfm-strikethrough because they all try to claim a `~` as their delimiter. That is why there are 3: strikethrough & subscript, strikethrough only and subscript only.

Replace your extension list with:

````
    private static final List<Class> DEFAULT_EXTENSIONS = Arrays.asList(
        WikiLinkExtension.class,
        AutolinkExtension.class,
        DefinitionExtension.class,
        TablesExtension.class,
        StrikethroughSubscriptExtension.class,
        SuperscriptExtension.class
    );
````

**Comment by vmassol** [comment]
Ah I missed that, sorry. Thanks, it works.

**Comment by vsch** [comment]
@vmassol, not a problem. I will add more informative error messages because this is bound to come up more often as time goes on.

**Comment by DaveJarvis** [comment]
Works as designed.
