### ISSUE TITLE
Embedded Image (max) scaling

### ISSUE THREAD

**Issue by Grestorn** [vsch/flexmark-java#250]
Hi,

I've just integrated flexmark on our site, and I'm very happy with it. 

I'd need a way to control the scaling of inline images. For one, I want to set the maximum dimension as an option and I'd also like to allow the user to specify the dimensions (within that limit) himself. 
Is this a planned feature? Or is this already possible somehow and I missed it? Would this something to implement in the core or would you have to create an extension for this (even though it's an extension of a standard Markdown element)?

**Comment by vsch** [comment]
@Grestorn, you need to implement a custom attribute provider. See: [AttributeProviderSample2.java] 

You can use the same provider to add/remove/change attributes for any node being rendered. 

To allow attributes to be modified in markdown you can enable the AttributesExtension which adds ability to add any HTML attribute to any element. See: [Extensions](https://github.com/vsch/flexmark-java/wiki/Extensions#attributes), described in [Attributes-Extension](https://github.com/vsch/flexmark-java/wiki/Attributes-Extension)

However, to implement limiting the user provided attribute within the default maximum dimension will require to create a custom node renderer which will examine the actual size attribute to the default maximum and change it if it exceeds the maximum. For an example of a custom renderer see  [NodeRendererSample.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/NodeRendererSample.java)

[AttributeProviderSample2.java]: https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/AttributeProviderSample2.java#L36-L57

**Comment by Grestorn** [comment]
Thanks for those pointers, I'm going to look them up!
