### ISSUE TITLE
GfmUser and GfmIssue are not recognized if immediately followed by non-space character

### ISSUE THREAD

**Issue by mstrap** [vsch/flexmark-java#252]
For below example, GitHub will recognize "world" as mention and "#1" as issue link, however Flexmark-Java does not:

	public static void main(String[] args) {
		final MutableDataHolder options = new MutableDataSet()
		            .set(Parser.EXTENSIONS, Arrays.asList(StrikethroughExtension.create(), GfmUsersExtension.create(), GfmIssuesExtension.create(), AutolinkExtension.create()));
		final Parser parser = Parser.builder(options).build();
		final Document document = parser.parse("Hello, @world, and #1!");
		new NodeVisitor(Collections.emptyList()) {
			@Override
			public void visit(Node node) {
				System.out.println("Node: " + node);
				super.visit(node);
			}
		}.visit(document);
	}

**Comment by vsch** [comment]
@mstrap, you are right. The regex is too restrictive and expects whitespace after the issue or user.

I changed it to be `\\b` just a word break and making a release with the fix.

**Comment by mstrap** [comment]
Thanks, version 0.34.14 is working fine now!
