### ISSUE TITLE
custom rules for parsing *** with '('

### ISSUE THREAD

**Issue by cpuheater** [vsch/flexmark-java#253]
I would like to have custom parsing rule which enables me to parse the following text "**\*\(\*\)" without escaping but at the same time I want to use '*' as indicators of emphasis. Would would be the base way to implement it ?

**Comment by vsch** [comment]
@cpuheater, for multi-character inline parsing the best example is probably the `flexmark-ext-attributes` extension: [AttributeParsing.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-attributes/src/main/java/com/vladsch/flexmark/ext/attributes/internal/AttributeParsing.java)

For using other emphasis characters you can take a look at the core asterisk processing [AsteriskDelimiterProcessor.java](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/internal/inline/AsteriskDelimiterProcessor.java) and [EmphasisDelimiterProcessor.java](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/internal/inline/EmphasisDelimiterProcessor.java) or at `flexmark-ext-gfm-strikethrough` extension: [StrikethroughDelimiterProcessor.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-gfm-strikethrough/src/main/java/com/vladsch/flexmark/ext/gfm/strikethrough/internal/StrikethroughDelimiterProcessor.java)

**Comment by oleksiypr** [comment]
What is the example of `AsteriskDelimiterProcessor` usage? How can I use it for my `Parser` and `HtmlRenderer`?

**Comment by vsch** [comment]
@oleksiypr, the asterisk delimiter processor is part of the core delimiter processors and are used for `*` processing and you do not need to add them to your code. Delimiter processing is handled by the core inline processor. Registering them in your extension is how they are used.

If you want to implement your own delimiter processor then the most complete examples are in the `flexmark-ext-gfm-strikethrough` module which implements several delimiters with various constraints.
