### ISSUE TITLE
Convert results to byte array insted of saving it to zip file

### ISSUE THREAD

**Issue by sirishayalavarthi** [vsch/flexmark-java#255]
Markdown to docx conversion, Can I change docx file contents to byte array instead of saving it to ZIP file

**Comment by vsch** [comment]
@sirishayalavarthi, flexmark uses docx4j library. The save method on the WordprocessingMLPackage has a save method that takes an output steam, so you can pass a ByteOutputStream and get a byte array from it.

See the test case implementation extracting XML for the docx from the byte output stream. [ComboDocxConverterIssuesSpecTest.java: Lines 146-185](https://github.com/vsch/flexmark-java/blob/master/flexmark-docx-converter/src/test/java/com/vladsch/flexmark/docx/converter/ComboDocxConverterIssuesSpecTest.java#L146-L185)

**Comment by sirishayalavarthi** [comment]
thank you.
