### ISSUE TITLE
Does flex mark supports base64image url in docx

### ISSUE THREAD

**Issue by sirishayalavarthi** [vsch/flexmark-java#257]
Does flex mark supports base64image URL in docx, like bar charts, pie charts with base64image url

**Comment by vsch** [comment]
@sirishayalavarthi, currently swing ImageIcon is created with URL() which I don't think supports base64 image urls.

I will add this to docx renderer

**Comment by anujkrai** [comment]
yes

**Comment by vsch** [comment]
This has been added #397 thanks to @Xaelis
