### ISSUE TITLE
Parser.SPACE_IN_LINK_URLS not working as expected

### ISSUE THREAD

**Issue by timokau** [vsch/flexmark-java#269]
flexmark-java is used in https://github.com/gsantner/markor. I'm trying to use that project to read vimwiki files, which use links with spaces in them: `[some file](some file.md)`. I've tried adding support to that to markor by adding the `SPACE_IN_LIN_URLS` option, but it did not have the intended effect. Am I misunderstanding that option?

Relevant markor issue: https://github.com/gsantner/markor/issues/317

**Comment by vsch** [comment]
@timokau, I added a test for this setting and it seems to work. The `url-space` option in the test sets option `MutableDataSet().set(Parser.SPACE_IN_LINK_URLS, true)`

```````````````````````````````` example(Space in URL: 1) options(url-space)
[some file](some file.md)
.
<p><a href="some%20file.md">some file</a></p>
.
Document[0, 25]
  Paragraph[0, 25]
    Link[0, 25] textOpen:[0, 1, "["] text:[1, 10, "some file"] textClose:[10, 11, "]"] linkOpen:[11, 12, "("] url:[12, 24, "some file.md"] pageRef:[12, 24, "some file.md"] linkClose:[24, 25, ")"]
      Text[1, 10] chars:[1, 10, "some file"]
````````````````````````````````

As you can see above it does allow spaces to be in link urls and generates the correct HTML and AST.

ℹ️ options used for parsing the document should have this option set to true to change the valid URL characters.

Can you give more details of the use case which is not working for you?

**Comment by gsantner** [comment]
@vsch   
I can't confirm that it works, seems still broken in the latest release.

Test code:
```
        MutableDataSet options = new MutableDataSet();
        options.set(Parser.SPACE_IN_LINK_URLS, true);
        Parser p = Parser.builder(options).build();
        HtmlRenderer r = HtmlRenderer.builder(options).build();
        String converted = r.render(p.parse("hello\nworld [text](some uri.md) world\nhello"));
        converted = r.render(p.parse("hello\nworld ![text](some uri.jpg) world\nhello"));
        converted = r.render(p.parse("hello\nworld ![link](/my uri) world\nhello"));
        converted = r.render(p.parse("hello\nworld [link](</my uri>) world\nhello"));
```

And none of these, with or without the additional SPACE_IN_LINK_URLS option render as expected - with `%20` for spaces.  
Beside expectation, this also makes it Commonmark incompatible - the last demo call above does not result to the expected `%20` spaced rendering as shown in [Commonmark Example 486](https://spec.commonmark.org/0.29/#example-486).

![grafik](https://user-images.githubusercontent.com/6735650/142716452-a01e245b-1d39-4a67-8199-83d59dc3deb3.png)

```
with SPACE_IN_LINK_URLS
<a href="/my uri">link</a>

without it
[link](&lt;/my uri&gt;)

Should be, either way:
<a href="/my%20uri">link</a>
```

See video for some examples:

https://user-images.githubusercontent.com/6735650/142716567-548e7bd5-88c8-4264-be0e-2e7de10f05b1.mp4

I tried with the latest release v0.62.2 and with v0.42.14 (the last Java7 release).

Can you please reopen and fix the issue?
