### ISSUE TITLE
Abbreviation node not called when 2 abbreviations

### ISSUE THREAD

**Issue by vmassol** [vsch/flexmark-java#27]
Hi, I'm now adding support for MD abbreviations.

I have added the AbbreviationExtension and registered a handler:

````
        AbbreviationNodeVisitor abbreviationNodeVisitor = new AbbreviationNodeVisitor(this.visitor, this.listeners);
        this.visitor.addHandlers(
            new VisitHandler<>(Abbreviation.class, abbreviationNodeVisitor::visit)
        );
````

And  in my `visit` method:

````
    public void visit(Abbreviation node)
    {
        // Since XWiki doesn't support abbreviations, we generate an HTML <abbr> element.
        String html;
        if (StringUtils.isNotEmpty(node.getAbbreviation())) {
            html = String.format("<abbr title=\"%s\">%s</abbr>", node.getAbbreviation(),
                String.valueOf(node.getChars()));
        } else {
            html = String.format("<abbr>%s</abbr>", String.valueOf(node.getChars()));
        }
        getListener().onRawText(html, Syntax.HTML_4_01);
    }
````

The problem comes from the following input:

````
The HTML specification is maintained by the W3C.

*[HTML]: Hyper Text Markup Language
*[W3C]:  World Wide Web Consortium
````

In my case I get only 1 call for my `visit(Abbreviation node)`method instead of the 2 I was expecting.

In other words, I don't get a call for the `W3C`abbreviation.

Any idea?

Thanks again!

**Comment by vmassol** [comment]
ok I know why.

with the following input it works fine:

````
The HTML specification is maintained by the W3C.

*[HTML]: Hyper Text Markup Language
*[W3C]:  World Wide Web Consortium

````

So the issue is the newline. With pegdown it was working without a trailing newline. Could you confirm if the currently implemented behavior is correct (i.e. to not consider an abbreviation definition if it's not ending with a newline even if if that last line of the input?

Thanks

**Comment by vsch** [comment]
@vmassol, it should accept the abbreviation definition without a trailing EOL at the end of the file. If it does not then it is a bug. I will add a test and fix it.

**Comment by vsch** [comment]
@vmassol, confirmed and fixed. Are you using maven or this repo for your project. If its maven I will do a release, otherwise I will just update the repo and wait for more fixes before making an official release.

**Comment by vmassol** [comment]
cool. Yes I'm using Maven. I can wait a few days if you don't want to release a new version now.

**Comment by vsch** [comment]
@vmassol, maven released. Not a problem to release it. If you were not using it then there would be no point in making a release.

Thank you for catching this one. All previous tests were done with an EOL at the end of the file. I will modify the testing to make No trailing EOL the default for all tests.
