### ISSUE TITLE
Customize WikiLinkLinkResolver

### ISSUE THREAD

**Issue by rshah** [vsch/flexmark-java#272]
I'm trying from generate url for wiki links syntax but the final url will be different based on the pattern of the link.
For example:

> [[TASK-1]] will be rendered as http://mysite.com/task/1
> [[My document page]] will be rendered as http://mysite.com/doc/My-document-page

I tried following `PegdownCustomLinkResolverOptions` example, but seems `CustomLinkResolver.resolveLink` is never called. The link always resolved by `WikiLinkLinkResolver`. 
`CustomLinkResolver.resolveLink` will be called only when i put this link syntax: **[link]**
I also set this for the base url for the final url `WikiLinkExtension.LINK_PREFIX`

Do you have any idea why CustomLinkResolver not called for wiki link?

**Comment by qwazer** [comment]
@rshah , maybe you forgot to register it in you Custom Extension?
https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/CustomLinkResolverSample.java#L163

**Comment by rshah** [comment]
> @rshah , maybe you forgot to register it in you Custom Extension?
> https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/CustomLinkResolverSample.java#L163

I did.  Maybe it's wrong to use `WikiLinkExtension` and `CustomExtension` (which i copied from `PegdownCustomLinkResolverOptions`) at the same time. 

`options.set(Parser.EXTENSIONS,
                Arrays.asList( WikiLinkExtension.create(), CustomExtension.create())
)`

Based on this i assume it's possible to use both extensions at the same time.
`PegdownOptionsAdapter.flexmarkOptions(Extensions.ALL, CustomExtension.create());` 
Also because of `CustomLinkResolver.resolveLink` has this checking:
`if (node instanceof WikiLink)` 
I thought it will be called somewhere.

I might not understand the sample properly.

**Comment by vsch** [comment]
@rshah, the order of extensions is significant for node renders. The first extension gets first dibs on rendering the node, it can delegate rendering to previous renderer via `context.delegateRender()` if it does not want to handle rendering.

Similarly, the first link resolver in the list which reports success will be used. So having the wiki link extension in the list first will cause its resolver to be used.

In your case you are putting the `WikiLinkExtension` first, whereas `PegdownOptionsAdapter` adds all custom extensions before adding any of the standard extensions.

Change the order of your extensions and your code will be called to resolve the links.

**Comment by rshah** [comment]
Thank you for your explanation.
I changed the order and it works great.
