### ISSUE TITLE
Java 11 module path conflicting package

### ISSUE THREAD

**Issue by Crazy-Duck** [vsch/flexmark-java#273]
When using flexmark as a dependency in a JDK11 project, I'm running into problems when using the MutableDataHolder, ... from the flexmark-util package. I'm unable to put both `require flexmark;` and `require flexmark.util;` in my module-info since both of those seem to expose the same `com.vladsch.flexmark` package, which is not allowed... Am I using the library wrong or is there no support yet for java 9+?

**Comment by vsch** [comment]
@Crazy-Duck, I have not tried it with Java 9+. I will create a project with Java 9 and try to resolve the issues.

**Comment by vsch** [comment]
@Crazy-Duck, from what I have read about java modules, it requires that all dependencies be modularized or it does not work. Jars which are not modularized should be included on the class-path not the module path.

flexmark-java is not modularized and has the same package used in both flexmark and flexmark-util. The latter will need to be moved to its own package. The same for other extenstions if they have duplicate packages.

**Comment by Crazy-Duck** [comment]
The issue is that modules cannot read jars on the classpath so as to prevent them from depending on "the chaos of the classpath". So if you want to modularize an application, all of its dependencies need to be put on the module path, even its non-modular ones, which automatically get turned into automatic modules. So this basically puts me into a bind. Flexmark cannot be turned into an automatic module since it has overlapping packages, which in turn means I cannot modularize my application who depends on it... The only possibility I have at the moment is leaving the application as a classpath application and compile it as such under Java 11. Given the deprecation of Java 8 in January, is modularizing this library something that is on the roadmap?

**Comment by vsch** [comment]
@Crazy-Duck, from what I read modules replace one hell with another one. There is not wide support in libraries for module, yet and I suspect that it will be that way for quite a long time.

To add to the mess there is not easy way to create a library that is both Java 8 and Java 9 compatible and not all build tools support modules seamlessly.

I will be looking into it over the next while. Java 8 is not going away for a long time. Just like Java 6 stuck around for a very long time. Oracle is not supporting Java 8 but Open JDK will be supported because of its wide use.

My suspicion is that it will be a while before Java modules will be widely adopted. In my experience no one has come up with a solution to the dependency problem. They only managed to replace one set of problems with another. The modules seem to be just another incarnation of an attempt at solving the problem. The real issue stems from dependencies on different versions of the same library and nothing will ever resolve this transparently or universally.

**Comment by Crazy-Duck** [comment]
I agree that the module system is just another stab at handling dependency management, although I do think the enhanced support for encapsulation and the explicit listing of dependencies is a nice improvement. However I disagree that there is no way to make a library both Java 8 and Java 9 compatible. The automatic module system exists for this exact purpose, the only requirement being that there be no conflicting packages. In short the main thing that would be needed to make the library Java 9+ compatible would just be resolving the package name conflicts, there's no need to make it fully modular yet.

**Comment by bahrigencsoy** [comment]
We are also badly hurt with this issue.

This is our class:

```java
import com.vladsch.flexmark.ast.Node;
import com.vladsch.flexmark.ext.autolink.AutolinkExtension;
import com.vladsch.flexmark.ext.gfm.issues.GfmIssuesExtension;
import com.vladsch.flexmark.ext.gfm.strikethrough.StrikethroughExtension;
import com.vladsch.flexmark.ext.gfm.users.GfmUsersExtension;
import com.vladsch.flexmark.ext.ins.InsExtension;
import com.vladsch.flexmark.ext.tables.TablesExtension;
import com.vladsch.flexmark.html.HtmlRenderer;
import com.vladsch.flexmark.parser.Parser;
import com.vladsch.flexmark.util.options.MutableDataSet;

public class OurClass{}
```

And module-info
```java
module ourproject {
    requires flexmark.util;
    requires flexmark.ext.autolink;
    requires flexmark.ext.gfm.issues;
    requires flexmark.ext.gfm.strikethrough;
    requires flexmark.ext.gfm.users;
    requires flexmark.ext.ins;
    requires flexmark.ext.tables;
    // requires flexmark; // FIXME split package
}
```

The last commented auto-module is problematic, if we uncomment that line, we get these kind of exceptions (clipped):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project atar: Compilation failure: Compilation failure:
[ERROR] error: the unnamed module reads package com.vladsch.flexmark from both flexmark and flexmark.util
[ERROR] error: the unnamed module reads package com.vladsch.flexmark.ast from both flexmark and flexmark.util
[ERROR] error: module flexmark reads package com.vladsch.flexmark from both flexmark and flexmark.util
[ERROR] error: module flexmark reads package com.vladsch.flexmark.ast from both flexmark and flexmark.util
[ERROR] error: module flexmark.ext.tables reads package com.vladsch.flexmark from both flexmark and flexmark.util
[ERROR] error: module flexmark.ext.tables reads package com.vladsch.flexmark.ast from both flexmark and flexmark.util
[ERROR] error: module flexmark.ext.ins reads package com.vladsch.flexmark from both flexmark and flexmark.util
[ERROR] error: module flexmark.ext.ins reads package com.vladsch.flexmark.ast from both flexmark and flexmark.util
[ERROR] error: module flexmark.ext.gfm.users reads package com.vladsch.flexmark from both flexmark and flexmark.util
[ERROR] error: module flexmark.ext.gfm.users reads package com.vladsch.flexmark.ast from both flexmark and flexmark.util
[ERROR] error: module flexmark.ext.gfm.strikethrough reads package com.vladsch.flexmark from both flexmark and flexmark.util
[ERROR] error: module flexmark.ext.gfm.strikethrough reads package com.vladsch.flexmark.ast from both flexmark and flexmark.util
[ERROR] error: module flexmark.ext.gfm.issues reads package com.vladsch.flexmark from both flexmark and flexmark.util
[ERROR] error: module flexmark.ext.gfm.issues reads package com.vladsch.flexmark.ast from both flexmark and flexmark.util
[ERROR] error: module flexmark.ext.autolink reads package com.vladsch.flexmark from both flexmark and flexmark.util
[ERROR] error: module flexmark.ext.autolink reads package com.vladsch.flexmark.ast from both flexmark and flexmark.util
[ERROR] error: module flexmark.util reads package com.vladsch.flexmark from both flexmark and flexmark.util
[ERROR] error: module flexmark.util reads package com.vladsch.flexmark.ast from both flexmark and flexmark.util
....
[ERROR] error: module commons.net reads package com.vladsch.flexmark from both flexmark and flexmark.util
....
```

The error is clear, two unnamed modules, flexmark.util & flexmark, has the same package.

We tried to patch the module during compilation, but was not successful:

```xml
                    <plugin>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>3.8.0</version>
                        <configuration>
                            <fork>true</fork>
                            <source>10</source>
                            <target>10</target>
                            <useIncrementalCompilation>false</useIncrementalCompilation>
                            <compilerArgs>
                                <arg>--patch-module</arg
   <arg>flexmark.util=${user.home}/.m2/repository/com/vladsch/flexmark/flexmark/0.34.56/flexmark-0.34.56.jar</arg>
                            </compilerArgs>
                        </configuration>
                    </plugin>
``` 

This time the error becomes:

```
[ERROR] /Users/bahri/projects/ourproject/src/main/java/com/com.ourcompany.OurClass.java:[10,27] error: package com.vladsch.flexmark.html is not visible
[ERROR]   (package com.vladsch.flexmark.html is declared in the unnamed module, but module com.vladsch.flexmark.html does not read it)
[ERROR] /Users/bahri/projects/ourproject/src/main/java/com/com.ourcompany.OurClass.java:[11,27] error: package com.vladsch.flexmark.parser is not visible
[ERROR]   (package com.vladsch.flexmark.parser is declared in the unnamed module, but module com.vladsch.flexmark.parser does not read it)
```

We tried to add exports to the patched module but the error did not change:

``` 
                            <compilerArgs>
                                <arg>--patch-module</arg>
                                <arg>flexmark.util=${user.home}/.m2/repository/com/vladsch/flexmark/flexmark/0.34.56/flexmark-0.34.56.jar</arg>
                                <arg>--add-exports</arg>
                                <arg>flexmark.util/com.vladsch.flexmark.html=ALL-UNNAMED</arg>
                                <arg>--add-exports</arg>
                                <arg>flexmark.util/com.vladsch.flexmark.parser=ALL-UNNAMED</arg>
                            </compilerArgs>
```

**Comment by vsch** [comment]
I fully agree and the library is well overdue for major refactoring that I did not do because it would break existing code. 

I am in the process of layout out the plan of action now so I can address this and other breaking clean up (#233) in one breaking release. I would like to include, if possible at least a RegEx to apply to existing source to help with the changes. I expect most of them will be import statement changes, most of which will be easily handled with a regex.
