### ISSUE TITLE
custom extension for file attachment syntaxes ![][] and [][]

### ISSUE THREAD

**Issue by rshah** [vsch/flexmark-java#275]
I want to create an extension for these file attachment syntaxes `![Alt Text][only image attachment id]` and `[Alt Text][normal file attachment id]`.
Basically the behavior is similar to link syntax but use `[` instead of `(` for link information.

For example:
`![myimage][12345]` will be converted to an `img` tag pointing to url for that image attachment file.
`[my report][12345]` will be converted to an `a` tag pointing to url for that normal attachment file.

Could you give some pointer which codes or extension should i learn from?

Thank you.

**Comment by vsch** [comment]
@rshah, the syntax you want to use is already implemented for inline parser as link and image refs.

The easiest way to get what you want is to create a custom node renderer for link and image refs which will not resolve using defined references but behave like link and image nodes.

* LinkRef rendering: [CoreNodeRenderer.java: Lines 942-1001](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/html/renderer/CoreNodeRenderer.java#L942-L1001)
* ImageRef rendering: [CoreNodeRenderer.java: Lines 888-940](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/html/renderer/CoreNodeRenderer.java#L888-L940)
* Link rendering: [CoreNodeRenderer.java: Lines 846-866](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/html/renderer/CoreNodeRenderer.java#L846-L866)
* Image rendering: [CoreNodeRenderer.java: Lines 818-844](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/html/renderer/CoreNodeRenderer.java#L818-L844)

* Custom node renderer sample: [NodeRendererSample.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/NodeRendererSample.java)


Both `LinkRef` and `ImageRef` nodes are `RefNode` classes and the `.getText()` returns the alt or text part of the node while `.getReference()` the url part of the node.

One caveat is that the syntax for link and image refs allows `[ref]` and `![ref]`, in which case the ref is provided and the text is equal to the ref. In this case the `RefNode.isReferenceTextCombined()` is true and `.getText().isNull()` is also true, with `.getText()` returning an empty based sequence.

**Comment by rshah** [comment]
@vsch 
Thank you for fast reply. I managed to implement basic renderer for my case.
