### ISSUE TITLE
Table Extension outputs  \u2028

### ISSUE THREAD

**Issue by rygel** [vsch/flexmark-java#276]
When using the table extension with no options set the outputted html includes the character /u2028 which messes up the rendering of the html later. Is there any option to suppress the creation of these characters or  to replace them with spaces?

And what is really strange about it is that these characters are not shown in IntelliJ (when looking at the string value in the debugger), but when the value is copied and pasted into e.g. Notepad++ then its visible. Also when I pipe the html as raw text to the Pebble Template Engine.

My input table looks like this (and is using CRLF as line endings):

\| Header 1 | Header 2 |
\| :------- | :------- |
\|    Row 1    |                                                                                                                                                     Row 2 |

**Comment by vsch** [comment]
@rygel, you have the line separators in your markdown source. 

In IntelliJ, https://plugins.jetbrains.com/plugin/7448-zero-width-characters-locator plugin has an inspection for zero width or whitespace looking non-space characters.

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/10299086/47714638-cefd5b80-dc13-11e8-8fa9-79088b06a2c7.png">

**Comment by rygel** [comment]
@vsch Thank you very much! I was looking all over the place, but did not think the source files would already contain the characters! I've installed the plugin and cleared the files and now everything works.

**Comment by vsch** [comment]
BTW, Markdown Navigator uses flexmark-java for its parsing and rendering. If you use standard extensions then you can preview the rendered result live in IntelliJ
