### ISSUE TITLE
How to add attribute (rel="nofollow") to anchor <a> for html nodes?

### ISSUE THREAD

**Issue by Elmervc** [vsch/flexmark-java#277]
I'd like to add the `rel="nofollow"` attribute to (most of the) rendered links from markdown texts.
I came around #103 and created an extension that handles `Link` and `AutoLink` nodes. This works great.
Now, I'd also like to add the rel attribute to anchor elements that are entered as HTML in the markdown input, but I cannot find out which node I need to match or how to match this.
Do you have any pointers? Thank you :)

```java
@Override
public void setAttributes(final Node node, final AttributablePart part, final Attributes attributes) {
  if (   (node instanceof Link || node instanceof AutoLink /*|| node instanceof ??SomeHTMLNode?? */)
      && (part == AttributablePart.LINK) ) {

    attributes.replaceValue("rel", "nofollow");

  }
}
```

**Comment by vsch** [comment]
@Elmervc, markdown does not parse HTML so you need to parse the node text for your tags and render the node in your extension with your changes. In this case the node is an `HtmlInline`, which will contain a contiguous run of HTML from the markdown.

If you don't have any mods for a particular node you can just let the previous renderer handle it by calling `context.delegateRender()`

The example from CoreNodeRenderer:

[`render(HtmlInline node, NodeRendererContext context, HtmlWriter html)`](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/html/renderer/CoreNodeRenderer.java#L726-L735)

and the function which implements the meat of handling all the suppression and escaping options:

[CoreNodeRenderer.java: Lines 742-750](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/html/renderer/CoreNodeRenderer.java#L742-L750)
