### ISSUE TITLE
markdown mode don't support delete line, ~~content~~ render to <del>content</del>

### ISSUE THREAD

**Issue by lynnchae** [vsch/flexmark-java#278]
markdown mode don't support delete line, '~~ content ~~' render to `<del>content</del>`

**Comment by vsch** [comment]
@lynnchae, the strikethrough syntax is not standard markdown. You need to add the gfm-strikethrough extension to the list of extensions for the parser.


See: 
[GitHubParsingSample.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/GitHubParsingSample.java)

**Comment by lynnchae** [comment]
ok, thank you.
