### ISSUE TITLE
Options for including custom anchor target attribute

### ISSUE THREAD

**Issue by mattjlewis** [vsch/flexmark-java#280]
Would it be possible to control the anchor target attribute value from custom attribute extensions?
For example to render something like this:
`
[Google](http://www.google.com){~external}
`
as:
`
<a href="http://www.google.com" target="external">Google</a>
`
I've looked at the examples and can see I could possibly control it by looking at the link URL, however, it would be nice to have some control over it.

Thanks

**Comment by vsch** [comment]
@mattjlewis, `[Google](http://www.google.com){target=external}` works so it would only be a matter of adding `~` to mean `target=` in the attributes extension.

**Q:** Is this what you mean or do you want to add the target attribute in the custom attribute provider?

If it is the latter then you can do that now. You can condition it by any of the node attributes.

**Comment by mattjlewis** [comment]
Wow, that's brilliant, thanks for your very swift response. I completely missed that I could do that.
