### ISSUE TITLE
Vulnerability of inlineed JavaScript execution 

### ISSUE THREAD

**Issue by bvn13** [vsch/flexmark-java#281]
If I parse the text below with FlexMark the `<script>` tag is not excaped. It leads to execute JS.

```
test

<script type="text/javascript">alert("1")</script>

test2
```

**Comment by bvn13** [comment]
I guess the question is about how to escape html tags but not within code-block.

**Comment by vsch** [comment]
@bvn13, [Extensions: HtmlRenderer Options](https://github.com/vsch/flexmark-java/wiki/Extensions#renderer) 

    `ESCAPE_HTML` default `false`, escape all html found in the document

Is the general suppression, the other ESCAPE_... give more granularity. Set to true to escape HTML.
