### ISSUE TITLE
how to use the toc extension and render it to html

### ISSUE THREAD

**Issue by lynnchae** [vsch/flexmark-java#282]
```java 
        MutableDataSet options = new MutableDataSet();
        options.setFrom(ParserEmulationProfile.MARKDOWN);
        options.set(Parser.EXTENSIONS, Arrays.asList(new Extension[]{TablesExtension.create(), TocExtension.create()}));
        Parser parser = Parser.builder(options).build();
        HtmlRenderer renderer = HtmlRenderer.builder(options).build();
        Node document = parser.parse(b.getContent());
        String html = renderer.render(document);
        String toc = ? ; // how to get it
```
how to render a toc html-formated with markdown content and get it?
thank you

**Comment by vsch** [comment]
@lynnchae,

If you want rendered TOC the easiest way is to use find the TOC node using a visitor [VisitorSample.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/VisitorSample.java) and then use the same code that is used by the extension renderer to render the node.

[TocNodeRenderer.java: Lines 45-54](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-toc/src/main/java/com/vladsch/flexmark/ext/toc/internal/TocNodeRenderer.java#L45-L60)

Alternately, you can find the node and then use the `HtmlRender.render(Node)` function or its variations to render it. This will work only for simple extensions that do not rely on document pre-processing information gathered during document rendering phase. TOC is a simple element so this should work.
