### ISSUE TITLE
''flexmark-html-parser' The module has an mistake

### ISSUE THREAD

**Issue by Only-lezi** [vsch/flexmark-java#287]
I have an HTML snippet like this:     
`<a href="https://github.com/vsch/flexmark-java">flexmark-java</<!-- [[[read_end]]] -->a>` 

I use the `flexmark-html-parser`   `FlexmarkHtmlParser.parse(html)` 
`FlexmarkHtmlParser` class at 727 line
This code creates an endless loop

**Comment by vsch** [comment]
@Only-lezi, thank you for the catch. I will address the endless loop issue but you will need to address the fact that this is invalid HTML.

You cannot have comments inside html opening or closing tags.

[Html 5 Syntax End Tags](https://www.w3.org/TR/html5/syntax.html#end-tags)

> ##### 8.1.2.2. End tags
> 
> End tags must have the following format:
> 
> 1. The first character of an end tag must be a U+003C LESS-THAN SIGN character (\<).
> 
> 2. The second character of an end tag must be a U+002F SOLIDUS character (/).
> 
> 3. The next few characters of an end tag must be the element's [tag name](https://www.w3.org/TR/html5/syntax.html#tag-name).
> 
> 4. After the tag name, there may be one or more [space characters](https://www.w3.org/TR/html5/infrastructure.html#space-characters).
> 
> 5. Finally, end tags must be closed by a U+003E GREATER-THAN SIGN character (\>).

**Comment by vsch** [comment]
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.
