### ISSUE TITLE
Markdown to PDF page split

### ISSUE THREAD

**Issue by Evertude** [vsch/flexmark-java#289]
Hi, i would like to specify that some groups of elements belong on the same page when creating a PDF file.
Is there any way to do so?

I made a small example where I would like to have all of the title-value combinations on the same page and also that there is no split in between a title or value element

![image](https://user-images.githubusercontent.com/7377709/50099784-351f5b80-021f-11e9-92c2-fa07fa3cd1f5.png)

**Comment by vsch** [comment]
@Evertude, the PDF conversion is very basic and relies on the OpenHtmlToPdf library. If you take a look at the implementation for flexmark pdf conversion you will see that it is minimal and relies on the OpenHtmlToPdf library to do all the work.

You can replace the bare bones implementation with your own which uses OpenHtmlToPdf. Then  you will only be limited by that library not my bare bones implementation.
