### ISSUE TITLE
An Apostrophe ' Breaks the Attributes Extension In-Line span

### ISSUE THREAD

**Issue by CorneliaXaos** [vsch/flexmark-java#296]
**Describe the bug**

As the title states, an apostrophe ' breaks the inline span.

Please provide as much information about where the bug is located or what you were using:

* [x] `AttributesExtension`
* [x] `TypographicExtension`

(See Below for full details of Flexmark Instance.)

**To Reproduce**

Run the following through the HTML Renderer with the Attributes Extension enabled.

```Markdown
This is a test. It works fine until a word like don't appears.{.style} Another style might follow.{.style2}
```

**Expected behavior** 

What is expected is that the class "style" would be applied to the entire first section:

```HTML
<span class="style">This is a test. It works fine until a word like don't appears.</span> ...
```

**Resulting Output** 

What actually happens is the apostrophe cuts the style short.

```HTML
This is a test. It works fine until a word like don'<span class="style">t appears.</span> ...
```

**Additional context**

I have a lot of extensions enabled, so it's possible that a couple are clobbering each other.  I know trying to use the  delimiter with the Attributes extension seems to break Emoji support as well (though I haven't fully looked into it).  Here's my Java code for my flexmark setup:

```java
final MutableDataSet options = new MutableDataSet();

// TODO - Make this configurable
options.set(EmojiExtension.ROOT_IMAGE_PATH, "https://www.webfx.com/tools/emoji-cheat-sheet/graphics/emojis/");
options.set(Parser.EXTENSIONS, Arrays.asList(
        AbbreviationExtension.create(),
        AnchorLinkExtension.create(),
        AsideExtension.create(),
        AttributesExtension.create(),
        DefinitionExtension.create(),
        EmojiExtension.create(),
        FootnoteExtension.create(),
        StrikethroughSubscriptExtension.create(),
        TablesExtension.create(),
        TaskListExtension.create(),
        MediaTagsExtension.create(),
        SuperscriptExtension.create(),
        TocExtension.create(),
        TypographicExtension.create(),
        YamlFrontMatterExtension.create()
));

parser = Parser.builder(options).build();
renderer = HtmlRenderer.builder(options).build();
```

**Comment by CorneliaXaos** [comment]
After further fiddling, it seems like the problem is the interaction with the escaped characters.  Namely, those produced by the Typographic Extension.  Things like `&rsquo;` won't accept any of the inline spans.  They are, however, still affected by the full-node styling.

**Comment by vsch** [comment]
@CorneliaXaos, I suspected that it would be the `TypographicExtension` that is an issue here. I will look into it. 

I suspect there is more logic needed for the attribute extension handling assignment of attributes to not treat typographic nodes as inline elements which can be decorated with attributes separately from the text containing them.

**Comment by CorneliaXaos** [comment]
I should note I tried to apply the style directly to the typographic element:

```Markdown
This doesn'{.style}t work.
```

It still doesn't get the style applied afterwards.  It just shows up as:

```HTML
<p>This doesn&rsquo;t work.</p>
```

**Comment by CorneliaXaos** [comment]
No problem.  Just noticed it while using the awesome software you put together.  Also, while it's not an extension, I did notice that it considers `<strong>` tags to be breaking.  So the following happens as well:

```Markdown
This has **strong** emphasis.{.style}
```

```HTML
<p>This has <strong>strong</strong><span class="style"> emphasis</span></p>
```

I don't know if that's desired behaviour or not.  (Probably so.)  I imagine the other inline emphasis elements will do the same. ( `*emphasis*` `~~strikethrough~~` `~subscript~` `^superscript^` etc.)

**Comment by vsch** [comment]
@CorneliaXaos, attributes are attached to immediately preceding inline "span" or stretch of plain text. If you want them to be attributed to the parent of the immediately preceding span then you should put a space before the style element.

If you want it to apply to the paragraph put it at the start of paragraph or after on its own line. Attributes by themselves on a line will attach to previous sibling element.

I found this gives the greatest flexibility but also fairly easy to understand where the attributes are attached in the AST. I could be wrong about the latter.

```markdown
This has ***strong** emphasis.{.style}*

This has ***strong** emphasis. {.style}*

{.style} This has ***strong** emphasis.*

This has ***strong** emphasis.*

{.style} 
```

```html
<p>This has <em><strong>strong</strong><span class="style"> emphasis.</span></em></p>
<p>This has <em class="style"><strong>strong</strong> emphasis.</em></p>
<p class="style">This has <em><strong>strong</strong> emphasis.</em></p>
<p class="style">This has <em><strong>strong</strong> emphasis.</em></p>
```

**Comment by vsch** [comment]
@CorneliaXaos, what issue did you get with the comment.

```markdown
{.A} This should be in style A. <!---->This in style B.{.B} And this style A again.
```
I am getting the following, which is as expected.

```html
<p class="A">This should be in style A. <!----><span class="B">This in style B.</span> And this style A again.</p>
```

Unfortunately, markdown does not have an NULL delimiter so HTML `<span>` has to be used.

Currently, attributes are not attached to HTML but can be if it makes the syntax easier:

**Comment by CorneliaXaos** [comment]
@vsch Huh..  I don't know what issue I had before.. but it's gone now.  Originally, it looked like using `<!---->` would cause any emojis to disappear if they came after.. but it seems like it works fine now..  I might have forgotten to close it?  Or I used the wrong number of hyphens or something.

I don't know what you meant by NULL delimiter..  `<span>` works fine for me.

The only thing I might desire might be a stronger left fence post.  The comment method (using `<!---->`) works so long as you don't have items within that aren't plaintext.  (i.e. `**` or an image or link)  It'd be nice to be able to fence a whole area in.. though I'm not sure what kind of results would come out the other end or how that would mess up the parsing and such.

In other words.. Something like this would be useful:

```Markdown
This is {>} an **arbitrary** span.{.style} It stretches along many nodes.
```

```HTML
<p>This is <span class="style"> an <strong>arbitrary</strong> span.</span> It stretches along many nodes.</p>
```

Even if it were limited to spreading over inline nodes only and not block nodes.  It would be immensely useful for my use case.  As I wouldn't be required to do the following:

```Markdown
This is an{.style} **arbitrary**{.style} span. It stretches along many nodes.{.style}
```

And I know there's the pre / post pending method for applying to the style to the whole thing, but it becomes a bit more complicated when I have two styles mixed within a single block like the following:

```Markdown
{.A} This is a more arbitrary example. <!---->This should{.B} **all**{.B} be in "B".{.B} The rest is in A.
```

(All because I need arbitrary ranges for my Markdown-based document editor. :stuck_out_tongue: )

**Comment by vsch** [comment]
@CorneliaXaos, I fixed the smarts issues with attributes and added an option to use `{.}` or `{#}` empty class or id attributes as attribute span delimiters.

* Add: `DoNotAttributeDecorate` interface to be implemented by all text nodes which do not
  result in span-like rendering of their text, such as `TypographicSmarts`, `TypographicQuotes`
  and `SoftLineBreak` but will erroneously create a break in the text and mess up attribute
  assignment to text spans.
* Add: `AttributesExtension.WRAP_NON_ATTRIBUTE_TEXT`, default `true`. When `false` does not wrap
  nodes marked as `DoNotAttributeDecorate` in `TextBase`. When `true`, will allow intuitive
  attribute processing for text containing `DoNotAttributeDecorate` as single text span instead
  of one interrupted by the typographic smarts nodes.
* Fix: `AttributesExtension` incorrectly parsed invalid empty sequences and absorbed the text
  instead of skipping it. ie. `{}`, `{ }`, `{#}` and `{.}`
* Add: `AttributesExtension.USE_EMPTY_IMPLICIT_AS_SPAN_DELIMITER`, default `false`. When set to
  `true` will treat `{#}` or `{.}`, without embedded spaced, as start attribute span delimiter to
  mark start of attribute assignment to text between `{.}` or `{#}` and the matching attributes
  element. 

Now you can `AttributesExtension.USE_EMPTY_IMPLICIT_AS_SPAN_DELIMITER` set to `true` to use:

```markdown
Cond {.}1.2 {.}decorated text {.red} {.green}
```

to get:

```html
<p>Cond <span class="green">1.2 <span class="red">decorated text </span></span></p>
```

Note that attribute span delimiters override assignment to parent for "unattached" attributes to previous node and that `{.}` and `{#}` can be used interchangeably.

**Comment by vsch** [comment]
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by CorneliaXaos** [comment]
@vsch That was fast! That new empty implicit span marker is actually just what I needed! Thank you for putting a fix in so fast.

**Comment by vsch** [comment]
@CorneliaXaos, you are welcome. It sounded like you had to go through hoops to get around the limitations so it made it a priority.

**Comment by CorneliaXaos** [comment]
@vsch Thank-you.  I was figuring out simple work-arounds for right now. The software I'm making is very much still in the alpha phase and isn't available publicly yet, but thank you again for fixing those issues for me.

And I tend to be verbose when describing things. :P

**Comment by vsch** [comment]
@CorneliaXaos, being verbose is not an issue. I am a fast reader. I prefer that to incomprehensibly terse communications. 😉
