### ISSUE TITLE
Typography extension breaks some auto links

### ISSUE THREAD

**Issue by maxcom** [vsch/flexmark-java#300]
I use Autolink and TypographicExtension and I found that some URL's are incorrectly linked. For example link `https://youtu.be/L1--OW4j0Pw` is converted to `https://youtu.be/L1–OW4j0Pw`. Autolink then chooses only first part of link, `https://youtu.be/L1`.

I expect that typography extension do not replace `--` in URL.

**Comment by vsch** [comment]
@maxcom, yes it is an omission in auto-link processing. Each text node is taken separately for link processing.

Typographic extension breaks up a single text node to insert a typographic node.

I added code to auto-link extension to combine following TypographicText nodes and Text nodes if they don't have spaces between them and process the combined text.

All nodes involved in processing are removed from the AST, except trailing ones which had no links.

It may have side-effect of removing valid typographic nodes but I will address this as the test cases are found.

**Comment by vsch** [comment]
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by vsch** [comment]
@maxcom, found the use case causing removal of typographic text nodes. #301

Fixed for next release. If it is an issue you are encountering please let me know and I will make a release. Otherwise, I will wait to accumulate a few other bug fixes before releasing.

**Comment by maxcom** [comment]
Thank you.
