### ISSUE TITLE
Can we add support for password support pdfs?

### ISSUE THREAD

**Issue by niksw7** [vsch/flexmark-java#303]

**Comment by vsch** [comment]
@niksw7, the library provides a very thin wrapper for the OpenHtmlToPDF library, so if what you need is possible with OpenHtmlToPDF then it should be very easy to add. 

The whole extension is 50 lines. [PdfConverterExtension.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-pdf-converter/src/main/java/com/vladsch/flexmark/pdf/converter/PdfConverterExtension.java)

**Comment by niksw7** [comment]
@vsch yes it's possible in openhtmlToPdf. 
https://github.com/danfickle/openhtmltopdf/issues/30#issuecomment-231359179
I created this PR that will add this functionality in flexmark-java. 
The feature it will provide along with password encrypted pdf is readOnly pdfs,print-permissions,etc as stated here (https://pdfbox.apache.org/docs/2.0.5/javadocs/org/apache/pdfbox/pdmodel/encryption/AccessPermission.html)
I was debating if I should be adding a new method exportToProtectedPdf or simply overload method of exportToPdf. The latter approach will break for folks using older api.

I have created a PR with the latter approach. Please review and let me know for any feedbacks.
https://github.com/vsch/flexmark-java/pull/306

**Comment by vsch** [comment]
@niksw7, thank you very much for taking care of this. I will take a look at the code and provide feedback.

**Comment by vsch** [comment]
@niksw7, I took a look at the code and the only thing that I would change is add an option to hold the PDF protection policy. That way it does not need to be passed separately and only needs to be setup once in options used for parsing/rendering and subsequently re-used for all pdf conversions using these options. The same way it is done for the default text direction. 

I will also add overloaded export functions passing null for protection policy so the API remains unbroken for existing code.

Great job. I will make a release shortly.

**Comment by niksw7** [comment]
Great!
