### ISSUE TITLE
EmojiExtension doesn't support all emoji listed at the Cheat Sheet

### ISSUE THREAD

**Issue by CorneliaXaos** [vsch/flexmark-java#304]
**Describe the bug**
(Note, not really an urgent bug.  Just putting this here for documentation.)
The EmojiExtension seems to be missing a few emoji from the [Cheat Sheet.][CHEAT]

* [ ] `EmojiExtension`

**To Reproduce**

Attempt to render `:simple_smile:`, the third emoji listed on the cheat sheet.  I checked in `flexmark-ext-emoji/src/test/java/com/vladsch/flexmark/ext/emoji/EmojiCheatSheetRaw.java` and noticed that this emoji is not present there.

**Expected behavior**
Is it to be expected that **all** emoji on the cheat sheet be supported?  If not, can we get a definitive list somewhere?  If we're using the cheat sheet as our definitive guide we may want to make sure all the emoji information is present and correct.  (I know we don't support the campfire sound snippets.)

**Additional context**
I'm using the same environment as in #296 .  Here's my options and parser / renderer setup again:
```java
final MutableDataSet options = new MutableDataSet();

// TODO - Make this configurable
options.set(EmojiExtension.ROOT_IMAGE_PATH, "https://www.webfx.com/tools/emoji-cheat-sheet/graphics/emojis/");
options.set(Parser.EXTENSIONS, Arrays.asList(
        AbbreviationExtension.create(),
        AnchorLinkExtension.create(),
        AsideExtension.create(),
        AttributesExtension.create(),
        DefinitionExtension.create(),
        EmojiExtension.create(),
        FootnoteExtension.create(),
        StrikethroughSubscriptExtension.create(),
        TablesExtension.create(),
        TaskListExtension.create(),
        MediaTagsExtension.create(),
        SuperscriptExtension.create(),
        TocExtension.create(),
        TypographicExtension.create(),
        YamlFrontMatterExtension.create()
));

parser = Parser.builder(options).build();
renderer = HtmlRenderer.builder(options).build();
```

[CHEAT]: https://www.webfx.com/tools/emoji-cheat-sheet/

**Comment by vsch** [comment]
@CorneliaXaos, you are right. It is the only missing shortcut from emoji cheat sheet.

Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by vsch** [comment]
@CorneliaXaos, I am working on the next release of my [Markdown Navigator plugin for JetBrains IDEs](http://vladsch.com/product/markdown-navigator), which uses this library for markdown parsing.

I am at the keyboard and stamping out bugs as fast as they come to my attention so I can make a release and take a break. 😀 

Yours was an exceptionally easy fix. I missed this shortcut when I created the [emoji-cross-reference](https://github.com/vsch/emoji-cross-reference)

**Comment by CorneliaXaos** [comment]
Still some issues I've posted sit and sit. :stuck_out_tongue:. Side question: I forget who closes these. Me or you. :P

**Comment by vsch** [comment]
@CorneliaXaos, if the solution resolves your issue then you can close it. I can always re-open an issue if needed.
