### ISSUE TITLE
Billeting in markdown to html and pdf not working 

### ISSUE THREAD

**Issue by sirishayalavarthi** [vsch/flexmark-java#309]
using bulleting like below text markdown

![capture](https://user-images.githubusercontent.com/39520433/52627707-f7724280-2ef0-11e9-9d20-196a41bb2eca.PNG)

it should be displayed in pdf 

![capture](https://user-images.githubusercontent.com/39520433/52627584-b37f3d80-2ef0-11e9-813e-9ed08665d7ae.PNG)

but still displaying like below in pdf
![capture](https://user-images.githubusercontent.com/39520433/52627731-035e0480-2ef1-11e9-924b-0575c95e8abb.PNG)

**Comment by vsch** [comment]
@sirishayalavarthi, can you please provide the HTML generated from your markdown, before you render it to PDF. PDF uses HTML to PDF conversion, so if your HTML is not right then the PDF will not be right.

**Comment by sirishayalavarthi** [comment]
> @sirishayalavarthi, can you please provide the HTML generated from your markdown, before you render it to PDF. PDF uses HTML to PDF conversion, so if your HTML is not right then the PDF will not be right.

Html also looks the same as below 

* testing bullet

it supposes to be

<ul>
 <li> testing bullet </li>
</ul>

**Comment by vsch** [comment]
@sirishayalavarthi, then you obviously have either wrong settings for your markdown source or something wrong in your markdown.

Try it on: [babelmarkIII](https://babelmark.github.io) and see which parsers return your expected result.

If you are trying to use CommonMark then you can also try it in GitHub comments/Documents. Both are CommonMark compliant.

**Comment by sirishayalavarthi** [comment]
> @sirishayalavarthi, then you obviously have either wrong settings for your markdown source or something wrong in your markdown.
> 
> Try it on: [babelmarkIII](https://babelmark.github.io) and see which parsers return your expected result.
> 
> If you are trying to use CommonMark then you can also try it in GitHub comments/Documents. Both are CommonMark compliant.

Thank you. Then I will close this issue. I will check my settings.
