### ISSUE TITLE
Inserted Node doesn't get rendered?

### ISSUE THREAD

**Issue by sez11a** [vsch/flexmark-java#311]
For some reason (lack of morning coffee maybe), I posted a question to [StackOverflow](https://stackoverflow.com/q/54829911/6627193) before coming here. 

I'm trying to get Flexmark to render image alt text as a caption, [the way Pandoc does it](https://pandoc.org/MANUAL.html#images). I made a Visitor that visits all Image Nodes and does this: 

	BasedSequence text = image.getText();
	Paragraph caption = new Paragraph(text);
	Node parent = image.getParent();
	parent.insertAfter(caption);

I have verified during debugging that calling `parent.getNext()` after this correctly returns my caption Paragraph object, so as far as I can tell, it's getting inserted correctly. However, when the document is rendered, the Paragraph I inserted isn't there. 

Am I doing something wrong, or is this a bug? Thanks!

**Comment by vsch** [comment]
@sez11a, If you can give me a bit **more information about the rendered HTML result** you want, I can provide you with the corrected code.

In flexmark each node's text contains strings from original file, with start/end offsets. This means that inserting nodes is a bit more involved. The offsets are expected to be in increasing, non-overlapping order.

It is possible to insert text from outside of the original file but it requires providing a location where in the file it is inserted to allow the rest of the code expecting original file offset locations to work correctly.

I will be reworking the library to make AST manipulation easier amongst other improvements but for now it is a bit of a PITA.

**Comment by sez11a** [comment]
Hi @vsch I would be very happy to provide an example: 

     <p>
	     <img alt="Figure 1: Some description here." src="/images/somefile.png" />
     </p>	

     <p class="caption">Figure 1: Some description here.</p>

The text is in the original file; I just need to copy it from the image element into its own paragraph. 

Thanks for your help!

**Comment by vsch** [comment]
@sez11a, I added a sample with the code to do what you described [NodeInsertingPostProcessorSample.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/NodeInsertingPostProcessorSample.java)

I had to improvise on how to add attributes to a generic `Paragraph` node since the AST has no provisions for doing so. I did not want to provide a custom node and custom renderer.

I like the solution so much I am adding it by default into the core as of next release. It is also a quick and dirty way to attach any additional information to a node in the AST.

```text
---- Markdown ------------------------

![Figure 1. Some description here.](http://example.com/image.png) **baz**

![bar]

![Figure 1. Some description here.][bar]

[bar]: http://example.com/image.png 'Image Title'

---- HTML ------------------------

<p><img src="http://example.com/image.png" alt="Figure 1. Some description here." /> <strong>baz</strong></p>
<p class="caption">Figure 1. Some description here.</p>
<p><img src="http://example.com/image.png" alt="bar" title="Image Title" /></p>
<p class="caption">bar</p>
<p><img src="http://example.com/image.png" alt="Figure 1. Some description here." title="Image Title" /></p>
<p class="caption">Figure 1. Some description here.</p>

---- AST ------------------------

Document[0, 176]
  Paragraph[0, 74] isTrailingBlankLine
    Image[0, 65] textOpen:[0, 2, "!["] text:[2, 34, "Figure 1. Some description here."] textClose:[34, 35, "]"] linkOpen:[35, 36, "("] url:[36, 64, "http://example.com/image.png"] pageRef:[36, 64, "http://example.com/image.png"] linkClose:[64, 65, ")"]
      Text[2, 34] chars:[2, 34, "Figur … here."]
    Text[65, 66] chars:[65, 66, " "]
    StrongEmphasis[66, 73] textOpen:[66, 68, "**"] text:[68, 71, "baz"] textClose:[71, 73, "**"]
      Text[68, 71] chars:[68, 71, "baz"]
  Paragraph[74, 74]
    EmbeddedNodeAttributes[74, 74], attributes: Attributes{class="caption"}
    Text[74, 74] chars:[74, 74, "Figur … here."] text "Figur … here."
  Paragraph[75, 82] isTrailingBlankLine
    ImageRef[75, 81] referenceOpen:[75, 77, "!["] reference:[77, 80, "bar"] referenceClose:[80, 81, "]"]
      Text[77, 80] chars:[77, 80, "bar"]
  Paragraph[82, 82]
    EmbeddedNodeAttributes[82, 82], attributes: Attributes{class="caption"}
    Text[82, 82] chars:[82, 82, "bar"] text "bar"
  Paragraph[83, 124] isTrailingBlankLine
    ImageRef[83, 123] textOpen:[83, 85, "!["] text:[85, 117, "Figure 1. Some description here."] textClose:[117, 118, "]"] referenceOpen:[118, 119, "["] reference:[119, 122, "bar"] referenceClose:[122, 123, "]"]
      Text[85, 117] chars:[85, 117, "Figur … here."]
  Paragraph[124, 124]
    EmbeddedNodeAttributes[124, 124], attributes: Attributes{class="caption"}
    Text[124, 124] chars:[124, 124, "Figur … here."] text "Figur … here."
  Reference[125, 174] refOpen:[125, 126, "["] ref:[126, 129, "bar"] refClose:[129, 131, "]:"] url:[132, 160, "http://example.com/image.png"] titleOpen:[161, 162, "'"] title:[162, 173, "Image Title"] titleClose:[173, 174, "'"]
```

**Comment by sez11a** [comment]
Thank you! I just implemented this and it works perfectly. I would never have been able to figure out all that by myself. Do you want me to close this issue/question?

**Comment by vsch** [comment]
@sez11a, you are welcome. 

BTW, I cannot blame you for not being able to figure it out when I have not provided good enough docs to describe the internals. I have added a todo item on my list to give a better overview of the architecture and internal workings. 

Of course every question leads to more samples. I will add a cross reference for samples in the docs too.

Feel free to close the issue.

**Comment by DaveJarvis** [comment]
https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/NodeInsertingPostProcessorSample.java
