### ISSUE TITLE
Not converting a basic link?

### ISSUE THREAD

**Issue by dmnt3rr0r** [vsch/flexmark-java#312]
I am trying to do what I believe is a dead simple test of this library. I am using the following scala code to do the parsing:
```scala
    import com.vladsch.flexmark.util.ast.Node
    import com.vladsch.flexmark.html.HtmlRenderer
    import com.vladsch.flexmark.parser.Parser
    import com.vladsch.flexmark.util.options.MutableDataSet
    import com.vladsch.flexmark.convert.html.FlexmarkHtmlParser
    import com.vladsch.flexmark.test.AstCollectingVisitor

    lazy val flxmkOptions: MutableDataSet = new MutableDataSet()
    lazy val flxmkParser: Parser = Parser.builder(flxmkOptions).build()
    lazy val flxmkRenderer: HtmlRenderer = HtmlRenderer.builder(flxmkOptions).build()

    def parseMarkdown(in: String): String = {
      val document: Node = flxmkParser.parse(in)
      println(new AstCollectingVisitor().collectAndGetAstText(document))
      flxmkRenderer.render(document)
    }
```

When the parseMarkdown function is given this string: 
`I have something to __SAY__ [okay](https://www.google.com) ?`

It generates this:
`<p>I have something to <strong>SAY</strong> [okay](https://www.google.com/) ?</p>`

Notice this link is not converted... Is there a feature I need to enable? I looked through the features and could not see anything about enabling basic linking. 

If it helps, here is the AST:

Document[0, 64]
  Paragraph[0, 64]
    Text[0, 20] chars:[0, 20, "I hav … g to "]
    StrongEmphasis[20, 27] textOpen:[20, 22, "__"] text:[22, 25, "SAY"] textClose:[25, 27, "__"]
      Text[22, 25] chars:[22, 25, "SAY"]
    Text[27, 63] chars:[27, 63, " \[ok … m/) ?"]

I must be missing something -- please let me know if it is obvious. Thank you

**Comment by vsch** [comment]
@dmnt3rr0r, I don't know what Scala is doing to cause this. I get by in Scala only insofar as it resembles Kotlin.

I translated your case to Java:

```java
import com.vladsch.flexmark.html.HtmlRenderer;
import com.vladsch.flexmark.parser.Parser;
import com.vladsch.flexmark.test.AstCollectingVisitor;
import com.vladsch.flexmark.util.ast.Node;
import com.vladsch.flexmark.util.options.MutableDataSet;

public class Issue312 {
    final static MutableDataSet flxmkOptions = new MutableDataSet();
    final static Parser flxmkParser = Parser.builder(flxmkOptions).build();
    final static HtmlRenderer flxmkRenderer = HtmlRenderer.builder(flxmkOptions).build();

    static String parseMarkdown(String in) {
        Node document = flxmkParser.parse(in);
        System.out.println(new AstCollectingVisitor().collectAndGetAstText(document));
        return flxmkRenderer.render(document);
    }

    public static void main(String args[]) {
        String html = parseMarkdown("I have something to __SAY__ [okay](https://www.google.com) ?");
        System.out.println(html);
    }
}
```

And here is the output in the console:

```text
Document[0, 60]
  Paragraph[0, 60]
    Text[0, 20] chars:[0, 20, "I hav … g to "]
    StrongEmphasis[20, 27] textOpen:[20, 22, "__"] text:[22, 25, "SAY"] textClose:[25, 27, "__"]
      Text[22, 25] chars:[22, 25, "SAY"]
    Text[27, 28] chars:[27, 28, " "]
    Link[28, 58] textOpen:[28, 29, "["] text:[29, 33, "okay"] textClose:[33, 34, "]"] linkOpen:[34, 35, "("] url:[35, 57, "https://www.google.com"] pageRef:[35, 57, "https://www.google.com"] linkClose:[57, 58, ")"]
      Text[29, 33] chars:[29, 33, "okay"]
    Text[58, 60] chars:[58, 60, " ?"]

<p>I have something to <strong>SAY</strong> <a href="https://www.google.com">okay</a> ?</p>
```

**Comment by vsch** [comment]
@dmnt3rr0r, I added a Scala module to my test samples and did my best to make a sample in scala as you had it and be able to test it in IntelliJ. I am using scala-sdk-2.11.11:

```scala
import com.vladsch.flexmark.html.HtmlRenderer
import com.vladsch.flexmark.parser.Parser
import com.vladsch.flexmark.test.AstCollectingVisitor
import com.vladsch.flexmark.util.ast.Node
import com.vladsch.flexmark.util.options.MutableDataSet

object Issue312 {
  lazy val flxmkOptions: MutableDataSet = new MutableDataSet()
  lazy val flxmkParser: Parser = Parser.builder(flxmkOptions).build()
  lazy val flxmkRenderer: HtmlRenderer = HtmlRenderer.builder(flxmkOptions).build()

  def parseMarkdown(in: String): String = {
    val document: Node = flxmkParser.parse(in)
    println(new AstCollectingVisitor().collectAndGetAstText(document))
    flxmkRenderer.render(document)
  }

  def main(args: Array[String]) {
    val html = parseMarkdown("I have something to __SAY__ [okay](https://www.google.com) ?")
    println(html)
  }
}
```

The results are the same as Java:

```text
Document[0, 60]
  Paragraph[0, 60]
    Text[0, 20] chars:[0, 20, "I hav … g to "]
    StrongEmphasis[20, 27] textOpen:[20, 22, "__"] text:[22, 25, "SAY"] textClose:[25, 27, "__"]
      Text[22, 25] chars:[22, 25, "SAY"]
    Text[27, 28] chars:[27, 28, " "]
    Link[28, 58] textOpen:[28, 29, "["] text:[29, 33, "okay"] textClose:[33, 34, "]"] linkOpen:[34, 35, "("] url:[35, 57, "https://www.google.com"] pageRef:[35, 57, "https://www.google.com"] linkClose:[57, 58, ")"]
      Text[29, 33] chars:[29, 33, "okay"]
    Text[58, 60] chars:[58, 60, " ?"]

<p>I have something to <strong>SAY</strong> <a href="https://www.google.com">okay</a> ?</p>

```

**What is the exact string you are passing to the `parseMarkdown` function?** You must have some Unicode embedded whitespace characters which are not really spaces as far as CommonMark is concerned. The parser has not been updated to the latest CommonMark's work in progress [cmark/spec.txt] which mentions treating some Unicode whitespace characters some of the time as equivalent to non-Unicode whitespace characters.

[cmark/spec.txt]: https://github.com/commonmark/cmark/blob/master/test/spec.txt "cmark/spec.txt at master · commonmark/cmark · GitHub"

[cmark/spec.txt]: https://github.com/commonmark/cmark/blob/master/test/spec.txt "cmark/spec.txt at master · commonmark/cmark · GitHub"

**Comment by dmnt3rr0r** [comment]
Thanks for checking on your end. I will dig in to the encoding coming from the SAS and make sure they are not sending some strange characters.

**Comment by vsch** [comment]
@dmnt3rr0r, if you can save the string they are sending to a file and give me a link to it or just dump out the string bytes as an array so I can paste it into code and convert it to a string then I can see on my end what it  is that is causing it. I just cannot do it without the actual string content.

**Comment by dmnt3rr0r** [comment]
Ack! the SAS was escaping the "["!  Thank you very much for your help. This one is solved.

**Comment by vsch** [comment]
@dmnt3rr0r, you are welcome.
