### ISSUE TITLE
Ability to override character replacements map in FlexmarkHtmlParser

### ISSUE THREAD

**Issue by dmitrymurashenkov** [vsch/flexmark-java#314]
**Is your feature request related to a problem? Please describe.**

I need to convert html to markdown. Input has special characters like: «», —. I want to replace them with standard asii chars "", -. 

At the moment I only can either leave them as is with TYPOGRAPHIC_QUOTES, TYPOGRAPHIC_SMARTS options or have them converterd to <<>>, ---.

**Describe the solution you'd like**

Make FlexmarkHtmlParser take option with custom character replacement map.

It seems that regexes used to find typographic chars is too complex approach - simple map would suffice.

**Comment by vsch** [comment]
@dmitrymurashenkov, this one is easy. I will just add an option with current defaults that you can override with any HTML content.

**Comment by vsch** [comment]
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by dmitrymurashenkov** [comment]
Houston, we have a problem!

I'm not sure if I'm doing something wrong, but this doesn't compile:

```
new MutableDataSet().set(FlexmarkHtmlParser.TYPOGRAPHIC_REPLACEMENT_MAP, new HashMap<>());
```

Seems some java generics issue, but I'm can't find a way to invoke this API. 

@vsch Perhaps you should take a look and either fix it one more time or provide an example :)

**Comment by vsch** [comment]
@dmitrymurashenkov, I think because the key is Map<String,String> the compiler has issues with figuring out the template parameters.

Use the same code as in the HTML Parser key definition for the default value with explicit template arguments: `new HashMap<String, String>()`

**Comment by dmitrymurashenkov** [comment]
I tried these and none of them compiles:

```
Map m1 = new HashMap<String, String>();
        Map<String, String> m2 = new HashMap<String, String>();
        Map<String, String> m3 = new HashMap<>();
        
        new MutableDataSet().set(FlexmarkHtmlParser.TYPOGRAPHIC_REPLACEMENT_MAP, new HashMap<>());
        new MutableDataSet().set(FlexmarkHtmlParser.TYPOGRAPHIC_REPLACEMENT_MAP, new HashMap<String, String>());
        new MutableDataSet().set(FlexmarkHtmlParser.TYPOGRAPHIC_REPLACEMENT_MAP, new HashMap<String, String>() {});
        new MutableDataSet().set(FlexmarkHtmlParser.TYPOGRAPHIC_REPLACEMENT_MAP, m1);
        new MutableDataSet().set(FlexmarkHtmlParser.TYPOGRAPHIC_REPLACEMENT_MAP, m2);
        new MutableDataSet().set(FlexmarkHtmlParser.TYPOGRAPHIC_REPLACEMENT_MAP, m3);
```

**Comment by vsch** [comment]
@dmitrymurashenkov, it's a bug in the MutableDataSet set(). It needs ? super T instead of T for the key template param.

I will patch and release right away.

**Comment by vsch** [comment]
@dmitrymurashenkov, 
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.
