### ISSUE TITLE
Aside extension not generating <aside> tags?

### ISSUE THREAD

**Issue by sez11a** [vsch/flexmark-java#315]
Hello! 

I have the Aside extension configured like this: 

     options.set(Parser.EXTENSIONS, 
			Arrays.asList(TablesExtension.create(),
				StrikethroughExtension.create(),
				AnchorLinkExtension.create(),
				AsideExtension.create(),
				DefinitionExtension.create(),
				FootnoteExtension.create(),
				MediaTagsExtension.create(),
				SuperscriptExtension.create(),
				TocExtension.create(),
				TypographicExtension.create(),
				YamlFrontMatterExtension.create(),
				ImageCaptionPostProcessorExtension.create()
				));
		_parser = Parser.builder(options).build();
		_renderer = HtmlRenderer.builder(options).build();`

I have Markdown that looks like this: 

     | **Note:** This is an aside we intend to style into a sidebar.  Follow [Some
     | Link](#link-here) in the sidebar to go to another document or place in this 
     | document. 

Here's the output I'm getting: 

     <p> 
	     <strong>Note:</strong> This is an aside we intend to style into a sidebar.  
             Follow <a href="#link-here">Some Link</a> in the sidebar to go to another 
             document or place in this document.  
     </p>

My understanding from reading the Aside extension docs is that Asides should look like this when processed: 

     <aside> 
	     <strong>Note:</strong> This is an aside we intend to style into a sidebar.  
             Follow <a href="#link-here">Some Link</a> in the sidebar to go to another 
             document or place in this document.  
     </aside>

It's very possible my markdown is wrong, but I don't think so. Am I configuring this right? Something's getting recognized because the pipe characters are getting removed from the Markdown. 

Thanks for your help!

**Comment by sez11a** [comment]
Note: I just upgraded to 0.40.18 and changed my options to below, but I still get the same behavior: 

     MutableDataSet options = new MutableDataSet()
				.set(HtmlRenderer.GENERATE_HEADER_ID, true)
				.set(AsideExtension.EXTEND_TO_BLANK_LINE, false)
				.set(AsideExtension.IGNORE_BLANK_LINE, false)
				.set(AsideExtension.ALLOW_LEADING_SPACE, true)
				.set(AsideExtension.INTERRUPTS_PARAGRAPH, true)
				.set(AsideExtension.INTERRUPTS_ITEM_PARAGRAPH, true)
				.set(AsideExtension.WITH_LEAD_SPACES_INTERRUPTS_ITEM_PARAGRAPH, true);

**Comment by vsch** [comment]
@sez11a, you forgot to add the `AsideExtension` to the list of parser extensions. Setting of the options is not enough since options are ignored by all except the intended exception.

```java
public class Issue315 {
    final static MutableDataSet flxmkOptions = new MutableDataSet()
            .set(HtmlRenderer.GENERATE_HEADER_ID, true)
            .set(AsideExtension.EXTEND_TO_BLANK_LINE, false)
            .set(AsideExtension.IGNORE_BLANK_LINE, false)
            .set(AsideExtension.ALLOW_LEADING_SPACE, true)
            .set(AsideExtension.INTERRUPTS_PARAGRAPH, true)
            .set(AsideExtension.INTERRUPTS_ITEM_PARAGRAPH, true)
            .set(AsideExtension.WITH_LEAD_SPACES_INTERRUPTS_ITEM_PARAGRAPH, true)
            .set(Parser.EXTENSIONS, Collections.singletonList(AsideExtension.create()));
            
    final static Parser flxmkParser = Parser.builder(flxmkOptions).build();
    final static HtmlRenderer flxmkRenderer = HtmlRenderer.builder(flxmkOptions).build();

    static String parseMarkdown(String in) {
        Node document = flxmkParser.parse(in);
        System.out.println(new AstCollectingVisitor().collectAndGetAstText(document));
        return flxmkRenderer.render(document);
    }

    public static void main(String args[]) {
        String html = parseMarkdown(" | **Note:** This is an aside we intend to style into a sidebar.  Follow [Some\n" +
                " | Link](#link-here) in the sidebar to go to another document or place in this \n" +
                " | document. \n");
        System.out.println(html);
    }
}
```

Output:

```text
Document[0, 173]
  AsideBlock[1, 173] marker:[1, 2, "|"]
    Paragraph[3, 173]
      StrongEmphasis[3, 12] textOpen:[3, 5, "**"] text:[5, 10, "Note:"] textClose:[10, 12, "**"]
        Text[5, 10] chars:[5, 10, "Note:"]
      Text[12, 73] chars:[12, 73, " This … llow "]
      Link[73, 99] textOpen:[73, 74, "["] text:[74, 86, "Some\nLink"] textClose:[86, 87, "]"] linkOpen:[87, 88, "("] url:[88, 98, "#link-here"] pageRef:[88, 88] anchorMarker:[88, 89, "#"] anchorRef:[89, 98, "link-here"] linkClose:[98, 99, ")"]
        Text[74, 78] chars:[74, 78, "Some"]
        SoftLineBreak[78, 79]
        Text[82, 86] chars:[82, 86, "Link"]
      Text[99, 157] chars:[99, 157, " in t …  this"]
      SoftLineBreak[158, 159]
      Text[162, 171] chars:[162, 171, "document."]

<aside>
<p><strong>Note:</strong> This is an aside we intend to style into a sidebar.  Follow <a href="#link-here">Some
Link</a> in the sidebar to go to another document or place in this
document.</p>
</aside>
```

**Comment by sez11a** [comment]
@vsch I have it (please see my `options.set` call at the top of the ticket). I actually have a whole bunch of extensions in the list.

**Comment by vsch** [comment]
Modified for your list from top comment and still getting the same output:

```java
public class Issue315 {
    final static MutableDataSet flxmkOptions = new MutableDataSet()
            .set(Parser.EXTENSIONS,
                    Arrays.asList(TablesExtension.create(),
                            AsideExtension.create(),
                            StrikethroughExtension.create(),
                            AnchorLinkExtension.create(),
                            DefinitionExtension.create(),
                            FootnoteExtension.create(),
                            MediaTagsExtension.create(),
                            SuperscriptExtension.create(),
                            TocExtension.create(),
                            TypographicExtension.create(),
                            //ImageCaptionPostProcessorExtension.create(),
                            YamlFrontMatterExtension.create()
                    ));;
            
    final static Parser flxmkParser = Parser.builder(flxmkOptions).build();
    final static HtmlRenderer flxmkRenderer = HtmlRenderer.builder(flxmkOptions).build();

    static String parseMarkdown(String in) {
        Node document = flxmkParser.parse(in);
        System.out.println(new AstCollectingVisitor().collectAndGetAstText(document));
        return flxmkRenderer.render(document);
    }

    public static void main(String args[]) {
        String html = parseMarkdown(" | **Note:** This is an aside we intend to style into a sidebar.  Follow [Some\n" +
                " | Link](#link-here) in the sidebar to go to another document or place in this \n" +
                " | document. \n");
        System.out.println(html);
    }
}
```

Can you post a `String markdown = "..."` with your exact text you are parsing?

**Comment by sez11a** [comment]
I can do better than that. :-) The Markdown I'm trying to parse is in the master branch here: 

https://github.com/liferay/liferay-docs/ 

The specific file is here: 

https://github.com/liferay/liferay-docs/blob/master/developer/reference/articles/tooling/01-creating-a-project.markdown

To find out more about Liferay, you can go here: https://community.liferay.com 

It looks like this affects more than one extension. AnchorLinks and Typographic seem to be working fine, but I just tested ToCExtension, and that one isn't working either. There must be something weird going on with the way I'm initializing them. Could it be that we use hard returns in our Markdown?

**Comment by vsch** [comment]
@sez11a, as a quick test I downloaded the file and opened it in IntelliJ using my plugin [Markdown Navigator] and enabled `Aside` extension and it parses and previews just fine. None of the images or links resolve but I only have that one file.

![issue315_asideextension](https://user-images.githubusercontent.com/10299086/53374210-b84ae500-3925-11e9-9d62-f3b3c420f298.png)

I will try to use your extension list and parse the file to see what it gives.

Have you tried disabling the `ImageCaptionPostProcessorExtension` to see if it makes a difference. Because that is the only thing I did not have in my test.

[Markdown Navigator]: http://vladsch.com/product/markdown-navigator

**Comment by sez11a** [comment]
@vsch  The `ImageCaptionPostProcessorExtension` is #311 so it's pretty much all your code. I can disable it and see. In fact, maybe I'll disable everything except Asides and see if it starts working.

**Comment by vsch** [comment]
@sez11a, you should not have to disable anything but as a test it is a good approach.

I cannot see what is causing it but then it is always not obvious until it is isolated to a bug.

**Comment by sez11a** [comment]
@vsch I disabled every extension except YamlFrontMatter and Aside and I still have the same problem. My code "imports" markdown into a Liferay application called Knowledge Base. I'm using YamlFrontMatter to store what we call a `header-id`, which is the URL to the converted file in the Knowledge Base. I can't disable YamlFrontMatter because the markdown won't import without it. (The `header-id` is just the first thing I want to use YamlFrontMatter for; I'm hoping later to implement auto-tagging from a list of tags in the header.)

**Comment by vsch** [comment]
@sez11a, what text are you passing to the parser?. The YAML is not a problem. I suspect that there is something else going on that is mangling the text before the parser gets it.

**Comment by vsch** [comment]
@sez11a, can you save the text to a file before parsing it and post here so I can take a look at it?

**Comment by sez11a** [comment]
@vsch I disabled every extension except YamlFrontMatter and Aside and I still have the same problem. My code "imports" markdown into a Liferay application called Knowledge Base. I'm using YamlFrontMatter to store what we call a `header-id`, which is the URL to the converted file in the Knowledge Base. I can't disable YamlFrontMatter because the markdown won't import without it. (The `header-id` is just the first thing I want to use YamlFrontMatter for; I'm hoping later to implement auto-tagging from a list of tags in the header.)

**Comment by sez11a** [comment]
@vsch I figured out that it's not Flexmark at all; our code is calling some Sanitizer utility on the content before saving it to the database (which is stripping out the `<aside>` tags), so it's definitely my problem to solve. Thank you for your help, and I apologize for take up your time with this.

**Comment by vsch** [comment]
@sez11a, it usually is something mangling the text before the parser gets it. Something as straight forward as your case would have been caught by the unit, integration and myriad of formatter tests.

Let me know if you encounter difficulties with something else.
