### ISSUE TITLE
Github user extension incorrectly formats some text

### ISSUE THREAD

**Issue by maxcom** [vsch/flexmark-java#316]
I created my custom extension for parsing user mentions (like `@maxcom`). I looked at code of GfmUsersInlineParserExtension as source of ideas.

I found problem in my extension, and I think it exists in original GfmUsers extension too.

Extension highlights user mentions in text that contains email addresses like 'maxcom@somehost.net' or text like '1080p@60'. Github's own parser does not highlight users in that texts.

I think that extension should highlight user mention only when it comes after white space.

(original issue maxcom/lorsource#841)

**Comment by vsch** [comment]
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.
