### ISSUE TITLE
FlexmarkHtmlParser outputs extra newline when converting nested <ol>, <ul> lists

### ISSUE THREAD

**Issue by dmitrymurashenkov** [vsch/flexmark-java#317]
**Describe the bug** 

When converting nested html lists there is an extra line break outputed after nested list. This makes most .md renderers add a separate newline between all list lines when converting md back to html.

**To Reproduce**

```
String md = FlexmarkHtmlParser.parse(
        "<ol>\n" +
                "    <li>P1</li>\n" +
                "    <li>P2\n" +
                "        <ol>\n" +
                "            <li>P2-1</li>\n" +
                "        </ol>\n" +
                "    </li>\n" +
                "    <li>P3</li>\n" +
                "</ol>");
System.out.println(md);
```
Expected output:
```
1. P1
2. P2
   1. P2-1
3. P3
```

Actual output:
```
1. P1
2. P2
   1. P2-1

3. P3
```

**Comment by vsch** [comment]
@dmitrymurashenkov, thank you for catching it. I'll fix it for the next release.

**Comment by vsch** [comment]
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.
