### ISSUE TITLE
Example 'CustomContextDataSample' doesn't work

### ISSUE THREAD

**Issue by jvdvegt** [vsch/flexmark-java#319]
I'm trying to understand the possibilities of the flexmark-code, but I cannot find a decent manual with what tag are supported (Something along the lines of this https://rawgit.com/fletcher/MultiMarkdown-6-Syntax-Guide/master/index.html would be useful!). So I reverted to the example code.

But the code here: https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/CustomContextDataSample.java cannot possibly work. I see some link-manipulation going on, but nowhere will the suggested output 'This is <em>Sparta</em>' appear.

It looks like (some much needed) examples got mixed up?

Please provide as much information about where the but is located or what you were using:

* [ ] `Parser`
* [ ] `HtmlRenderer`
* [ ] `Formatter`
* [ ] `FlexmarkHtmlParser`
* [ ] `DocxRenderer`
* [ ] `PdfConverterExtension`
* [X] extension(s)

**To Reproduce**
See https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/CustomContextDataSample.java

**Comment by vsch** [comment]
@jvdvegt, you looked at an unfortunate sample which was for a very specific case and the comment with Sparta was left over from cut/paste.

flexmark-java is an extensible markdown parsing library so its markdown specification varies depending on the extensions and what the users decide to tweak in the options.

The specification for the core parser is [CommonMark (spec 0.28)] extensions are documented in general in [Extensions Wiki] with those that have more details providing a link to their own wiki pages:

* [Admonition-Extension](https://github.com/vsch/flexmark-java/wiki/ext/Admonition-Extension.md)
* [Attributes-Extension](https://github.com/vsch/flexmark-java/wiki/ext/Attributes-Extension.md)
* [Customizing-Docx-Rendering](https://github.com/vsch/flexmark-java/wiki/ext/Customizing-Docx-Rendering.md)
* [Definition-List-Extension](https://github.com/vsch/flexmark-java/wiki/ext/Definition-List-Extension.md)
* [Docx-Renderer-Extension](https://github.com/vsch/flexmark-java/wiki/ext/Docx-Renderer-Extension.md)
* [Enumerated-References-Extension](https://github.com/vsch/flexmark-java/wiki/ext/Enumerated-References-Extension.md)
* [Flexmark-Spec-Example-Extension](https://github.com/vsch/flexmark-java/wiki/ext/Flexmark-Spec-Example-Extension.md)
* [Footnotes-Extension](https://github.com/vsch/flexmark-java/wiki/ext/Footnotes-Extension.md)
* [Macros-Extension](https://github.com/vsch/flexmark-java/wiki/ext/Macros-Extension.md)
* [PDF-Renderer-Converter](https://github.com/vsch/flexmark-java/wiki/ext/PDF-Renderer-Converter.md)
* [Table-of-Contents-Extension](https://github.com/vsch/flexmark-java/wiki/ext/Table-of-Contents-Extension.md)
* [Tables-Extension](https://github.com/vsch/flexmark-java/wiki/ext/Tables-Extension.md)
* [Typographic-Extension](https://github.com/vsch/flexmark-java/wiki/ext/Typographic-Extension.md)

[CommonMark (spec 0.28)]: https://spec.commonmark.org/0.28
[Extensions Wiki]: file:///Users/vlad/src/projects/flexmark-java/flexmark-java.wiki/Extensions.md

[CommonMark (spec 0.28)]: https://spec.commonmark.org/0.28
[Extensions Wiki]: file:///Users/vlad/src/projects/flexmark-java/flexmark-java.wiki/Extensions.md
