### ISSUE TITLE
Change JRE requirement to Java 8 or above.

### ISSUE THREAD

**Issue by vsch** [vsch/flexmark-java#321]
I think it is time to stop Java 7 support to use Java 8 constructs in the code.

Versions before 0.50 will be the last Java 7 compatible releases in the master branch. 

Java 7 will fork to its own `Java7` branch with only bug fixes are planned in future releases.

Please comment here if this presents a problem or if you have ideas suggestions on this decision.

**Comment by slachiewicz** [comment]
What is the current minimum version of Java for 0.42.x code?

**Comment by vsch** [comment]
@slachiewicz, Java 7 is supported with the exception of 0.40.26 - 0.42.6 where PDF conversion was upgraded to OpenHtmlToPDF version 0.0.1-RC19 which is Java 8 byte codes. It was reverted in 0.42.8 to Java 7 compatible version of the library.

I will update the comment to reflect that Java 7 is supported before version 0.50.

**Comment by vsch** [comment]
Branch 0.50 merged into master.

Older version now in branch 0.42
