### ISSUE TITLE
Parse div block syntax

### ISSUE THREAD

**Issue by DaveJarvis** [vsch/flexmark-java#327]
Pandoc now has a [DIV](https://github.com/jgm/pandoc/issues/168#issuecomment-328690899) syntax for [content blocks](https://talk.commonmark.org/t/content-block-inline-syntax/815). For example:

``` markdown
::: homepage
![logo](images/logo.svg){width=120px height=120px} \

::: content
# Title
## Subtitle

[Contact](mailto:person@domain.com)
:::

:::
```

Using the latest version of Pandoc, the above produces:

``` html
<div class="homepage">
<p><img src="images/logo.svg" alt="logo" width="120" height="120" /><br />
</p>
<div class="content">
<h1>Title</h1>
<h2>Subtitle</h2>
<p><a href="mailto:person@domain.com">Contact</a></p>
</div>
</div>
```

This would be great to see in FlexMark as well.

**Comment by vsch** [comment]
@DaveJarvis, I will add it to the to do list but at the moment no PanDoc specific profile or extensions are implemented so it may take a while to add this extension along with other PanDoc specific ones.

**Comment by DaveJarvis** [comment]
Should anybody need this functionality, attached are a few classes that may help.

* [ClosingDivBlock.java.txt](https://github.com/vsch/flexmark-java/files/6080961/ClosingDivBlock.java.txt)
* [DivBlock.java.txt](https://github.com/vsch/flexmark-java/files/6080962/DivBlock.java.txt)
* [FencedDivExtension.java.txt](https://github.com/vsch/flexmark-java/files/6080963/FencedDivExtension.java.txt)
* [FencedDivRenderer.java.txt](https://github.com/vsch/flexmark-java/files/6080964/FencedDivRenderer.java.txt)
* [OpeningDivBlock.java.txt](https://github.com/vsch/flexmark-java/files/6080965/OpeningDivBlock.java.txt)

Here's a short example usage:

``` java
final var extensions = new ArrayList<Extension>();
extensions.add( FencedDivExtension.create() );

final IParse parser = Parser.builder().extensions( extensions ).build();
final IRender renderer = HtmlRenderer.builder().extensions( extensions ).build();
```

This solution works for nested fenced div elements, although it may be suboptimal because the opening and closing `div` elements are written separately, without knowledge of each other. If a Markdown document is missing the closing `:::` then the resulting HTML document will be missing a closing `div`.

If you have questions, you may be best off asking on StackOverflow.

**Comment by XenoAmess** [comment]
@DaveJarvis please add a pr...

**Comment by DaveJarvis** [comment]
@XenoAmess, a PR probably won't happen. If I were to make a flexmark extension at all, it'd be for parsing citations and cross-references, not for fenced DIVs. Here's the latest source code for fenced DIVs as is integrated into my text editor:

https://github.com/DaveJarvis/KeenWrite/tree/main/src/main/java/com/keenwrite/processors/markdown/extensions/fences
