### ISSUE TITLE
Add Macro support

### ISSUE THREAD

**Issue by vmassol** [vsch/flexmark-java#33]
See:

* https://github.com/vsch/flexmark-java/issues/28#issuecomment-269387630
* https://github.com/vsch/flexmark-java/issues/28#issuecomment-269500176
* https://github.com/vsch/flexmark-java/issues/28#issuecomment-269519040
* https://github.com/vsch/flexmark-java/issues/28#issuecomment-269533055

**Comment by vmassol** [comment]
About https://github.com/vsch/flexmark-java/issues/28#issuecomment-269533055:

* Cool that you're ok to add some macro support in flexmark-java
* Regarding the syntax I'm actually open to any syntax. The important part for XWiki are:
** Ability to have macros inline and at block level
** Ability to have content in the macro (on multiple lines too)
** Ability to specify parameters on the macro

Answering your questions:

>  I am not clear on how all these macros are used. All the macro syntax appears to be defining the
macro. Where and how do you expand the macro?

The way it works in XWiki Rendering, is described here: http://rendering.xwiki.org/xwiki/bin/view/Main/Architecture

In short:
* XWiki Parsers take some input text and convert them to an AST (called XDOM, it's a list of Block elements)
* Then Transformations execute. A transformation takes an XDOM as input and generates a modified XDOM. So we have a Macro Transformation that execute the Macro. Each Macro's execute() method return a List of Block, which replace the MacroBlock blocks in the original XDOM.

> If expansion is used on the content then what syntax is used for the parameter replacement in the body of the definition?

Not sure I understand the question.

The syntax of the content is completely Macro-dependent. The Macro completely owns its content which is seen as a black box from the Parser's POV.

> What does a macro without content do with its parameters? Is this a definition or an expansion
of it?

It's a definition (if I understand the terms correctly).

For example imagine the following macro using XWiki 2.1 Syntax: `{{rss url="..."/}}`. It doesn't have content, only parameters. It'll generate the Blocks to represent the RSS feed at a given URL.

>  I would even allow up to 3 spaces or whatever the processor family treats as non-indenting spaces

I'm fine with that too.

> Macro's should not be nested. Too difficult on the non-recursive parser but can be done

XWiki supports this.For example a Macro can generate other Macro Blocks. FYI, here's the implementation of our MacroTransformation: https://github.com/xwiki/xwiki-rendering/blob/master/xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/internal/transformation/macro/MacroTransformation.java

Now this shouldn't be a problem at al here since all I need to integrate flexmark-java is to be able to call `visit(Macro node)`and get a Macro object containing the macro definition. The rest is handled by XWiki.

> What are parameters used for?
> Are they replaced in the content?
> If they are, do they use {paramName} syntax? Other syntax?

The parameters are used in the java code for the Macro. In XWiki, a macro implements the Macro interface and the macro parameters are passed as java method parameters for the execute method (https://github.com/xwiki/xwiki-rendering/blob/master/xwiki-rendering-transformations/xwiki-rendering-transformation-macro/src/main/java/org/xwiki/rendering/macro/Macro.java):

    List<Block> execute(P parameters, String content, MacroTransformationContext context)
        throws MacroExecutionException;

> Is there a way to include a file that defines macros or do they need to be defined where used?

What we have in XWiki is an `include` macro to include markup defined in another page.

However for me all these questions are not important since all the logic corresponding to your questions should be handled in the Macro handling code and shouldn't have any effect on the parsing code. For me the parser should simply generate a Macro Node object and that's all. It's then up to the Macro handling code to do whatever it wants with a macro definition (or even do nothing if it doesn't support macros).

In this manner it's easy to add support for this in flexmark-java and then leave it to extenders to decide what to do with macro definitions.

WDYT?

**Comment by vsch** [comment]
@vmassol, I suspected it but wasn't sure. The macro capability you are referring to is not "stand-alone" allowing the user to define macros, then use them where he wants them expanded. 

What you are describing should really be called "FUNCTIONS" or system "MACROS", they serve no purpose without knowing how the end processor handles it.

Effectively, they become another mechanism for extending the Markdown processors without having to get into the guts and gore and deal only with the AST.

I was missing this little tit-bit to fully understand the uses. 

I can also see a use for a generic MACRO extension that will allow creating and expanding macros without needing to implement code for it, the extension will provide default behaviour. That way, repeated snippets of Markdown can be re-used, with customization parameters that are expanded in the text. My question about "expanding parameters" was referring to this type of use case.

I will give some thought to making the system MACRO facility highly independent from actual syntax in terms for openers, closers and internal parameter parsing. I will expose detail processing in the extension for implementors to handle/customize. I would like to make it as re-usable as possible and not married to any specific context as much as possible.

If I can combine the generic and system MACRO extension by making default extension behaviour implement generic macro facility with implementations capable of augmenting or overriding it, then that would be an ideal solution.

**Comment by vmassol** [comment]
> I can also see a use for a generic MACRO extension that will allow creating and expanding macros without needing to implement code for it, the extension will provide default behaviour. That way, repeated snippets of Markdown can be re-used, with customization parameters that are expanded in the text. My question about "expanding parameters" was referring to this type of use case.

Ok so we were using different terminology. What you describe is what I call "templates" :)

> I will give some thought to making the system MACRO facility highly independent from actual syntax in terms for openers, closers and internal parameter parsing. I will expose detail processing in the extension for implementors to handle/customize. I would like to make it as re-usable as possible and not married to any specific context as much as possible.

That's very fine with me.

> If I can combine the generic and system MACRO extension by making default extension behaviour implement generic macro facility with implementations capable of augmenting or overriding it, then that would be an ideal solution.

Sure. You could also consider them as 2 different features (since that's what they are in my view):
* Macros (generate a Macro Node/Block in the AST)
* Templates (just replace the template usage with the template definition, expanding parameters if any). Note that for templates (and as opposed to Macros) you need 2 syntaxes: one for defining the template and one for using it.

Thanks! Waiting for it since Macro is the last remaining bit before I can release a first version of the XWiki Markdown extension based on flexmark-java! :)

**Comment by vsch** [comment]
@vmassol, here is the overview for the macro module that I am working on. The AST will contain: MacroBlock, Macro, MacroClose and MacroAttribute. The latter is what you call parameter. MacroClose will represent `{{/macro}}` sequence if it exists.

flexmark-java extension for application specific macros

Macros come in two forms: block and inline. Block macros can include mutli-line content,
inluding blank lines. The content can contain other markdown elements and is parsed for inline
markdown content.

Inline macros can contain multi-line content but not blank lines because they are fully
contained in a single paragraph block.

Opening and closing block macro markers must be the first and last non-blank content on a line.
Other than this distinction there is no difference in handling macros by the extension between
inline and block macros. This means that inline macros will always be part of a paragraph block
content, even if the inline macro is the only content. If these inline macros are desired to be
processed as block macros then a node post processor should be used to transform these
paragraphs to block macros.

### Block Macros

```markdown
{{macroName attribute1=value attribute2 attribute3="value any content"}} 
content of the macro block, can include other block macros

blank lines and any other markdown element
{{/macroName}}
```

```markdown
{{macroName attribute3="value with possible spaces"}}content{{/macroName}}
```

Block Macros without content:

```markdown
{{macroName attribute1=value attribute2}}{{/macroName}}
```

```markdown
{{macroName attribute1=value attribute2 /}}
```

```markdown
{{macroName /}}
```

General form of an inline macro is the same as the block form except the opening and/or closing
marker has a blank or non-blank text prefix and/or non blank text suffix, or both opening and
closing markers are containted on the same line.

### Inline Macros:

A non-indenting space should be included before the opening and closing inline macro to prevent
it from being interpreted as a block macro.

:information_source: Non-indenting space below is replaced with `․`

```markdown
․{{macroName attribute4='another format'}} 
possibly containing other lines, but no blank lines 
․{{/macroName}}
```

```markdown
prefix text {{macroName attribute1=value}}
content possibly containing other lines, but no blank lines
lines {{/macroName}}
```

Single line inline macros:

```markdown
․{{macroName attribute3="value with possible spaces"}}content{{/macroName}}
```

Inline Macros without content:

```markdown
․{{macroName attribute1=value attribute2}}{{/macroName}}
```

```markdown
․{{macroName attribute1=value attribute2 /}}
```

```markdown
․{{macroName /}}
```

AST for block macro will start with the `Macro` node and if there was a closing marker then a
`MacroClose` will be the last child node.

Macro attributes, if any, are included as child blocks of the `Macro` node.

**Comment by vmassol** [comment]
This is awesome @vsch! :)

The only comment I have is about:

>  The content can contain other markdown elements and is parsed for inline
markdown content.

I hope that this is optional since in the XWiki case macros can contain anything (including content in other syntaxes) and it's up to the Macro code to parse its own content.

Thanks! I'm eager to try this out :)

**Comment by vsch** [comment]
@vmassol, the content will be parsed as Markdown but since default rendering of macro blocks or inline macros will do nothing it will have no effect unless you make use of it. 

For non-markdown content you can aways use the text between macro opening node and the macro closing node and ignore the markdown generated AST for the content. Since the offsets and original source is accessible from any node through any of the node's text attributes it should not be an issue. 

The implementation will put the macro attribute nodes, content and macro closing node as a children of the macro node that way the processing of macro content will be completely application dependent.

**Comment by vmassol** [comment]
ok good. The only issue is that parsing the macro content will cost more that if you don't parse them so it would be nice to at least have an option to not parse the content as MD content IMO. WDYT?

**Comment by vsch** [comment]
@vmassol, I will see if parsing can be disabled without side-effects but cannot guarantee it until I finalize the implementation. 

I would point out that if you are switching from pegdown the parsing time will not be significant because pegdown is parsing all input and doing so about 30-50x slower than flexmark. 😁

**Comment by vmassol** [comment]
> I would point out that if you are switching from pegdown the parsing time will not be significant because pegdown is parsing all input and doing so about 30-50x slower than flexmark. 😁

hehe... I haven't measured that yet but I believe you. One note though. I have a lot of unit tests and they each use a new flexmark parser. And I've found that the init time is now taking much longer than with pegdown. So overall the xwiki unit tests related to MD are most likely slower than before.

With reminds me a question I had: is the Parser thread safe? Can I reuse the same Parser object I get with `Parser parser = Parser.builder(options).build();` across threads?

Thanks

**Comment by vsch** [comment]
@vmassol, the parser does not store any state other than determined by options. The parse method creates a local variable for document parser and document node. I don't see why you would not be able to re-use the same parser for multiple inputs and across threads as long as it is done after the parser instance has fully been created before it is used in another thread for parsing.

**Comment by vsch** [comment]
@vmassol, `flexmark-ext-xwiki-macros` xwiki application specific macro extension, for now only
the block macros are implemented. Inline are treated as text.

For AST examples you can take a look at the test spec [xwiki_macro_ast_spec](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-xwiki-macros/src/test/resources/xwiki_macro_ast_spec.md)

**Comment by vsch** [comment]
@vmassol, inline macros added. Repo updated, maven updated but for some reason it takes a long time and sometimes the index does not get updated.

NOTE: changed default renderer for xwiki macro extension to render the macro as text so that if the app does not provide its own rendering then macros will be output as text.

**Comment by vmassol** [comment]
Awesome! I'll try to check this out in the afternoon today, thanks a lot.

**Comment by vmassol** [comment]
> Add: `flexmark-ext-xwiki-macros` xwiki application specific macro extension

wooohoo! This is even more than I expected :) Very nice treat! Thanks a lot.

I'm integrating it now.

**Comment by vmassol** [comment]
ok I have:

````
    public void visit(Macro node)
    {
        getListener().onMacro(String.valueOf(node.getName()), <parameters as a map here>, <content here>, <true if macro is inline or false otherwise>);        
    }
`````

I need to find out how to get the values in `<...>`: 
* the raw content inside the macro 
* the parameters. I know that I can use `visit(MacroAttribute node)` but is there any node/block I can visit and from which I can know for sure that the macro has been fully parsed and thus execute my ` getListener().onMacro()` call in it?
* if the macro is inline or block

Any idea of how I can get those?

Thanks

**Comment by vsch** [comment]
@vmassol, give me a few minutes and I will give you a code sample for these. I will also add these as methods on the Macro node.

**Comment by vmassol** [comment]
awesome

**Comment by vsch** [comment]
@vmassol, did not test but should work:

```java
package com.vladsch.flexmark.samples;

import com.vladsch.flexmark.ast.*;
import com.vladsch.flexmark.ext.xwiki.macros.*;
import com.vladsch.flexmark.html.HtmlRenderer;
import com.vladsch.flexmark.parser.Parser;
import com.vladsch.flexmark.util.options.MutableDataHolder;
import com.vladsch.flexmark.util.options.MutableDataSet;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

@SuppressWarnings({ "unchecked", "WeakerAccess" })
public class XWikiMacrosSample implements MacroVisitor {
    // Sample XWiki processing
    // NOTE: using raw text content of the node means that any nested macros will be taken as is
    // to handle nested macros would require more logic to allow nested macros to provide their content
    // to parent macros

    NodeVisitor visitor = new NodeVisitor(
            MacroVisitorExt.VISIT_HANDLERS(this)
    );

    @Override
    public void visit(final Macro node) {
        // collect attributes
        final Map<String, String> attributes = new HashMap<>();
        for (Node child : node.getChildren()) {
            if (child instanceof MacroAttribute) {
                MacroAttribute attribute = (MacroAttribute) child;
                attributes.put(attribute.getAttribute().toString(), attribute.getValue().toString());
            }
        }

        Node lastChild = node.getLastChild();
        int startOffset = node.getClosingMarker().getEndOffset();
        int endOffset = lastChild == null ? node.getEndOffset() : lastChild.getStartOffset();
        Node ancestor = node.getAncestorOfType(Paragraph.class, MacroBlock.class);

        String content = node.getChars().baseSubSequence(startOffset, endOffset).toString();
        boolean isBlock = ancestor instanceof MacroBlock;

        // use content, attributes, isBlock
    }

    @Override
    public void visit(final MacroClose node) {

    }

    @Override
    public void visit(final MacroBlock node) {
        visitor.visitChildren(node);
    }

    public static void main(String[] args) {
        MutableDataHolder options = new MutableDataSet();
        options.set(Parser.EXTENSIONS, Arrays.asList(MacroExtension.create()));

        Parser parser = Parser.builder(options).build();
        HtmlRenderer renderer = HtmlRenderer.builder(options).build();

        String markdown = "markdown content here";
        Node document = parser.parse(markdown);

        XWikiMacrosSample macroProcessor = new XWikiMacrosSample();
        macroProcessor.visitor.visitChildren(document);
    }
}
```

**Comment by vmassol** [comment]
Thanks. However, I think there's a problem because AFAIU when you have the following input:

````
{{mymacro param=value}}content{{/mymacro}}
````

Then the AST is: Macro, Text, MacroClose.

So if we're on the Macro node, then I won't be able to get the content since it's on the next sibling node and I need to find the next MacroClose node and compute what's between Macro and MacroClose.

Also your example code doesn't work for inputs such as `{{mymacro param=value /}}`. The end offset is less than the start offset. I'm still debugging that.

Thanks

**Comment by vsch** [comment]
@vmassol, just realized that the macro is only inline. MacroBlock has to handled separately. I will also address the issue you found.

**Comment by vmassol** [comment]
Ah yes I understand. I need to handle at the level of MacroBlock for block macros and at the level of Macro for inline macros.

**Comment by vsch** [comment]
@vmassol, split inline and block and also checking for `{{macro /}}`

```java
package com.vladsch.flexmark.samples;

import com.vladsch.flexmark.ast.*;
import com.vladsch.flexmark.ext.xwiki.macros.*;
import com.vladsch.flexmark.html.HtmlRenderer;
import com.vladsch.flexmark.parser.Parser;
import com.vladsch.flexmark.util.options.MutableDataHolder;
import com.vladsch.flexmark.util.options.MutableDataSet;
import com.vladsch.flexmark.util.sequence.BasedSequence;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

@SuppressWarnings({ "unchecked", "WeakerAccess" })
public class XWikiMacrosSample implements MacroVisitor {
    // Sample XWiki processing
    // NOTE: using raw text content of the node means that any nested macros will be taken as is
    // to handle nested macros would require more logic to allow nested macros to provide their content
    // to parent macros

    NodeVisitor visitor = new NodeVisitor(
            MacroVisitorExt.VISIT_HANDLERS(this)
    );

    @Override
    public void visit(final Macro node) {
        // collect attributes
        final Map<String, String> attributes = new HashMap<>();
        for (Node child : node.getChildren()) {
            if (child instanceof MacroAttribute) {
                MacroAttribute attribute = (MacroAttribute) child;
                attributes.put(attribute.getAttribute().toString(), attribute.getValue().toString());
            }
        }

        Node lastChild = node.getLastChild();
        int startOffset = node.getClosingMarker().getEndOffset();
        int endOffset = lastChild == null ? node.getEndOffset() : lastChild.getStartOffset();

        String content = node.getClosingMarker().length() > 2 ? "" : node.getChars().baseSubSequence(startOffset, endOffset).toString();
        boolean isBlock = false;

        // use content, attributes, isBlock
    }

    @Override
    public void visit(final MacroClose node) {

    }

    @Override
    public void visit(final MacroBlock node) {
        // collect attributes
        Node firstChild = node.getFirstChild();
        assert firstChild instanceof Macro;

        Macro macro = (Macro) firstChild;
        final Map<String, String> attributes = new HashMap<>();
        for (Node child : macro.getChildren()) {
            if (child instanceof MacroAttribute) {
                MacroAttribute attribute = (MacroAttribute) child;
                attributes.put(attribute.getAttribute().toString(), attribute.getValue().toString());
            }
        }

        Node lastChild = node.getLastChild();
        Node firstContentNode = firstChild.getNext();
        Node lastContentNode = lastChild instanceof MacroClose ? lastChild.getPrevious() : lastChild;

        BasedSequence contentChars = Node.spanningChars(firstContentNode == null || firstContentNode instanceof MacroClose ? BasedSequence.NULL : firstContentNode.getChars(),
                lastContentNode == null || lastContentNode instanceof Macro ? BasedSequence.NULL : lastContentNode.getChars());

        String content = contentChars.toString();
        boolean isBlock = true;

        // use content, attributes, isBlock
    }

    public static void main(String[] args) {
        MutableDataHolder options = new MutableDataSet();
        options.set(Parser.EXTENSIONS, Arrays.asList(MacroExtension.create()));

        Parser parser = Parser.builder(options).build();
        HtmlRenderer renderer = HtmlRenderer.builder(options).build();

        String markdown = "markdown content here";
        Node document = parser.parse(markdown);

        XWikiMacrosSample macroProcessor = new XWikiMacrosSample();
        macroProcessor.visitor.visitChildren(document);
    }
}
```

**Comment by vsch** [comment]
@vmassol, Changed test for `lastConentNode instanceof Macro` to `lastContentNode == firstChild` to allow for nested macros causing second to last node being a Macro node but not the first macro.

This code does not handle nested macros since the content is taken as text. Needs extra logic to allow for nested macros handling their own conversion to text. I don't know if this is needed or not.

**Comment by vmassol** [comment]
@vsch Thanks. I'm testing it. I don't understand one thing. With the following input:

````
{{testsimplemacro/}}

{{testsimplemacro param1=value1 param2=value2 /}}
````

I get Macro nodes when I was expecting MacroBlock nodes (i.e. those are block macros and not inline macros). 

> This code does not handle nested macros since the content is taken as text. Needs extra logic to allow for nested macros handling their own conversion to text. I don't know if this is needed or not.

No I don't need to handle nested macros. This is handled in XWiki itself where each macro executes and handles its own content.

**Comment by vsch** [comment]
@vmassol, if MacroBlock calls visitChildren() then Macro will be visited since it is the first child of a MacroBlock. To eliminate this put a test at the top of Macro visitor: 

`if (node.getParent() instanceof MacroBlock && node == node.getParent().getFirstChild()) return;`

I was lazy and re-used Macro instead of creating a different node for MacroBlock macro data.

**Comment by vsch** [comment]
@vmassol, found a bug for Macro handling caused when the last child is MacroAttribute.

need to change end offset to:

```java
        int endOffset = lastChild == null || lastChild instanceof MacroAttribute ? getEndOffset() : lastChild.getStartOffset();
```

I will be making a release now with added members to Macro nodes that simplify your implementation. Also added to AST tests output of new member methods so that these are part of the tests.

**Comment by vsch** [comment]
@vmassol, released update. With new methods the xwiki processing changes to:

```java
package com.vladsch.flexmark.samples;

import com.vladsch.flexmark.ast.*;
import com.vladsch.flexmark.ext.xwiki.macros.*;
import com.vladsch.flexmark.html.HtmlRenderer;
import com.vladsch.flexmark.parser.Parser;
import com.vladsch.flexmark.util.options.MutableDataHolder;
import com.vladsch.flexmark.util.options.MutableDataSet;
import com.vladsch.flexmark.util.sequence.BasedSequence;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

@SuppressWarnings({ "unchecked", "WeakerAccess" })
public class XWikiMacrosSample implements MacroVisitor {
    // Sample XWiki processing
    // NOTE: using raw text content of the node means that any nested macros will be taken as is
    // to handle nested macros would require more logic to allow nested macros to provide their content
    // to parent macros

    NodeVisitor visitor = new NodeVisitor(
            MacroVisitorExt.VISIT_HANDLERS(this)
    );

    @Override
    public void visit(final Macro node) {
        if (!node.isBlockMacro()) {
            // collect attributes
            final Map<String, String> attributes = node.getAttributes();
            String content = node.getMacroContentChars().toString();
            boolean isBlock = false;

            // use content, attributes, isBlock
        }
    }

    @Override
    public void visit(final MacroClose node) {

    }

    @Override
    public void visit(final MacroBlock node) {
        // collect attributes
        final Map<String, String> attributes = node.getAttributes();
        String content = node.getMacroContentChars().toString();
        boolean isBlock = true;

        // use content, attributes, isBlock
    }

    public static void main(String[] args) {
        MutableDataHolder options = new MutableDataSet();
        options.set(Parser.EXTENSIONS, Arrays.asList(MacroExtension.create()));

        Parser parser = Parser.builder(options).build();
        HtmlRenderer renderer = HtmlRenderer.builder(options).build();

        String markdown = "markdown content here";
        Node document = parser.parse(markdown);

        XWikiMacrosSample macroProcessor = new XWikiMacrosSample();
        macroProcessor.visitor.visitChildren(document);
    }
}
```

**Comment by vmassol** [comment]
@vsch That simplifies it a lot, thanks! :)

I'm now checking the full test suite for macros in XWiki. I have some issues but they're possibly on my side. I'll debug and raise any issue here.

Thanks again on your great help. Have a good week end!

**Comment by vmassol** [comment]
@vsch Ok I've finished adapting it to xwiki and it works fine! This is great. There's only 1 test failing and we need to decide if that's ok (and I need to remove this test) or if there's something to fix.

Here's the test:

````
.#-----------------------------------------------------
.input|markdown/1.2
.# Test proper pair matching of macro
.#-----------------------------------------------------
{{mymacro par1="val1" par2=2}}
{{/nomacro}} is not end
and even {{mymacro}} is just plain content
{{/mymacro}}

Markdown
{{/mymacro}}
.#-----------------------------------------------------
.expect|event/1.0
.#-----------------------------------------------------
beginDocument
onMacroStandalone [mymacro] [par1=val1|par2=2] [{{/nomacro}} is not end
and even {{mymacro}} is just plain content]
beginParagraph
onWord [Markdown]
onSpace
onSpecialSymbol [{]
onSpecialSymbol [{]
onSpecialSymbol [/]
onWord [mymacro]
onSpecialSymbol [}]
onSpecialSymbol [}]
endParagraph
endDocument
````

Let me know what you think. Thanks.

**Comment by vsch** [comment]
@vmassol, according to the "definition" the first `{{/mymacro}}` closes the macro block. To make it the closing of the inline `{{mymacro}}` there needs to be at least a space before the first `{{/mymacro}}` then it becomes syntactically correct for the new block/inline macros being the same except for the leading text/trailing non-whitespace text.

I would not delete the use case but would change it for the new syntax by adding a leading a space. BTW, this test uncovered a bug in the implementation that causes an index out of range when a closing macro element is rejected because of context. I will make a release with a fix now.

```markdown
{{mymacro par1="val1" par2=2}}
{{/nomacro}} is not end
and even {{mymacro}} is just plain content
 {{/mymacro}}

Markdown
{{/mymacro}}
```

The your test case is parsed as:

<img width="757" alt="screen shot 2017-01-21 at 12 24 31 pm" src="https://cloud.githubusercontent.com/assets/10299086/22176312/45c93ff0-dfd5-11e6-96bb-254aedb121e3.png">


While the corrected test case for the new syntax is parsed as expected:

<img width="756" alt="screen shot 2017-01-21 at 12 25 04 pm" src="https://cloud.githubusercontent.com/assets/10299086/22176313/49efc522-dfd5-11e6-9f15-55d4546d00ee.png">

**Comment by vsch** [comment]
@vmassol, new release with fix for the bug, version 0.11.8.

**Comment by vmassol** [comment]
Closing since it's working fine! Great work!

**Comment by vmassol** [comment]
Actually there's one problem: the order of the parameters is OS/VM-dependent. Do you think you could modify the code to use a LinkedHashMap instead of a HashMap so that the order of the parameters is fixed and thus when a macro is parsed and then rendered, it always render the parameters in the same order? :)

Thanks!

**Comment by vsch** [comment]
@vmassol, fixed and released. Version 0.12.0

**Comment by vmassol** [comment]
Thanks! Waiting for it to appear on http://repo2.maven.org/maven2/com/vladsch/flexmark/flexmark/

**Comment by vmassol** [comment]
ok it seems it's now available at https://repo.maven.apache.org/maven2/com/vladsch/flexmark/flexmark/0.12.0 but strangely the jar is not found : https://repo.maven.apache.org/maven2/com/vladsch/flexmark/flexmark/0.12.0/flexmark-0.12.0.jar

Not sure what's going on... :)

**Comment by vmassol** [comment]
ok seems it's available now...

**Comment by vsch** [comment]
@vmassol, you probably caught it as it was updating. I find Maven to be less than reliable, it seems to have grown to a difficult to manage size.
