### ISSUE TITLE
Ability to replace empty <p> with <br> during html2mark conversion

### ISSUE THREAD

**Issue by dmitrymurashenkov** [vsch/flexmark-java#331]
This is a typical case when converting html from rich text editor like TinyMCE to markdown. User presses enter key 2 times and gets 2 paragraphs in editor which visually look like several newlines in html:
```
<p>1</p>
<p></p>
<p>2</p>
```
We expect it to be processed similar to:
```
1<br><br><br>2
```
which gives:
```
1

<br />

2
```
but actual result is:
```
1

2
```
Note that in real case the empty `<p>` tag looks like this:
```
<p>&nbsp;</p>
```
So  strictly it is not empty, but is still omitted.

Options used:
```
MutableDataSet options = new MutableDataSet();
options.set(FlexmarkHtmlParser.OUTPUT_ATTRIBUTES_ID, false);
options.set(FlexmarkHtmlParser.THEMATIC_BREAK, "-------------------");
options.set(FlexmarkHtmlParser.SETEXT_HEADINGS, false);
options.set(FlexmarkHtmlParser.BR_AS_EXTRA_BLANK_LINES, true);
options.set(FlexmarkHtmlParser.BR_AS_PARA_BREAKS, true);
options.set(FlexmarkHtmlParser.DIV_AS_PARAGRAPH, true);
options.set(TableFormatOptions.FORMAT_TABLE_CAPTION, TableCaptionHandling.REMOVE);
```

**Comment by dmitrymurashenkov** [comment]
Found workaround for my particular case with nbsp in the empty paragraph:
```
options.set(FlexmarkHtmlParser.NBSP_TEXT, "&nbsp;");
```
This gives:
```
1

&nbsp;

2
```
Which is rendered as several blank lines too.

**Comment by vsch** [comment]
@dmitrymurashenkov, this is a bug of not implementing BR_AS_EXTRA_BLANK_LINES if the paragraph element is empty.

```````````````````````````````` example Issue 331: 1
1

<br />

2
.
<p>1</p>
<p></p>
<p>2</p>
````````````````````````````````

Release with the fix coming shortly.

**Comment by vsch** [comment]
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.
