### ISSUE TITLE
withOptions forgets about old link resolvers

### ISSUE THREAD

**Issue by Katrix** [vsch/flexmark-java#332]
**Describe the bug**
Might be that I'm using the library wrong, but I think the behavior of `HtmlRenderer#withOptions` changed at some point to not include the link resolvers of the old renderer.

Please provide as much information about where the but is located or what you were using:

* [ ] `Parser`
* [x] `HtmlRenderer`
* [ ] `Formatter`
* [ ] `FlexmarkHtmlParser`
* [ ] `DocxRenderer`
* [ ] `PdfConverterExtension`
* [ ] extension(s)

**To Reproduce**

Create a custom link resolver, and pass it to a `HtmlBuilder.Builder` instance. Later set some options using `withOptions`. The link resolver is now gone as the builder with an that takes both an old builder and more options don't set the custom Builder options for the new builder.

Here is a link to the source file where we use Flexmark and are having options.

Here we set the link resolver:
https://github.com/SpongePowered/Ore/blob/master/app/models/project/Page.scala#L199

Here we remove it by calling withOptions:
https://github.com/SpongePowered/Ore/blob/master/app/models/project/Page.scala#L220

Not really possible to show that the link resolver disappeared without using a debugger.

**Comment by vsch** [comment]
@Katrix, I will double check. It is possible since that part of the code was changed.

**Comment by vsch** [comment]
@Katrix, this actually never worked because builder state other than extensions and options were never inherited. 

Added transferring state between builders and unloading extensions to allow changing configured extension api points based on option changes.

This required a breaking change of moving `com.vladsch.flexmark.Extension` to `com.vladsch.flexmark.util.builder.Extension`

Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by vsch** [comment]
* Fix: IntelliJ Migration contained in [migrate flexmark-java 0_40_x to 0_42_0], to use:
  * copy to IntelliJ application settings to `migrations` subdirectory
  * if you have the project which you want to migrate open, then close it
  * open the project in IntelliJ Ultimate or Community
  * update the flexmark-java dependency version to 0.42.0 (or later) and make sure the new library is downloaded/updated in the project.
  * use menu `Refactor` > `Migrate...`
  * select `migrate flexmark-java 0.42.x to 0.50.0`
  * press `Run`
  * in the refactoring preview tool window that opens hit `Do Refactor`
