### ISSUE TITLE
Parsing lists without space between marker and item

### ISSUE THREAD

**Issue by Brassw** [vsch/flexmark-java#333]
Hi, I'm trying to setup parser in a way that lists without space between marker and item would be parsed as lists. Example input:

```
1.foo
2.bar
3.baz
*foo
*bar
*baz
```

I thought setting Parser.LISTS_ITEM_MARKER_SPACE = false mentioned in [List Parsing Options](https://github.com/vsch/flexmark-java/wiki/Extensions#list-parsing-options) would do the trick, and tried something similar to following code:

```
import com.vladsch.flexmark.html.HtmlRenderer;
import com.vladsch.flexmark.parser.Parser;
import com.vladsch.flexmark.util.ast.Node;
import com.vladsch.flexmark.util.options.MutableDataHolder;
import com.vladsch.flexmark.util.options.MutableDataSet;

public class ParserTesting {

    public static void main(String[] args) {
        MutableDataHolder options = new MutableDataSet();
        options.set(Parser.LISTS_ITEM_MARKER_SPACE, false);
        Parser parser = Parser.builder(options).build();
        HtmlRenderer renderer = HtmlRenderer.builder(options).build();

        String text = "1.foo\n"
                + "2.bar\n"
                + "3.baz\n"
                + "*foo\n"
                + "*bar\n"
                + "*baz";

        Node document = parser.parse(text);
        System.out.println(renderer.render(document));
    }
}

```
I expected it would produce following result:

```
<ol>
<li>foo</li>
<li>bar</li>
<li>baz</li>
</ol>
<ul>
<li>foo</li>
<li>bar</li>
<li>baz</li>
</ul>
```

However it produced this instead:

```
<p>1.foo
2.bar
3.baz
*foo
*bar
*baz</p>
```

Am I misunderstanding what Parser.LISTS_ITEM_MARKER_SPACE is intended for? Is there some way to achieve what I'm trying with Flexmark?

**Comment by vsch** [comment]
@Brassw, the space after the marker is not optional. 

The `Parser.LISTS_ITEM_MARKER_SPACE` only refers to empty items. In some parsers `* ` is a valid empty list item but `*` is not, while others treat both as valid items.

If you allow `*foo` to be a valid bullet item then text such as `*foo*` and `**foo**` will not be italic or bold text but a bullet list item.

**Comment by Brassw** [comment]
Thanks for your reply! Looking at the data I need parse, bullet lists are actually separated by space, while ordered lists are not. There is also a newline before each item in a list. 

Since configuration is not an option, I'll try to look how to extend Flexmark to support my scenario with least amount of new code. Parsing.LIST_ITEM_MARKER seems like a good starting point.
