### ISSUE TITLE
getLineNumber incorrect with Windows end of line separators

### ISSUE THREAD

**Issue by mattmook** [vsch/flexmark-java#338]
`Document.getLineNumber` assumes the end-of-line character is just one character wide and so on Windows Lin numbers are, effectively, doubled.

**To Reproduce**

Given the following we would expect the line number for the 7th character ('W') to return 1, however it returns 2:

```
Document document = new Document(new MutableDataSet(), BasedSequenceImpl.of("Hello\r\nWorld"));

document.getLineNumber(7) // should return 1
```

**Additional context**

I have created the PR https://github.com/vsch/flexmark-java/pull/339 to fix this issue

**Comment by vsch** [comment]
@mattmook, thank you for the PR and the report. I'll merge and release shortly.

**Comment by vsch** [comment]
@mattmook, I only changed the code to not treat offset between `\r\n` as part of the next line. So only offsets after complete EOL reflect next line number.

Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by mattmook** [comment]
Cool, many thanks
