### ISSUE TITLE
WRAP_AUTO_LINKS defaults to false, Markdown loses a potential useful link

### ISSUE THREAD

**Issue by gsora** [vsch/flexmark-java#348]
**Describe the bug**

Rendering HTML to Markdown using `FlexmarkHtmlParser.parse()` ignores anchors in which the `href` value equals the wrapped value, thus ignoring a potential useful link being generated.

* [ ] `Parser`
* [x] `HtmlRenderer`
* [ ] `Formatter`
* [ ] `FlexmarkHtmlParser`
* [ ] `DocxRenderer`
* [ ] `PdfConverterExtension`
* [ ] extension(s)

**To Reproduce**

This sample codes converts HTML to Markdown using the example approach detailed [here](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/HtmlToMarkdownSample.java):

```java
String originalText = "<p>This doesn't get rendered: <a href=\"https://google.com\" rel=\"nofollow\">https://google.com</a> <a href=\"https://google.com\" rel=\"nofollow\">This does.</a></p> \n";
String output = FlexmarkHtmlParser.parse(originalText);
```

**Expected behavior**: the first anchor should be rendered to a Markdown link.

**Resulting Output**: it just gets transformed to text.

**Additional context**: to fix this issue, the following approach has been employed:

```java
String originalText = "<p>This doesn't get rendered: <a href=\"https://google.com\" rel=\"nofollow\">https://google.com</a> <a href=\"https://google.com\" rel=\"nofollow\">This does.</a></p> \n";
String output = FlexmarkHtmlParser.parse(
                originalText,
                1,
                new MutableDataSet()
                        .set(FlexmarkHtmlParser.WRAP_AUTO_LINKS, true)
        );
```

Setting `FlexmarkHtmlParser.WRAP_AUTO_LINKS` to true renders the anchor successfully.

**Comment by vsch** [comment]
@gsora, WRAP_AUTO_LINKS controls whether links which look like auto-links, ie. the URL and link text match, get wrapped in `<>` or are left bare.

The bare links will be correctly interpreted as an auto-link when using the `flexmark-ext-autolink` extension.

I think it is a good idea to change the default for WRAP_AUTO_LINKS option to `true` but I will do this for version 0.50 which has many backward compatibility breaking changes. I do not want to introduce these breaking changes into the master branch.

**Comment by vsch** [comment]
@gsora, you can also remove auto-link conversion so all links convert to plain links by setting `EXTRACT_AUTO_LINKS` to false.

**Comment by gsora** [comment]
Thanks for your reply.

> The bare links will be correctly interpreted as an auto-link when using the flexmark-ext-autolink extension.

What's the recommended way to use `flexmark-ext-autolink` with  `FlexmarkHtmlParser`?

**Comment by vsch** [comment]
@gsora, the auto-link extension is a parser extension. 

It has a post-processor which scans all text elements in the AST after parsing looking for anything that looks like a valid URI.

It is actually slow for large files (2x to 3x slower parsing) so if you do not need unwrapped auto-links then I would recommend not using it but instead set WRAP_AUTO_LINKS to true for HTML to markdown conversion.

If you do want plain auto-links recognized in markdown files then you should include the `AutolinkExtension.create()` in your parser options `EXTENSIONS` list option.
