### ISSUE TITLE
Is there any special format requirement for processing html data to markdown

### ISSUE THREAD

**Issue by fwk1010** [vsch/flexmark-java#351]
Please provide as much information about where the but is located or what you were using:

* [ ] `Parser`
* [ ] `HtmlRenderer`
* [ ] `Formatter`
* [x] `FlexmarkHtmlParser`
* [ ] `DocxRenderer`
* [ ] `PdfConverterExtension`
* [ ] extension(s)

**Input text used** 
There was a standard and common html and I used <code>FlexmarkHtmlParser.parse(htmlContent)</code> to handle data without any options.
```html
<!doctype html>
<html>
<head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
</head>
<body>
<div class="container logo-search">
    <div class="col search row-search-mobile">
        <form action="index.html">
            <input autocomplete="off" class="placeholder" name="s" placeholder="search">
        </form>
    </div>
    <div class="row">
        <div class="col logo">
            <h1><a href="/">test</a></h1>
        </div>
        <div class="col right-list">
            <button class="btn btn-responsive-nav btn-inverse" data-target=".nav-main-collapse" data-toggle="collapse"
                    id="pull" style=""><i class="fa fa-navicon"></i></button>
        </div>
        <div class="col search search-desktop last">
            <form action="#last" target="_blank">
                <input autocomplete="off" class="placeholder" id="s" name="s" placeholder="search">
            </form>
        </div>
    </div>
</div>
</body>
</html>
```
**Expected behavior**
To out Markdown content like
```markdown
[test](/)
```
**Resulting Output** 
```java
java.lang.ArrayIndexOutOfBoundsException: -1

	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at com.vladsch.flexmark.util.html.LineFormattingAppendableImpl.getLineContents(LineFormattingAppendableImpl.java:602)
```
Is there any special format requirement for processing html data to markdown? I just know the one use case through [flexmark-java-samples](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/HtmlToMarkdownSample.java). 

How can I get more information about to make html to markdown? Thanks.

**Comment by vsch** [comment]
@fwk1010, it is a bug that has now been fixed. Thank you for catching this.

Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by fwk1010** [comment]
@vsch Grateful ! It works.I will close this issue.
