### ISSUE TITLE
how to make title without number

### ISSUE THREAD

**Issue by ArthurZgx** [vsch/flexmark-java#356]
how to make pdf file'title without number;
like this
![image](https://user-images.githubusercontent.com/34998960/61445224-8e02ce00-a97f-11e9-80b4-ab6a594507ff.png)

**Comment by ArthurZgx** [comment]
my code
   @Test
    public void testHtml() throws IOException {
        MutableDataHolder OPTIONS = PegdownOptionsAdapter.flexmarkOptions(
                Extensions.ALL & ~(Extensions.ANCHORLINKS | Extensions.EXTANCHORLINKS_WRAP)
                , TocExtension.create()).toMutable()
                .set(TocExtension.LIST_CLASS, PdfConverterExtension.DEFAULT_TOC_LIST_CLASS);
        InputStream stream = new FileInputStream("/Users/arthur/Desktop/test1.html");

        String htmlContent = IOUtils.toString(stream, "UTF-8");
        PdfConverterExtension.exportToPdf("/Users/arthur/project/ops/upload/report/report_monthly.pdf", htmlContent, "", OPTIONS);
    }

**Comment by vsch** [comment]
@ArthurZgx, the extension uses its resource `/default.css` to define the default CSS string option `DEFAULT_CSS`. You can override this option with anything you like including a blank string which will not provide any style defaults and remove the legal numbering from headings.

**Comment by ArthurZgx** [comment]
oh,I see...     Thank you very much.

**Comment by ArthurZgx** [comment]
problem solved
thank you again!
`/* Table of contents */
@media print {
    .toc a::after {
        content: leader('. ') target-counter(attr(href), page) '.';
    }
}

.toc li { display: block }
ol.toc li:first-child { counter-reset: l1 }
ol.toc li li:first-child { counter-reset: l2; }
ol.toc li li li:first-child { counter-reset: l3 }
ol.toc li li li li:first-child { counter-reset: l4 }

ol.toc li:before {}
ol.toc li li:before {}
ol.toc li li li:before {}
ol.toc li li li li:before {}

/* Heading numbers */
body {counter-reset: h2}
h2 {counter-reset: h3}
h3 {counter-reset: h4}
h4 {counter-reset: h5}
h5 {counter-reset: h6}

h2:before {}
h3:before {}
h4:before {}
h5:before {}
h6:before {}

.nocount:before { content: ""; counter-increment: none }
`

**Comment by sungmore** [comment]
你好，请问你可以将解决方法描述详细点吗？我在工程下没有找到CSS文件，具体解决步骤是什么样的呢

**Comment by vsch** [comment]
@sungmore, see examples of adding CSS by using `style` tag added in code.

[PdfLandscapeConverter.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/PdfLandscapeConverter.java)  
[PdfConverter.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/PdfConverter.java)

If you have the CSS as a resource in your application you can set `PdfConverterExtension.DEFAULT_CSS_RESOURCE_PATH` string to the path of the resource. 

PDF Converter uses `PdfConverterExtension.DEFAULT_CSS` string. So you can set it to your CSS if you want to completely override it. By default this will be the content of resource defined by`PdfConverterExtension.DEFAULT_CSS_RESOURCE_PATH`

**Comment by sungmore** [comment]
I want to deploy the project on the was server, and I want each user to download the PDF to their own computer, but I find that the export command is encapsulated. What should I do?

**Comment by zhangziqiang1** [comment]
String html = FileUtils.readFileToString(file, "utf-8");
            final DataHolder OPTIONS = PegdownOptionsAdapter.flexmarkOptions(
                    Extensions.ALL & ~(Extensions.ANCHORLINKS | Extensions.EXTANCHORLINKS_WRAP)
                    , TocExtension.create()).toMutable()
                    .set(PdfConverterExtension.DEFAULT_CSS, "")  // overwriting
                    .toImmutable();
