### ISSUE TITLE
Will markdown2html function support scratch? 

### ISSUE THREAD

**Issue by mercraft** [vsch/flexmark-java#358]
I am using Parser to parse markdown to html. However, I find that it will not support "Scratch" in markdown to change to html.

**To Reproduce**
When type \~\~toDelete\~\~
It will result in \<p\>\~\~toDelete\~\~\</p\> whose expected result is \<del\>toDelete\</del\>

If you can please provide sample code which exhibits the issue. This is always best because it incorporates a testable morsel which includes all relevant information.

```
public class Markdown2HtmlUtils {
    public static String markdown2Html(String markdownContent){
        MutableDataSet options = new MutableDataSet();
        options.setFrom(ParserEmulationProfile.MARKDOWN);

        // enable table parse!
        options.set(Parser.EXTENSIONS, Arrays.asList(TablesExtension.create()));

        Parser parser = Parser.builder(options).build();
        HtmlRenderer renderer = HtmlRenderer.builder(options).build();

        Node document = parser.parse(markdownContent);
        return renderer.render(document);
    }


    public static void main (String[] args) {
        String sb = "~~ToDelete~~";
        System.out.println(Markdown2HtmlUtils.markdown2Html(sb));
    }

}
```

**Comment by vsch** [comment]
@mercraft, the strike through syntax is an extension to markdown so you need to add `StrikethroughExtension` from the `flexmark-ext-gfm-strikethrough` module to your extension list. See: [GitHubParsingSample.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/GitHubParsingSample.java)

**Comment by mercraft** [comment]
Thanks @vsch ! This really works and a nice demo!
