### ISSUE TITLE
I added flexmark-java to CommonMark wiki (list of Implementations)

### ISSUE THREAD

**Issue by juanmirocks** [vsch/flexmark-java#360]
Not an issue, but just FYI (I hope you are OK with this).

I added **flexmark-java** to https://github.com/commonmark/commonmark-spec/wiki/List-of-CommonMark-Implementations#java

Commit: https://github.com/commonmark/commonmark-spec/wiki/List-of-CommonMark-Implementations/6817b58a221dfe8c61620b7a90e9db1d5f220991

THANK YOU for this AWESOME library!

**Comment by vsch** [comment]
@juanmirocks, thank you. I completely forgot about listing it.

**Comment by juanmirocks** [comment]
You deserved it. Closing now.
