### ISSUE TITLE
table does not render correctly

### ISSUE THREAD

**Issue by frostblazergit** [vsch/flexmark-java#365]
**Describe the bug** A clear and concise description of what the bug is.

Feel free to remove any sections that do not apply or add your own to clarify your issue.

Please provide as much information about where the but is located or what you were using:

* [x] `Parser`
* [x] `HtmlRenderer`
* [ ] `Formatter`
* [ ] `FlexmarkHtmlParser`
* [ ] `DocxRenderer`
* [ ] `PdfConverterExtension`
* [x] extension(s)

**To Reproduce**

If you can please provide sample code which exhibits the issue. This is always best because it incorporates a testable morsel which includes all relevant information.

java code:

```java
MutableDataSet options = new MutableDataSet().set(Parser.EXTENSIONS, Arrays.asList(
                AutolinkExtension.create(),
                EmojiExtension.create(),
                StrikethroughExtension.create(),
                TaskListExtension.create(),
                TablesExtension.create()
        ))
                // set GitHub table parsing options
                .set(TablesExtension.WITH_CAPTION, false)
                .set(TablesExtension.COLUMN_SPANS, false)
                .set(TablesExtension.MIN_HEADER_ROWS, 1)
                .set(TablesExtension.MAX_HEADER_ROWS, 1)
                .set(TablesExtension.APPEND_MISSING_COLUMNS, true)
                .set(TablesExtension.DISCARD_EXTRA_COLUMNS, true)
                .set(TablesExtension.HEADER_SEPARATOR_COLUMN_MATCH, true)

                // setup emoji shortcut options
                // uncomment and change to your image directory for emoji images if you have it setup
                //.set(EmojiExtension.ROOT_IMAGE_PATH, emojiInstallDirectory())
                .set(EmojiExtension.USE_SHORTCUT_TYPE, EmojiShortcutType.GITHUB)
                .set(EmojiExtension.USE_IMAGE_TYPE, EmojiImageType.IMAGE_ONLY)
                // other options
                ;

        // uncomment to convert soft-breaks to hard breaks like GitHub comments
        //options.set(HtmlRenderer.SOFT_BREAK, "<br />\n");

        Parser parser = Parser.builder(options).build();
        HtmlRenderer renderer = HtmlRenderer.builder(options).build();

        // You can re-use parser and renderer instances
        Node document = parser.parse(markdown);// markdown file
        String html = renderer.render(document);
```

markdown file:

```
name|age
-|-
Tom|23
Jack|25


```

Or a link to a sample code file.

**If a code sample is not possible please provide as much of the following information as you can :**

1. **Input text used** Please provide a sample of text which causes the issue.

   ```
   sample
   ```

   Or provide a link to a file

2. Options used to configure the parser, renderer, formatter, etc. Please provide concise code when you can.

**Expected behavior** A clear and concise description of what you expected to happen with sample output that would be desired, where it makes sense.

**Resulting Output** It is best to provide one of the following (in decreasing order of value):

- text results,
- file links,
- screenshots are least useful but better than nothing.

**Additional context** Add any other context about the problem here.

**Comment by vsch** [comment]
@frostblazergit, minimum dashes for a table separator column is 3.

If you want shorter ones to be recognized you need to `.set(TablesExtension.MIN_SEPARATOR_DASHES, 1)` in your options.

**Comment by frostblazergit** [comment]
@vsch 
Thank you very much! I should not rely on the wiki without checking the source code.

The wiki is a bit outdated, but it's not a big deal. 😊

https://github.com/vsch/flexmark-java/wiki/Tables-Extension

**Comment by vsch** [comment]
@frostblazergit, I forgot to add the new options to the extension wiki. Thank you for bringing it to my attention. I will update them.

**Comment by vsch** [comment]
@frostblazergit, wiki updated. Thank you for letting me know.
