### ISSUE TITLE
How to add attribute 'class' to AutoLink node

### ISSUE THREAD

**Issue by steveluo** [vsch/flexmark-java#37]
Hi, 
I'm new to flexmark. And this is not a bug report. I just want to get some help here:

1.  How to add 'class' attribute to AutoLink node? 
2. Is it possible to configure FlexMark to render ```\n``` as ```<br/>```, for example, FlexMark now renders below markdown:
```markdown
hello
world
```
to:
```html
<p>hello\nworld</p>
```
I want to get below html instead:
```html
<p>hello<br/>world</p>
```

Thanks in advance.

**Comment by vsch** [comment]
@steveluo,

1. You need to implement an AttributeProvider, here is a sample which I will add to `flexmark-java-samples` on the next release:

   ```java
   package com.vladsch.flexmark.samples;

   import com.vladsch.flexmark.Extension;
   import com.vladsch.flexmark.ast.AutoLink;
   import com.vladsch.flexmark.ast.FencedCodeBlock;
   import com.vladsch.flexmark.ast.Node;
   import com.vladsch.flexmark.ext.autolink.AutolinkExtension;
   import com.vladsch.flexmark.html.*;
   import com.vladsch.flexmark.html.renderer.AttributablePart;
   import com.vladsch.flexmark.html.renderer.CoreNodeRenderer;
   import com.vladsch.flexmark.html.renderer.LinkStatus;
   import com.vladsch.flexmark.html.renderer.NodeRendererContext;
   import com.vladsch.flexmark.parser.Parser;
   import com.vladsch.flexmark.util.html.Attribute;
   import com.vladsch.flexmark.util.html.Attributes;
   import com.vladsch.flexmark.util.options.MutableDataHolder;
   import com.vladsch.flexmark.util.options.MutableDataSet;

   import java.util.Arrays;
   import java.util.Collections;

   public class AttributeProviderSample {
       static class SampleExtension implements HtmlRenderer.HtmlRendererExtension {
           @Override
           public void rendererOptions(final MutableDataHolder options) {
               // add any configuration settings to options you want to apply to everything, here
           }

           @Override
           public void extend(final HtmlRenderer.Builder rendererBuilder, final String rendererType) {
               rendererBuilder.attributeProviderFactory(SampleAttributeProvider.Factory());
           }

           static SampleExtension create() {
               return new SampleExtension();
           }
       }

       static class SampleAttributeProvider implements AttributeProvider {
           @Override
           public void setAttributes(final Node node, final AttributablePart part, final Attributes attributes) {
               if (node instanceof AutoLink && part == AttributablePart.LINK) {
                   // Put info in custom attribute instead
                   attributes.replaceValue("class", "my-autolink-class");
               }
           }

           static AttributeProviderFactory Factory() {
               return new IndependentAttributeProviderFactory() {
                   @Override
                   public AttributeProvider create(NodeRendererContext context) {
                       //noinspection ReturnOfInnerClass
                       return new SampleAttributeProvider();
                   }
               };
           }
       }

       static String commonMark(String markdown) {
           MutableDataHolder options = new MutableDataSet();
           options.set(Parser.EXTENSIONS, Arrays.asList(new Extension[] { AutolinkExtension.create(), SampleExtension.create() }));
        
           // change soft break to hard break
           options.set(HtmlRenderer.SOFT_BREAK, "<br/>");    
        
           Parser parser = Parser.builder(options).build();
           Node document = parser.parse(markdown);
           HtmlRenderer renderer = HtmlRenderer.builder(options).build();
           final String html = renderer.render(document);
           return html;
       }

       public static void main(String[] args) {
           String html = commonMark("http://github.com/vsch/flexmark-java");
           System.out.println(html); // output: <p><a href="http://github.com/vsch/flexmark-java" class="my-autolink-class">http://github.com/vsch/flexmark-java</a></p>
       }
   }

   ```
   
2. This is done by setting your own value for `HtmlRenderer.SOFT_BREAK` value as done in above sample with the line:

   ```
   options.set(HtmlRenderer.SOFT_BREAK, "<br/>");    
   ```

**Comment by steveluo** [comment]
@vsch Thank you so much for the prompt reply!

I have tested with your solution, AutoLink with class can work, but SOFT_BREAK can't.
I still got ```\n``` instead of ```<br />```. Anything I missed here?

And, when I test AutoLink solution, I find that below link can't convert to AutoLink node, maybe this is a bug?

```
https://google.com/abc?hello=456&world=789
```

It seems that auto link fails when link contains ```&```.

Again, thank you very much for this amazing library!

**Comment by vsch** [comment]
@steveluo, the & is probably a bug. I will test the AutoLink extension.

For the soft break are you using the sample code (which does work) or your own? If your own can you post the code here so I can double check it. You are probably not passing the option to html renderer builder.

**Comment by vsch** [comment]
@steveluo, I confirm that it is a bug in auto link. I will fix it and make a release.

**Comment by steveluo** [comment]
@vsch Thank you so much!

Below is what I did (just like your snippet):

```java
         MutableDataHolder options = new MutableDataSet();
        options.set(Parser.EXTENSIONS, Arrays.asList(new Extension[] { AutolinkExtension.create() }));
        // change soft break to hard break
        options.set(HtmlRenderer.SOFT_BREAK, "<br/>");

        Parser parser = Parser.builder(options).build();
        String raw = "hello\nworld";
        Node document = parser.parse(raw);
        HtmlRenderer renderer = HtmlRenderer.builder().extensions(getExtensions()).build();
        String html = renderer.render(document);
        System.out.println(html);
```

Still got:
```
hello\nworld
```

**Comment by vsch** [comment]
@steveluo, you are not passing the options to `HtmlRenderer.builder()`

Change to:

```java
        HtmlRenderer renderer = HtmlRenderer.builder(options).extensions(getExtensions()).build();
```

**Comment by steveluo** [comment]
@vsch  Oh, yes! So sorry!

And thank you very much! It worked now like a charm!

**Comment by vsch** [comment]
@steveluo, actually change to:

```java
        HtmlRenderer renderer = HtmlRenderer.builder(options).build();
```

Extensions are also passed via options. I will probably remove all the non-option based builder methods that are left-over from commonmark-java which does not have a universal API for configuration.

**Comment by vsch** [comment]
@steveluo, don't be sorry. It takes a bit of time to adjust your thinking to the API. I know it took some time for me.

**Comment by steveluo** [comment]
😄 , yes, I'm just converting my Pegdown code to FlexMark. And I need a bit time to learn! Fortunately, your support is so amazing!

**Comment by vsch** [comment]
@steveluo, thank you. I made the journey myself. I can assure you that it is well worth the effort.

**Comment by vsch** [comment]
@steveluo, repo updated, maven released with fix for autolink with ampersand fix.

**Comment by steveluo** [comment]
@vsch Wow, you are amazing! I have confirmed that the #38 is fixed. Thank you!

**Comment by mirfatif** [comment]
@vsch sorry to interrupt you. This is not a big problem but hard to digest. :smile: 

`This is Sparta` becomes `<p>This is Sparta</p>\n`. The last character in the source string is `a`, so it marks the end of `p` tag. We get `<p>This is Sparta</p>`.

From where does the trailing `\n` come?
Is there a way to get rid of this (except `.replaceFirst("\\n$", "")`)?

I looked into README and wiki but can't figure it out.

Thanks.
