### ISSUE TITLE
How to handle code snippets can be highlighted with css

### ISSUE THREAD

**Issue by Jack1477** [vsch/flexmark-java#371]
Sorry, my english is noob . I want to implement the following features.

markdown -> html

i will be 
``````
```java
void render(N node, NodeFormatterContext context, MarkdownWriter markdown);
```
``````

convert to

```
<td id="LC7" class="blob-code blob-code-inner js-file-line">    
  <span class="pl-k">void</span> 
  <span class="pl-en">render</span>
  (
  <span class="pl-smi">N</span> 
  <span class="pl-v">node</span>
  , 
  <span class="pl-smi">NodeFormatterContext</span>
  <span class="pl-v">context</span>
  , 
  <span class="pl-smi">MarkdownWriter</span>
   <span class="pl-v">markdown</span>);
</td>
```

Like github, i want use the style to achieve highlighting, please tell me how to do.
(Sorry , It seems that my English expression is terrible.)

**Comment by Jack1477** [comment]
@vsch

**Comment by vsch** [comment]
@Jack1477, you need to provide a custom node renderer for fenced code blocks where based on the fenced code info string (the language string) you will have to parse the text content and generate the HTML.

GitLab extension module adds custom fenced code handling so it is the best place to look: [flexmark-ext-gitlab](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-gitlab)

You can also see [#205, How create wrapper for PlantUML in markdown?]

This library does not parse contents of fenced code or do any syntax highlighting. This is left to JavaScript libraries which can be added to the rendered HTML to handle.

[#205, How create wrapper for PlantUML in markdown?]: https://github.com/vsch/flexmark-java/issues/205

**Comment by Jack1477** [comment]
Thank you for your prompt reply, this is very helpful to me.
