### ISSUE TITLE
[Regression?] Attributes extension not applied to `code` tag of code blocks

### ISSUE THREAD

**Issue by cjbrooks12** [vsch/flexmark-java#372]
**Describe the bug**

In 0.42.12, attributes added with the Attributes Extension were applied to both the `pre` and `code` elements of code blocks. In 0.50.40, the same Markdown seems to only apply the attributes to the `pre` element, and I can't seem to find a way to get them applied to the inner `code` element.

This is a problem, as there is no way to apply additional attributes to code blocks in such a way that Javascript selectors can use them (such as for configuring a JS-based syntax highlighter). For example, the typical selector for finding code blocks of a particular language from Markdown is something like `pre code[class='language-run-kotlin']`, selecting the inner `code` element, but the configuration attributes are not available to the element that is selected.

* [X] `Parser`
* [X] `HtmlRenderer`
* [ ] `Formatter`
* [ ] `FlexmarkHtmlParser`
* [ ] `DocxRenderer`
* [ ] `PdfConverterExtension`
* [X] Attributes extension (using default options)

**To Reproduce**

In 0.42.12, the following snippet would apply the attributes to both the 

    ```run-kotlin
    fun main() {
        println("Running from Kotlin Playground!")
    }
    ```
    {theme='darcula' lines='true'}

**Expected behavior** 

Attributes are applied to both the `pre` and `code` elements, to be compatible with the 0.42.12 version. The following snippet is how the sample input above was rendered on 0.42.12.

```html
<pre theme="darcula" lines="true"><code class="language-run-kotlin" theme="darcula" lines="true">fun main() {
   println(&quot;Running from Kotlin Playground!&quot;)
}
</code></pre>
```

**Resulting Output** 

Attributes are only applied to the `pre` element, which is incompatible with 0.42.12. The following snippet is how the sample input above is rendered on 0.50.40.

```html
<pre theme="darcula" lines="true"><code class="language-run-kotlin">fun main() {
    println(&quot;Running from Kotlin Playground!&quot;)
}
</code></pre>
```

**Comment by vsch** [comment]
@cjbrooks12, thank you for the catch.

Yes, I broke it by adding ability to add attributes after the info string for my plugin. https://github.com/vsch/idea-multimarkdown/issues/760

I will add an option to generate it with attributes after info, by default to fall back to 0.42.12.

**Comment by vsch** [comment]
@cjbrooks12, as often happens, there is already a setting `AttributesExtension.FENCED_CODE_INFO_ATTRIBUTES` and it is set to `true` by default. I will change it to `false` in the next release.

As a workaround if you explicitly set `AttributesExtension.FENCED_CODE_INFO_ATTRIBUTES` to `false` in your parser/renderer options you will get old behaviour, which was to set attributes on the `pre` tag not `code` tag.

**Comment by cjbrooks12** [comment]
I think that option is different. It seems to change how attributes are parsed when they're in the _first_ line of the code fence but doesn't change anything when the attributes list is _immediately after_ the code fence. And it doesn't change whether or not the attributes are applied to the `code` tag within `pre`. To match the previous behavior, the parsed attributes should be applied to both the `pre` and `code` tags. Currently, they are only ever applied to `pre`.

**Comment by vsch** [comment]
@cjbrooks12, my bad. I did not realize that I "corrected" the fenced code attributes to only add them to the outer tag `<pre>`.  This branch had no fenced code tests for attributes so I could not tell at a glance if I changed it. I added a test and saw the change.

I will fix it in 0.5.0 for backward compatibility and add an option to choose whether to add it to `pre`, `code` or both.

**Comment by vsch** [comment]
@cjbrooks12, 
Fix for this is available. Repo updated branch **0.50**, maven updated but may take a while to show up in maven central.

* Add: `AttributesExtension.FENCED_CODE_ADD_ATTRIBUTES`, default `FencedCodeAddType.ADD_TO_PRE_CODE` for backward compatibility with 0.42, but if this is option is not set and `AttributesExtension.FENCED_CODE_INFO_ATTRIBUTES` is set to `true`, default will change to `FencedCodeAddType.ADD_TO_PRE` since attributes after info are used to add to the `code` tag.

**Comment by cjbrooks12** [comment]
Just tried it out, it's working great. Thanks for the help!
