### ISSUE TITLE
convert markdown to html

### ISSUE THREAD

**Issue by AmberNew** [vsch/flexmark-java#376]
Hi:
i convert markdown to html, if markown content contain character *, there are some unexpected results after converted. example:
input:    "test1|test2|test3|test4|test5|test6\n" +
                ":------:|:------:|:------:|:------:|:------:|:------:|:------:\n" +
                "1*1 | 1*1|1 |3.8%|40.6|523|78\n" +
                "1*10|1*10|24 |82.7%|72.3|360|1134.1";
output:  <table>...<tr><td align="center">1<em>1 | 1</em>1</td><td align="center">1 </td><td align="center">3.8%</td><td align="center">40.6</td><td align="center">523</td><td align="center">78</td></tr>...</table>

private String markdown2Html() throws IOException {
        DataHolder OPTIONS = PegdownOptionsAdapter.flexmarkOptions(true,
                Extensions.ALL
        );

        String mdContent = "test1|test2|test3|test4|test5|test6\n" +
                ":------:|:------:|:------:|:------:|:------:|:------:|:------:\n" +
                "1*1 | 1*1|1 |3.8%|40.6|523|78\n" +
                "1*10|1*10|24 |82.7%|72.3|360|1134.1";
        System.out.println(mdContent);
        Parser parser = Parser.builder(OPTIONS).build();
        HtmlRenderer renderer = HtmlRenderer.builder(OPTIONS).build();

        Node document = parser.parse(mdContent);
        System.out.println(renderer.render(document));
        return renderer.render(document);
    }

**Comment by vsch** [comment]
@AmberNew, thank you for bringing it to my attention. It looks like a bug. I will look into it, but parser seems to give priority to emphasis before pipes.

For now the only thing to do is to add space around `*` to prevent it from being used as an emphasis delimiter or escape it `\*`

**Comment by AmberNew** [comment]
> 
> 
> @AmberNew, thank you for bringing it to my attention. It looks like a bug. I will look into it, but parser seems to give priority to emphasis before pipes.
> 
> For now the only thing to do is to add space around `*` to prevent it from being used as an emphasis delimiter or escape it `\*`

thank you for your answer, may be it's a bug, it works when using pegedown to convert that.

       String mdContent = "test1|test2|test3|test4|test5|test6\n" +
            ":------:|:------:|:------:|:------:|:------:|:------:|:------:\n" +
            "1*1 | 1*1|1 |3.8%|40.6|523|78\n" +
            "1*10|1*10|24 |82.7%|72.3|360|1134.1";
        PegDownProcessor pdp = new PegDownProcessor(Integer.MAX_VALUE);
        System.out.println(pdp.markdownToHtml(mdContent.toString()));

**Comment by vsch** [comment]
@AmberNew, it is a bug and I have a good idea where it is caused and why. Inline delimiter processing is not taking special conditions for table cell parsing. I'll fix it and make a release.

**Comment by vsch** [comment]
@AmberNew, branch 0.50 was updated with the fix.

Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.
