### ISSUE TITLE
HeadingParser doesn't include trailing whitespace

### ISSUE THREAD

**Issue by saket** [vsch/flexmark-java#377]
The `HeadingParser` trims trailing whitespace characters, resulting in "# Hello " getting parsed as a `Heading("# Hello")` node. I'm not sure if this intentional, but I am doing some calculations when rendering heading nodes and this is resulting in incorrect renderings where the text length doesn't match the node's end offset. Will it be possible to not skip whitespace characters?

Please provide as much information about where the but is located or what you were using:

* [x] `Parser`

**Comment by vsch** [comment]
@saket, `Heading.getText()` returns only the text used for rendering the heading, it does not include leading/trailing spaces or leading/trailing markers `#`. Not only trailing spaces but any trailing spaces followed by one or more `#` are also excluded.

![image](https://user-images.githubusercontent.com/10299086/69499504-bddb5880-0ec0-11ea-9185-a7443e154be3.png)

This is part of the [CommonMark (spec 0.28)] so the parser is implemented correctly.

You need to add logic to your code to handle the variety of headings it can encounter.

If you need the text which includes all trailing characters then for a heading node `heading` use `heading.getChars().baseSubSequence(heading.getText().getStartOffset(), heading.getChars().getEndOffset())` which will give you the heading text starting with the first non-space after the markers and extending to all characters, excluding the EOL at the end of the line, which is not part of the heading node element.

[CommonMark (spec 0.28)]: https://spec.commonmark.org/0.28

**Comment by saket** [comment]
Got it. I assumed it might be the intended behavior as per the spec. Thank you for confirming!
