### ISSUE TITLE
convert markdown to html

### ISSUE THREAD

**Issue by AmberNew** [vsch/flexmark-java#378]
it does work if markdown content like this:
 ### ok
head1|head2|head3|head4
:------:|:------:|:------:|:------:
1|2|3|4
1|2|3|4
but it doesn't work if there are some content in the previous row of the table,for example,markdown content like this:
 ### error
some content....
head1|head2|head3|head4
:------:|:------:|:------:|:------:
1|2|3|4
1|2|3|4

my code:
DataHolder OPTIONS = PegdownOptionsAdapter.flexmarkOptions(true, Extensions.ALL);
Parser parser = Parser.builder(OPTIONS).build();
HtmlRenderer renderer = HtmlRenderer.builder(OPTIONS).build();
 String mdContent = "some content....\n" +
"test1|test2|test3|test4|test5|test6\n" +
":------:|:------:|:------:|:------:|:------:|:------:|:------:\n" +
"1*1 | 1*1|1 |3.8%|40.6|523|78\n" +
 "1*10|1*10|24 |82.7%|72.3|360|1134.1";
Node document = parser.parse(mdContent.toString());
System.out.println((renderer.render(document)));

After convert, it becomes a p tag, not a table
output: 
<p>some content on the top of table<br />
test1|test2|test3|test4|test5|test6<br />
:&mdash;&mdash;:|:&mdash;&mdash;:|:&mdash;&mdash;:|:&mdash;&mdash;:|:&mdash;&mdash;:|:&mdash;&mdash;:|:&mdash;&mdash;:<br />
1<em>1 | 1</em>1|1 |3.8%|40.6|523|78<br />
1<em>10|1</em>10|24 |82.7%|72.3|360|1134.1</p>

**Comment by vsch** [comment]
@AmberNew, works as designed.

[flexmark-ext-tables/src/main/javadoc overview](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-tables/src/main/javadoc/overview.md)

> **Extension for tables using "|" pipes with optional spanning columns and table caption**
>
> Converts table elements of the form:
>
> ```markdown
>
> |    Heading Centered    | Heading Left Aligned   |  Heading Centered  |   Heading Right Aligned |
> |------------------------|:-----------------------|:------------------:|------------------------:|
> | Cell text left aligned | Cell text left aligned | Cell text centered | Cell text right aligned |
> | cell 21                | cell 22                |      cell 22       |                 cell 22 |
>
> ```
>
> Depending on the specified option tables may have multiple header rows, number of columns in table body does not need to match header or separator line columns and column spans can be specified by adding consecutive `|` at the end of the cell. Each pipe represents column span count `||` spans two columns, `|||` three, etc.
>
> Additionally, missing columns may be either left as is or filled in with empty elements.
>
> When column span syntax is enabled, empty table cells must have at least one space. Otherwise they will be interpreted as column spans for the previous cell.
>
> :warning: Table elements must be preceded by a blank line to be processed by this extension.
