### ISSUE TITLE
Is there an option for number of whitespaces needed to create sub-lists?

### ISSUE THREAD

**Issue by andersHj** [vsch/flexmark-java#382]
Hi, I want to move from Pegdown to Flexmark. I am testing it now and I have some problems with nested lists, seems Flexmark accepts 2 to 5 whitespaces , while pegdown accepts 4 to 7 whitespaces to create a sublist:

With this input: 
```
- [ ] Main item
      - [ ] sub item prefixed with 6 spaces
```

I will get this result:
![image](https://user-images.githubusercontent.com/2843210/71257821-fb52ca80-2334-11ea-925c-9d42d6e84a16.png)

So I am wondering if there is an option to allow for up to 7 whitespaces in flexmark to get the same result as in pegdown (since we have a lot of markdown stored in db on "pegdown" format.)?

**Comment by vsch** [comment]
Are you not using the `PegdownOptionsAdapter` to select parser options based on pegdown Extensions? If you look at the code in the implementation, it selects pegdown profile which among other things sets the indentation to fixed 4 spaces.

The profile you are describing fits CommonMark and other non-fixed indentations.

See: https://github.com/vsch/flexmark-java#pegdown-migration-helper

**Comment by andersHj** [comment]
You are right, for some reason I tried without this `PegdownOptionsAdapter`. 
Using the `PegdownOptionsAdapter` fixes the main issues (now behaves similar for 0-7 spaces). However when using 8 spaces for sub items it will render differently (but I do not think that is a big problem for us since we tell our users to use 4 spaces). Anyway here is an example of differences:

Input:
```
* [ ] Main item
        * [ ] Sub item indented by **8 spaces**
```
Output:
![image](https://user-images.githubusercontent.com/2843210/71809723-f732e680-3070-11ea-96de-f77e7f5ecaca.png)

Thanks for your help and a great library!

**Comment by andersHj** [comment]
I have another issue with this input: 

```
* [ ] First item
* [ ] Second item


* [ ] Third item separated by 2 newlines
```

In flexmark it renders the third item as a child of the second item and also for some reason makes it bold:
![image](https://user-images.githubusercontent.com/2843210/71974170-15cfe380-3211-11ea-989f-6c45920aec3c.png)

**Comment by vsch** [comment]
@andersHj, can you extract your parser/renderer creation code with parse/render of the markdown input and post it here as a snippet of code that duplicates this. 

What you are describing is strange and I cannot duplicate it so it must depend on some specific option combinations you are using.

**Comment by vsch** [comment]
@andersHj, the 8 space indentation not being converted to lazy continuation is a bug. Thank you for catching it.

I fixed it in the 0.60 branch and will add the fix to 0.50 and make a new release.

**Comment by vsch** [comment]
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.

**Comment by andersHj** [comment]
Thanks! 👍  (I have been pretty busy lately so did not get the time to test this yet, so sorry for slow response)

**Comment by vsch** [comment]
@andersHj, no problem. If the fix does not work, please re-open the issue.
