### ISSUE TITLE
Not  support markdown line-through

### ISSUE THREAD

**Issue by shalousun** [vsch/flexmark-java#383]
convert markdown to html，not support line through text in markdown file.

**Comment by vsch** [comment]
@shalousun, can you please give an example of what you are trying to do?

A short snippet of code with your parser, renderer setup and the markdown source you are using would allow me to test your case and provide corrections.

**Comment by shalousun** [comment]
Usage:
```
/**
     * Convert markdown to html.
     *
     * @param content markdown contents
     * @return html contents
     */
    public static String toHtml(String content) {
        MutableDataSet options = new MutableDataSet();
        options.setFrom(ParserEmulationProfile.MARKDOWN);
        // enable table parse!
        options.set(Parser.EXTENSIONS, Arrays.asList(TablesExtension.create()));

        Parser parser = Parser.builder(options).build();
        HtmlRenderer renderer = HtmlRenderer.builder(options).build();

        Node document = parser.parse(content);
        return renderer.render(document);
    }
```
markdown 
```
### ~~Test apiNote tag~~
**URL:** http://127.0.0.1/test

**Type:** POST

**Author:** cht

**Content-Type:** application/x-www-form-urlencoded;charset=utf-8
```

**Comment by vsch** [comment]
@shalousun, the strike-through syntax is not standard Markdown and is implemented in the `StrikethroughExtension`, add `StrikethroughExtension.create()` to your list of extensions and it should work as you expect.

Basic markdown has only the basic CommonMark core elements, for everything else you need to use the corresponding extensions.
