### ISSUE TITLE
Disable parsing of sub-lists

### ISSUE THREAD

**Issue by saket** [vsch/flexmark-java#394]
**Is your feature request related to a problem? Please describe.** 
Is it possible to disable parsing of sub-lists? Adding extra margin in an editable WYSIWYG text field is resulting in double margins because the text already contains spaces.

**Describe the solution you'd like**
I'd like to treat this block as a single list block instead of two nested blocks:
```
- Milk
- Drinks
  - Coke
  - Pepsi
```

Apologies if this is already possible, but I was unable to find the right `Parser.*` options.

**Comment by vsch** [comment]
@saket, list parsing is intricate and not easily changed except when using a different emulation profile which defines number of spaces used for a sub-item indentation. 

If you use FIXED_INDENT profile then sub-list items will require 4 spaces for sub-item indentation. You can also change the `Parser.LISTS_ITEM_INDENT` to something >4, but disabling it completely is not supported.

You can achieve the effect of not having sub-lists by writing a `NodePostProcessor` which will run after the document is parsed. In it you can move list items from a sub-list to the parent list and remove the empty list node. You can also apply logic on when to do this, so it can be fairly flexible. 

Be warned. Lists are a PITA to deal with there are lots of gotchas and your code will need a lot of testing.

See `flexmark-java-samples` for post processor examples and https://github.com/vsch/flexmark-java/wiki/Writing-Extensions for overview of parser phases and customization API points.

**Comment by saket** [comment]
> If you use FIXED_INDENT profile then sub-list items will require 4 spaces for sub-item indentation. You can also change the Parser.LISTS_ITEM_INDENT to something >4, but disabling it completely is not supported.

Hey this seems to work and my parsed documents look exactly the same. I know the default options are different, but the visual result is the same for common markdown syntaxes. This might be a good option with `Parser.LISTS_ITEM_INDENT` set to `Integer.MAX_VALUE`.

I was trying out another alternative. What do you think of this condition in my node visitor?

```kotlin
val isSubList = child is ListBlock && child.parent is ListItem
if (isSubList.not()) {
  val visitor = highlighters.nodeVisitor(child)
  visitor.visit(child, pool, writer)
}
```

> You can achieve the effect of not having sub-lists by writing a NodePostProcessor which will run after the document is parsed. In it you can move list items from a sub-list to the parent list and remove the empty list node. You can also apply logic on when to do this, so it can be fairly flexible.
> 
> Be warned. Lists are a PITA to deal with there are lots of gotchas and your code will need a lot of testing.

Gotcha, I'm going to stay away from this to avoid dealing with gotchas.

**Comment by vsch** [comment]
@saket, the condition is correct to detect if a list is a direct child of a list item. 

It is also possible to have a sub-list in an intervening block element, such as a block quote. I am not sure if you want to handle these differently:

```markdown
* list item

  > * sub-list item
```

**Comment by saket** [comment]
Got it, will handle that case. Thank you so much!
