### ISSUE TITLE
DocumentParser stops reading too early resulting in the document being cut off

### ISSUE THREAD

**Issue by dzholmukhanov** [vsch/flexmark-java#396]
The `if` condition inside `while` loop in [DocumentParser:331](https://github.com/vsch/flexmark-java/blob/9719ed1923b5601439455976b3cfdcad1ad3f92e/flexmark/src/main/java/com/vladsch/flexmark/parser/internal/DocumentParser.java#L331) is incorrect because it assumes that it reached the end of the reader if less number of bytes was read than `buffer.length`. When in fact it is guaranteed only if `-1` was returned according to the official documentation.

The documentation for [Reader.read(char[] cbuf, int off, int len)](https://docs.oracle.com/javase/7/docs/api/java/io/Reader.html#read(char[],%20int,%20int)) says: 

> len - Maximum number of characters to read

> Returns: The number of characters read, or -1 if the end of the stream has been reached

And for [Reader.read(char[] cbuf)](https://docs.oracle.com/javase/7/docs/api/java/io/Reader.html#read(char[])) it says:

> Returns: The number of characters read, or -1 if the end of the stream has been reached

I think they mean that an attempt is made to read as many bytes as `len`, but a smaller number may be read. Both methods are called when [this line](https://github.com/vsch/flexmark-java/blob/9719ed1923b5601439455976b3cfdcad1ad3f92e/flexmark/src/main/java/com/vladsch/flexmark/parser/internal/DocumentParser.java#L327) executes. It is not guaranteed that Reader will always return `buffer.length` even if there are that many bytes.

I stumbled upon this problem when I was using `org.glassfish.jersey.client.internal.HttpUrlConnector` wrapped into `InputStreamReader`. Sometimes it wasn't returning `buffer.length` number of bytes. This was resulting in the document being cut off very frequently.

I found this issue while debugging when after this line executed: `if (charsRead < buffer.length) break;`, I called `bufferedReader.read(buffer);` one more time and saw that it was able read additional bytes.

**Comment by vsch** [comment]
@dzholmukhanov, thank you for catching it. I will fix it and make a new release.

It makes sense that the bug would show up on an HTTP connection.

**Comment by dzholmukhanov** [comment]
@vsch Great. Thank you!

**Comment by vsch** [comment]
Fix for this is available. Repo updated, maven updated but may take a while to show up in maven central.
