### ISSUE TITLE
Which JAR should I import？

### ISSUE THREAD

**Issue by sungmore** [vsch/flexmark-java#399]
hello,when I use the project as  https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/PdfConverter.java#L161 , I import the JAR as follows :
`<dependency>
    <groupId>com.vladsch.flexmark</groupId>
    <artifactId>flexmark-all</artifactId>
    <version>0.61.16</version>
</dependency>`
But when I pack the project,I found it is to big.  So which JAR should I import? and how  should I write in maven? Thanks~

**Comment by vsch** [comment]
@sungmore, the PDF converter depends on HtmlToPDF library, which has a lot of dependencies.

The flexmark module also depends on most of the extensions.

In my project, core and all the modules including PDF, results in a JAR of about 2MB.

I am not a maven expert, but do you also include dependencies in your project JAR?, in this case all the dependencies, not just flexmark jars are included.

**Comment by sungmore** [comment]
> @sungmore, the PDF converter depends on HtmlToPDF library, which has a lot of dependencies.
> 
> The flexmark module also depends on most of the extensions.
> 
> In my project, core and all the modules including PDF, results in a JAR of about 2MB.
> 
> I am not a maven expert, but do you also include dependencies in your project JAR?, in this case all the dependencies, not just flexmark jars are included.

**Comment by sungmore** [comment]
> @sungmore, the PDF converter depends on HtmlToPDF library, which has a lot of dependencies.
> 
> The flexmark module also depends on most of the extensions.
> 
> In my project, core and all the modules including PDF, results in a JAR of about 2MB.
> 
> I am not a maven expert, but do you also include dependencies in your project JAR?, in this case all the dependencies, not just flexmark jars are included.

thanks。 Another question：How to add watermark to PDF exported by https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/PdfConverter.java#L161
