### ISSUE TITLE
watermarking the pdf

### ISSUE THREAD

**Issue by sungmore** [vsch/flexmark-java#400]
Do you support watermarking on exported PDF？

**Comment by sungmore** [comment]
https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/PdfConverter.java#L161
`PdfConverterExtension.exportToPdf("/Users/vlad/src/pdf/flexmark-java.pdf", html, "", OPTIONS);
`

**Comment by vsch** [comment]
@sungmore, the PDF renderer is a thing wrapper around the HtmlToPdf library. It is indented only as a convenience for basic conversion.

If you require greater control over the PDF rendering it is probably easier to implement your own copy of [PdfConverterExtension.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-pdf-converter/src/main/java/com/vladsch/flexmark/pdf/converter/PdfConverterExtension.java) and change it to use the full features of the HtmlToPdf library for your project.

The extension is 150 lines of code so there is not much to its functionality.

**Comment by sungmore** [comment]
> @sungmore, the PDF renderer is a thing wrapper around the HtmlToPdf library. It is indented only as a convenience for basic conversion.
> 
> If you require greater control over the PDF rendering it is probably easier to implement your own copy of [PdfConverterExtension.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-pdf-converter/src/main/java/com/vladsch/flexmark/pdf/converter/PdfConverterExtension.java) and change it to use the full features of the HtmlToPdf library for your project.
> 
> The extension is 150 lines of code so there is not much to its functionality.

Thanks，sorry for another question:  if I want to create PDF stream to web. How should I do on
` public static void exportToPdf(OutputStream os, String html, String url, PdfRendererBuilder.TextDirection defaultTextDirection, ProtectionPolicy protectionPolicy) {
        PdfBoxRenderer renderer = null;
        try {
            // There are more options on the builder than shown below.
            PdfRendererBuilder builder = new PdfRendererBuilder();

            handleTextDirection(defaultTextDirection, builder);
            handleW3cDocument(html, url, builder);

            builder.toStream(os);
            renderer = builder.buildPdfRenderer();
            PDDocument document = renderer.getPdfDocument();

            if (protectionPolicy != null)
                document.protect(protectionPolicy);

            renderer.layout();
            renderer.createPDF();
        } catch (Exception e) {
            e.printStackTrace();
            // LOG exception
        } finally {
            try {
                if (renderer != null) {
                    renderer.close();
                }
                os.close();
            } catch (IOException e) {
                // swallow
            }
        }
    }`
