### ISSUE TITLE
how to use Formatter and htmlRender together?

### ISSUE THREAD

**Issue by simonjhy** [vsch/flexmark-java#403]
**Is your feature request related to a problem? Please describe.** 
I want to convert markdown to html and use it in offline mode. So I also want to replace the html link to local file refernce.

**Describe the solution you'd like**
I found the htmlRender and formatter inherit from Render interface.

**Describe alternatives you've considered**
Is there a solution to make markdown convert to html and replace html link to local file reference at the same time.

**Additional context**

**Comment by vsch** [comment]
@simonjhy, you do not need a Formatter if you only need HTML rendering.

You should look into implementing your own `LinkResolver` which will examine and modify links for HTML rendering. Link resolver is used to convert the URL in markdown to the URL used in rendering.

[LinkResolver.java](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/html/LinkResolver.java)

Some samples which use it:

[CustomContextDataSample.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/CustomContextDataSample.java)  
[CustomLinkResolverSample.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/CustomLinkResolverSample.java)  
[PegdownCustomLinkResolverOptions.java](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/PegdownCustomLinkResolverOptions.java)

**Comment by simonjhy** [comment]
thanks your suggestion

**Comment by DaveJarvis** [comment]
@simonjhy, if you're satisfied with the answer, please close the ticket.
