### ISSUE TITLE
Is there a way to get the complete AST printed out?

### ISSUE THREAD

**Issue by tedneward** [vsch/flexmark-java#417]
I would prefer to not have to write a Visitor that walks every node and prints out what it finds, and seeing the complete dump of the AST at times is helpful to understand how the parser is picking things apart. Does such a thing already exist? (I've not found it.)

**Comment by vsch** [comment]
@tedneward, I use `AstCollectingVisitor`:

```
        System.out.println(new AstCollectingVisitor().collectAndGetAstText(document));
```

Where `document` is the node, with children which you want to dump to text.

**Comment by DaveJarvis** [comment]
@tedneward, if @vsch's answer is satisfactory, please close this ticket.

**Comment by tedneward** [comment]
The AstCollectingVisitor is definitely what I was looking for, the only thing I'd suggest adding somewhere is a reference to which package it's in (com.vladsch.flexmark.test) and that it's part of the flexmark-test module/library, not part of the core parser itself. That was the only struggle I had after getting this response. Thanks!

**Comment by tedneward** [comment]
I would suggest documenting how to use the AstCollectingVisitor in documentation somewhere, as it could be very useful during debugging and other diagnostic tools.
