### ISSUE TITLE
How to set font?

### ISSUE THREAD

**Issue by Clay-Ferguson** [vsch/flexmark-java#423]
I'm starting with markdown and rendering to PDF. I have it working, but I can't figure out how to set a specific font family. 

Is there a way to set the font?  

Here's the code I'm using:

```
Parser parser = Parser.builder(options).build();
HtmlRenderer renderer = HtmlRenderer.builder(options).build();

Node document = parser.parse(markdown.toString());
String html = renderer.render(document);
html = PdfConverterExtension.embedCss(html, "body {font-family: 'Verdana';}");
out = new FileOutputStream(new File(fullFileName));
PdfConverterExtension.exportToPdf(out, html, "", options);
```

The Verdana font is definitely in the html, but gets ignored by the PDF converter.

**Comment by Clay-Ferguson** [comment]
I figured it out:

```
```

**Comment by ndtreviv** [comment]
Are you hosting the ttf font file, then? What is `constProvider`?

I want to read the font in from the classpath and call `setFont` like I do on `PdfRendererBuilder`, but can't work it out?
