### ISSUE TITLE
Combining bold and italics does not always work

### ISSUE THREAD

**Issue by andersHj** [vsch/flexmark-java#426]
**Edit**: I see that it is the same issue when testing in the commonmark online editor:
https://spec.commonmark.org/dingus/?text=**This%20should%20be%20bold_combined%20with%20italics_**%0A%0A__This%20should%20be%20bold*combined%20with%20italics*__%0A%0A**This%20should%20be%20bold%20_combined%20with%20italics_**%0A%0A

-------------

Hi, combining bold and italics does not work in one case when using `**` for bold and `_` for italics:

`**This should be bold_combined with italics_**` 
But it will not be italics here. It renders:
`<p><strong>This should be bold_combined with italics_</strong></p>`

If adding a space before the first underscore it works:
`**This should be bold _combined with italics_**` 

It also works when switching to use `__` for bold and `*` for italics:
`__This should be bold*combined with italics*__`

**To Reproduce**

```
import com.vladsch.flexmark.html.HtmlRenderer;
import com.vladsch.flexmark.parser.Parser;
import com.vladsch.flexmark.profile.pegdown.Extensions;
import com.vladsch.flexmark.profile.pegdown.PegdownOptionsAdapter;
import com.vladsch.flexmark.util.data.DataHolder;

public class MarkdownParserTest {
    private final static int PEGDOWN_EXTENSIONS = Extensions.AUTOLINKS; // Just so it won't be empty
    
    private static final DataHolder OPTIONS = PegdownOptionsAdapter.flexmarkOptions(
        PEGDOWN_EXTENSIONS
    );

    public static Parser PARSER = Parser.builder(OPTIONS).build();
    public static HtmlRenderer htmlRenderer = HtmlRenderer.builder(OPTIONS).build();

    public static String getHtml(String markdownString) {
        return htmlRenderer.render(PARSER.parse(markdownString));
    }

    public static void main(String[] args) {
        // Space before underscore: Works
        String ok1 = "**This should be bold _combined with italics_**"; 
        System.out.println(MarkdownParserTest.getHtml(ok1));
        // Output: 
        // <p><strong>This should be bold <em>combined with italics</em></strong></p>
        
        // No space before underscore: Fails
        String failing = "**This should be bold_combined with italics_**"; 
        System.out.println(MarkdownParserTest.getHtml(failing));
        // Output: 
        // <p><strong>This should be bold_combined with italics_</strong></p>

        // Switching to use underscore for bold and * for italics: Works
        String ok2 = "__This should be bold*combined with italics*__";
        System.out.println(MarkdownParserTest.getHtml(ok2));
        // Output:
        // <p><strong>This should be bold<em>combined with italics</em></strong></p>
    }
}
```

**Comment by DaveJarvis** [comment]
The behaviour is correct:

![bold-italics](https://user-images.githubusercontent.com/2131950/103502729-03c65800-4e07-11eb-8c87-1721f53f8a1e.png)

Underscores can be used to link words in software development, such as the_names_of_variables. That's one reason why underscores need to be separated by non-alphanumeric characters (spaces, punctuation).

You have a few options. As shown in the image, you can use single asterisks to accomplish the task. Or you can create your own extension to specifically check for this case. As this library stands, though, it is a correct implementation of the Markdown specification.
