### ISSUE TITLE
question: how to parse latex formula by using GitLab Flavoured Markdown extension?

### ISSUE THREAD

**Issue by zc-BEAR** [vsch/flexmark-java#428]
I use the following code to add GitLab Flavoured Markdown extension.
```java
DataHolder OPTIONS = new MutableDataSet()
                .set(Parser.EXTENSIONS, Arrays.asList(TablesExtension.create(), GitLabExtension.create( )))
                .toImmutable();
```
But I can't parse my math formula from markdown to html.
It still like :
```html
<p>$Math =\sum$</p>
```
Where could I find the details of how to use this extension?

**Comment by DaveJarvis** [comment]
My application contains a TeX processor that converts a math formula from Markdown to SVG, embedded inside HTML. Here's an example approach to that should provide a few details on how to go about this, @zc-BEAR:

https://github.com/DaveJarvis/keenwrite/tree/master/src/main/java/com/keenwrite/processors/markdown/extensions/tex
