### ISSUE TITLE
Out of date documentation for Pegdown Migration Helper

### ISSUE THREAD

**Issue by bhagany** [vsch/flexmark-java#43]
I'm trying to follow this: https://github.com/vsch/flexmark-java#pegdown-migration-helper.  However, I don't see the `flexmark-profile-pegdown` module in maven here: https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.vladsch.flexmark%22, and the pom for that module seems like it's kind of old (https://github.com/vsch/flexmark-java/blob/master/flexmark-profile-pegdown/pom.xml) because it references `flexmark-java` version `0.8.0`.  Is there a new way to accomplish Pegdown emulation that's not in the README?

**Comment by vsch** [comment]
@bhagany, I missed that `flexmark-profile-pegdown` was not in the project pom. It's version was not being updated.

I will make a corrected release shortly with a fix for this omission.

**Comment by vsch** [comment]
@bhagany, you can always grab the source for this file from this repo: https://github.com/vsch/flexmark-java/blob/master/flexmark-profile-pegdown/src/main/java/com/vladsch/flexmark/profiles/pegdown/PegdownOptionsAdapter.java, 

it is a single file that you may want to customize instead of using it as is.

**Comment by bhagany** [comment]
Ah, great, thanks! Copying the source was going to be the next thing I tried, but I'm using `flex mark-java` from clojure, and I'm not sure how much of a pain that will be. I'll just wait for your new release, thanks again!

**Comment by vsch** [comment]
@bhagany, repo updated, Maven released but may take time to have central index updated.
