### ISSUE TITLE
Why is " a unsafe character?

### ISSUE THREAD

**Issue by reisi007** [vsch/flexmark-java#435]
Hi,

Regarding the following source snippets:

https://github.com/vsch/flexmark-java/blob/c0313d67e0146292a10d04eb8944faff991579e9/flexmark-util-sequence/src/main/java/com/vladsch/flexmark/util/sequence/Escaping.java#L43-L45

https://github.com/vsch/flexmark-java/blob/c0313d67e0146292a10d04eb8944faff991579e9/flexmark-util-sequence/src/main/java/com/vladsch/flexmark/util/sequence/Escaping.java#L64-L78

Why is the `"` character is considered unsafe in the following context?

My usecase: I am processing Markdown, which is then processed using velocity. I rely on the fact that `"` is outputted as `"` and not as `&quot;`.

I am parsing the following line of markdown (which is a function call in velocity)

    $object.myfun("myString")

**Expected**: 

    $object.myfun("myString")
**Actual**:

    $object.myfun(&quot;myString&quot;)

Sources that this is valid:

- https://pagedart.com/blog/single-quote-in-html/
- https://stackoverflow.com/questions/2210430/are-single-quotes-valid-in-html-xhtml (Strictest answer says that `"` is not allowed in attribute, but says nothing about plain text)

**Workaround**:

I am currently setting the `XML_SPECIAL_RE` field with my own replacer, which ignores the `"`case.

**Proposed solution**:

https://github.com/vsch/flexmark-java/blob/c0313d67e0146292a10d04eb8944faff991579e9/flexmark-util-html/src/main/java/com/vladsch/flexmark/util/html/HtmlAppendableBase.java#L128

     appendable.append(s);

Thanks for your time!

**Comment by vsch** [comment]
My apologies for taking a year to address this. You are right. This was probably inherited from original code.

I will merge your PR for next release.

**Comment by reisi007** [comment]
Hi :)

It's okay. Hm....

Seeing it now there is a downside to this solution as well... Links for example <a href="bla">. If the String "bla" contained a ", it would break the generated HTML.

So might be better to have a better workaround than that (I can look into this if you think that the solution above is not good enough)

**Comment by reisi007** [comment]
It's okay :)

However I cannot run the following test

```
com.vladsch.flexmark.integration.test.SpecIntegrationTest

java.lang.AssertionError: Resource path: 'D:\com\vladsch\flexmark\test\util\spec.txt' not found.
```

We can also leave that for now, I have a workaround for my project :) And I guess I am off spec TBH
