### ISSUE TITLE
how to set border in the table extension

### ISSUE THREAD

**Issue by Zhen-hao** [vsch/flexmark-java#454]
hi, it is more a question. I couldn't see how to do it from the source code. 

With the table extension, I can render tables in Markdown files. But the result HTML tables don't have any style set.
So, there are no lines between rows or columns in my case. 

Is it possible to set the border as an option parameter?

**Comment by vsch** [comment]
You can use the generic attribute provider extension to add a class attribute to table elements or attributes. 

Look in the samples module for an example of attribute provider extension.

**Comment by Zhen-hao** [comment]
@vsch thank you for the suggestion.
If I understand it correctly, I need to implement `setAttributes` like [this](https://github.com/vsch/flexmark-java/blob/c0313d67e0146292a10d04eb8944faff991579e9/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/AttributeProviderSample.java#L40).

It seems I need to know more about this library's DSL to do it. I will do it when I get more time.

**Comment by vsch** [comment]
Yes, you need to implement the container class for the method and the SampleExtension class too. Then add the extension to your extensions list so it is loaded by the parser. 

What you are doing is creating an extension which only implements an attribute provider.

If you already have a custom extension for your use case you can just add the attribute provider to it.
