### ISSUE TITLE
How to have square brackets in output without being parsed as a LinkRef  

### ISSUE THREAD

**Issue by kemitix** [vsch/flexmark-java#460]
I have a source document that contains a phrase like:

```
Some text [with text in square brackets] that is not a link.
```

When parsed, this is interpreted as a `LinkRef`. How do I tell flexmark to treat it as plain text?

Thanks

**Comment by vsch** [comment]
Use the standard markdown escape `\` before the leading `[`.

**Comment by kemitix** [comment]
@vsch Thanks. I think I'd been trying to escape both open and close braces.

**Comment by noahmoss** [comment]
@vsch Is this not a bug? It seems that escaping should not be required, at least according to the CommonMark spec. [This example works](https://spec.commonmark.org/dingus/?text=Some%20text%20%5Bwith%20text%20in%20square%20brackets%5D%20that%20is%20not%20a%20link.), in addition.

I am running into this issue as well but escaping is not an option as I do not have control of the Markdown input.
