### ISSUE TITLE
GFM with Syntax Highlight?

### ISSUE THREAD

**Issue by itamarc** [vsch/flexmark-java#469]
### Discussed in https://github.com/vsch/flexmark-java/discussions/465

<div type='discussions-op-text'>

<sup>Originally posted by **itamarc** July 17, 2021</sup>
I'm using Flexmark to convert some files in a GitHub Action. But when I convert a .md file that have a section with syntax highlight defined, it looses the highlight, only putting it in a `<pre>` block with `<code class="language-yaml">` inside. (I don't know if there is a way to use this "class".

I tried to find some extension or option to activate the syntax highlight, but failed to find anything.

Does Flexmark support the conversion of syntax highlighted blocks? If it does, how can I use it?
</div>

**Comment by cng-pvl** [comment]
Hi Itamar,

for highlighting, take a look here:

https://github.com/vsch/flexmark-java/issues/183#issuecomment-368314949

**Comment by itamarc** [comment]
Thanks, @cng-pvl . Now I understood. I'll look HighlightJS and Prism.js to see which one is better for my project.

Sorry that I failed to find that closed issue.
