### ISSUE TITLE
ID attibutes specifed with {#} syntax don't appear when not using anchorlinks.

### ISSUE THREAD

**Issue by tom-clik** [vsch/flexmark-java#476]
Using the attribute extension you can specify an id using a # short cut e.g. {#anchor-name}

These work when using the anchorLinks extension but not without it.

* [X] extension(s)

**To Reproduce**

Ensure attributes is on and anchorLinks is off.
Parse sample text below.

```
# Title {#title}

## Heading with class {#myid .class otheratt=whatver}
```

**Expected behavior** Should render id attribute  

```
<h1 id='title'>Title</h1>
<h2 id='myid' class='class' otheratt='whatver'>
```

**Resulting Output** It is best to provide one of the following (in decreasing order of value):

```
<h1>Title</h1>
<h2 class='class' otheratt='whatver'>
```

<dependency>
            <groupId>com.vladsch.flexmark</groupId>
            <artifactId>flexmark-all</artifactId>
            <version>0.62.2</version>
        </dependency>

**Comment by jochenberger** [comment]
This is still happening in 0.64.0. The id gets set via `setAnchorRefId`, but it is not written

**Comment by jochenberger** [comment]
I think that in `com.vladsch.flexmark.html.renderer.CoreNodeRenderer.render(Heading, NodeRendererContext, HtmlWriter)`, we need to check whether the node has an explicit ID set.

**Comment by jochenberger** [comment]
As a workaround, one can set `HtmlRenderer.RENDER_HEADER_ID` to `true`.

**Comment by vsch** [comment]
> As a workaround, one can set `HtmlRenderer.RENDER_HEADER_ID` to `true`.

Actually, it is not a workaround, but the correct option setting to get header ids rendered.

The attributes extension affects the parsing and generated AST, the rendering option controls the generation of HTML. You need both set to get the output you expect.

There are use cases where you want the attributes parsed but not generated in HTML.

This probably needs clarification in the attributes extension documentation.
