### ISSUE TITLE
Add Email obfuscation?

### ISSUE THREAD

**Issue by rygel** [vsch/flexmark-java#50]
Is it possible to add email address obfuscation like in pegdown? 
It is defined in Fastencoder:
https://github.com/sirthias/pegdown/blob/2a514555a84f56fe112155748fc24d84046e9c88/src/main/java/org/pegdown/FastEncoder.java

**Comment by vsch** [comment]
@rygel, I will add it for next release, which should happen within a day or two max.

When using pegdown profile e-mail obfuscation will be on by default. For CommonMark and other processors you will need to set `HtmlRenderer.OBFUSCATE_EMAIL` to `true`, if you need to have repeatability for testing then set `HtmlRenderer.OBFUSCATE_EMAIL_RANDOM` to `false` and then the result will be repeatable.

**Comment by rygel** [comment]
@vsch Thank you very much for your quick response!

**Comment by vsch** [comment]
@rygel, update released, maven updated
