### ISSUE TITLE
2 spaces at end of line is not recognized as a newline if the end of line has \r\n

### ISSUE THREAD

**Issue by vmassol** [vsch/flexmark-java#54]
If I give to the parser "sometext  \n" I get a newline block.

But if I give to the parser "sometext  \r\n" I get 2 spaces.

I tried to check if this bug was fixed since on xwiki I'm currently using v0.12.0 but seems that the VERSION.md file has not beed updated with the changes ;)

Thanks

**Comment by vsch** [comment]
@vmassol, it's a bug. Thanks for catching it. I'll release a fix shortly

**Comment by vsch** [comment]
@vmassol, fixed in 0.13.4, released

**Comment by vmassol** [comment]
hehe as fast as usual, thanks! :)

**Comment by vmassol** [comment]
Waiting for it to appear on http://repo2.maven.org/maven2/com/vladsch/flexmark/flexmark-java/ (always a pain)

**Comment by vsch** [comment]
@vmassol if patience is a virtue. Maven is for the very virtuous.

**Comment by vmassol** [comment]
indeed :) It's there now. thx

**Comment by vmassol** [comment]
@vsch bad news, it's still failing. This time I took the time to write a unit test and it's indeed confirming that it's not working:

{code}
    @Test
    public void convertTwoSpacesIntoNewMine() throws Exception
    {
        Parser parser = this.mocker.getInstance(Parser.class, "markdown/1.2");

        XDOM xdom = parser.parse(new StringReader("paragraph1 on  \nmultiple  \nlines\n"));
        assertEquals(2, xdom.getBlocks(new ClassBlockMatcher(NewLineBlock.class), Block.Axes.DESCENDANT).size());

        xdom = parser.parse(new StringReader("paragraph1 on  \r\nmultiple  \r\nlines\r\n"));
        assertEquals(2, xdom.getBlocks(new ClassBlockMatcher(NewLineBlock.class), Block.Axes.DESCENDANT).size());
    }
{code}

The second assert fails.

Could you double check?

Thanks

**Comment by vsch** [comment]
@vmassol, my bad. I re-used a test which had more than 2 trailing spaces so it passed. With only 2 spaces and \r\n it does not parse as HardLineBreak. Fixing. now. Hope you have enough virtue left. 😊

**Comment by vmassol** [comment]
Don't worry it's my fault. I should have tested it before doing a new release of the xwiki markdown extension :)

**Comment by vsch** [comment]
@vmassol, I usually write basic tests and then add more as I encounter bugs in real use cases. In this case this approach does not work because none of my use cases come with \r\n EOL. Oops.

New version released.

**Comment by vmassol** [comment]
Thanks!

That's exactly what happened to me too and why I didn't write a new test earlier on (my framework for tests didn't allow me to specify end of lines). So this time I've had to create a new unit test without using my test framework ;).

**Comment by vsch** [comment]
You are welcome. 

In my case there is no reason other than laziness. I love having tests to ease debugging and validate changes to code but I hate writing tests. Something I haven't been able to reconcile, even with an easy and painless test harness in flexmark-java which makes writing and maintaining tests a breeze.
