### ISSUE TITLE
Indented Link Reference Definitions not parsed correctly

### ISSUE THREAD

**Issue by Elmervc** [vsch/flexmark-java#55]
I was migrating our project to use flexmark instead of pegdown, when I came across the following issue with link reference defs.

## Example markdown:

```
This note demonstrates some of what [Markdown][1] is capable of doing.
....
*Note: the fourth item uses the Unicode character for [Roman numeral four][2].*

  [1]: http://daringfireball.net/projects/markdown/
  [2]: http://www.fileformat.info/info/unicode/char/2163/index.htm
```

### Expected result:
This note demonstrates some of what [Markdown][1] is capable of doing.
....
*Note: the fourth item uses the Unicode character for [Roman numeral four][2].*

  [1]: http://daringfireball.net/projects/markdown/
  [2]: http://www.fileformat.info/info/unicode/char/2163/index.htm

### Given result (using CommonMark profile):
<p>This note demonstrates some of what <a href="http://daringfireball.net/projects/markdown/">Markdown</a> is capable of doing.<br>....<br><em>Note: the fourth item uses the Unicode character for [Roman numeral four][2].</em></p> 
<p>[2]: http://www.fileformat.info/info/unicode/char/2163/index.htm</p>

------

CommonMark spec:
>A link reference definition consists of a link label, indented up to three spaces, followed by a colon (:), optional whitespace (including up to one line ending), a link destination, optional whitespace (including up to one line ending), and an optional link title, which if it is present must be separated from the link destination by whitespace. No further non-whitespace characters may occur on the line.

------
When I add an additional newline between the definitions, or when I remove the indentation (2 spaces) from the definitions, it parses/renders correctly.

**Comment by vsch** [comment]
@Elmervc, it is a bug. The code fails to skip leading 1-3 spaces on references after the first. I am making a release with a fix now.

**Comment by vsch** [comment]
@Elmervc, version 0.13.6 released. Maven central update may take some time.

**Comment by vsch** [comment]
@Elmervc, maven central index was updated. Let me know if you encounter any other issues migrating from pegdown.

**Comment by Elmervc** [comment]
Thanks a lot for this quick fix. I've had some other issues with the behaviour of hard wraps being different from pegdown (using the pegdown adapter). Shall I report that in a new issue?

**Comment by vsch** [comment]
@Elmervc, please don't hesitate to open an issue on any discrepancy you encounter.
