### ISSUE TITLE
Request for information: configuration to format a markdown document on a console

### ISSUE THREAD

**Issue by jlerbsc** [vsch/flexmark-java#555]
How can flexmark be configured to format a markdown document on a console?

I am using the spring shell library on a client application which must display help on the console which is formatted in markdown. I would like this help to be displayed in a formatted text form. How can I do this? Is there an extension I could use to get this rendering.

**Comment by DaveJarvis** [comment]
This isn't a responsibility of flexmark-java. It's up to the developer who wants to use the library to make a program tailored to their particular requirements.

My text editor, [KeenWrite](https://github.com/DaveJarvis/keenwrite), uses flexmark-java both when running from the command-line _and_ from running through the user interface.

Broadly:

1. Write a Java program that has a `main(String args[])`.
1. Open a file from the given arguments, or open standard input.
1. Read from the stream.
1. Create a newly configured instance of flexmark-java's parser.
1. Pass the stream to the parser.
1. Write the transformed document to standard output (or a file if given on the command-line).

How you implement this is your responsibility, flexmark-java will only do the heavy lifting of transforming the document.

**Comment by DaveJarvis** [comment]
@jlerbsc if this answers your question, please close the ticket. You may wish to ask specific questions about integration on StackOverflow.

Otherwise, please add more details about your question.
