### ISSUE TITLE
Pegdown HARDWRAPS option adds an additional line break when using trailing spaces

### ISSUE THREAD

**Issue by Elmervc** [vsch/flexmark-java#56]
When using the following option configuration:  
`new MutableDataSet( PegdownOptionsAdapter.flexmarkOptions( Extensions.ALL ) )` ,  
the parser/renderer adds 2 line breaks instead of one when using 2 trailing spaces followed by a line break.

### Example markdown
```markdown
line one with line break
line two with line break
line three with line break and 2 trailing spaces  
line four at the end
```

#### Expected result

<p>line one with line break<br> line two with line break<br> line three with line break and 2 trailing spaces<br> line four at the end</p>

#### Given result

<p>line one with line break<br> line two with line break<br> line three with line break and 2 trailing spaces<br> <br> line four at the end</p>

-----

My current fix is to change the options to:

```java
options = new MutableDataSet( PegdownOptionsAdapter.flexmarkOptions( Extensions.ALL & ~Extensions.HARDWRAPS ) );
options.set(HtmlRenderer.SOFT_BREAK, "<br/>");
```

**Comment by vsch** [comment]
@Elmervc, this is a bug I missed in fixing. I encountered it in my plugin but forgot to fix in the library.

The fix is exactly as you have done. I will make the fix and make a new release.

**Comment by Elmervc** [comment]
Great, thanks again! No other issues right now :)
