### ISSUE TITLE
Get all modules for gradle build

### ISSUE THREAD

**Issue by mnlipp** [vsch/flexmark-java#57]
Can anybody please tell me how I can force all modules to be included in a gradle build?

If I depend the compile on flexmark-java (`[group: 'com.vladsch.flexmark', name: 'flexmark-java', version: '0.15.+']`) gradle downloads only a pom.xml with the module list (no jars). If I depend on flexmark (`[group: 'com.vladsch.flexmark', name: 'flexmark', version: '0.15.+']`), I get only the "core" module (jar).

Of course, I could list all modules as dependencies explicitly (although this is quite a list). But this is difficult to maintain on the long run.

**Comment by vsch** [comment]
If someone can point me where I can get information on how to add to flexmark-java pom building of a jar that contains all or some of the dependent modules I will be able to add the core flexmark and all the extension jars to flexmark-java.

**Comment by vsch** [comment]
@mnlipp, I found instructions and trying it out now. It will create an artifact id `flexmark-parent` that will include core, util, extension modules, formatter and conversion modules: jira, youtrack, pdf and html to markdown.

I will let you know when I got it working and made a release

**Comment by mnlipp** [comment]
Great!

**Comment by vsch** [comment]
@mnlipp, I don't know if the solution I found will be of help. I made a new maven release 0.15.1 with an artifact `flexmark-parent` but could only create a jar with a classifier of -lib which contains core, extensions and converters not transient dependencies. 

I will try to figure out if it is possible to create a module artifact that contains output of other modules without a classifier.

**Comment by mnlipp** [comment]
Personally, I'd rather call it `flexmark-all`. But leaving that aside, it works as it should. All flexmark modules (and their dependencies) are downloaded and put in the classpath. Thanks!

**Comment by vsch** [comment]
@mnlipp, if you don't mind the break I will rename the module to flexmark-all and make a new release. I like this naming better.

**Comment by vsch** [comment]
@mnlipp, changes made and updated. Maven updated 0.15.2, flexmark-parent renamed to flexmark-all.

**Comment by mnlipp** [comment]
Nice, thanks!
