### ISSUE TITLE
Suppress highlight.js's auto guessing the language

### ISSUE THREAD

**Issue by mnlipp** [vsch/flexmark-java#59]
`highlight.js` seems to be one of the most popular libraries for syntax highlighting. Sometimes, its "auto guessing the language" feature leads to strange results. The feature can be turned off using "`nohighlight`" (instead of "`language-...`") as class for the `code`
```html
<pre><code class="nohighlight">...</code></pre>
```

Currently, flexmark renders fenced code blocks without language specification as `code` without a class attribute, thus "triggering" the auto guessing feature. It would be nice to be able to prevent auto guessing for the complete generated markup with a new option `FENCED_CODE_LANGUAGE_DEFAULT_CLASS`. When set, fenced code blocks without language would be rendered as `code` with a `class` attribute with the specified value. 

Setting `FENCED_CODE_LANGUAGE_DEFAULT_CLASS = "nohighlight"` would then turn off auto guessing for the complete generated document.

**Comment by vsch** [comment]
@mnlipp, I added `HtmlRenderer.FENCED_CODE_NO_LANGUAGE_CLASS` which is used as the class of the `<code>` tag for fenced code without info (language) specification and for indented code.

Version 0.15.3 updated and released.
