### ISSUE TITLE
Problem with WikiLink rendering

### ISSUE THREAD

**Issue by mnlipp** [vsch/flexmark-java#61]
I have added the WikiLink extension. But when I render this
```
This is a link [[http://www.example.com/]].

This is a link [[Example http://www.example.com/]].
```
I get:
```html
<p>This is a link <a href="http:--www.example.com-">http://www.example.com/</a>.</p>
<p>This is a link <a href="Example-http:--www.example.com-">Example http://www.example.com/</a>.</p><
```
(Note the wrong href attributes.)

Am I doing something wrong or is this a bug?

**Comment by vsch** [comment]
@mnlipp, wiki links are for page references not links. ` +/<>` characters in the wiki page ref are changed to dashes `-` before creating the link with the page ref. It has options and link resolver that can be implemented to create custom page ref to link resolution.

GitHub Wiki, for example, ignores directory structure when resolving a link to an actual file.

**Comment by mnlipp** [comment]
Thanks for the clarification. I found [this](https://pythonhosted.org/Markdown/extensions/wikilinks.html) as first search result and had different expectations.

**Comment by vsch** [comment]
@mnlipp, the example you looked at is correct. If you notice the page ref is passed through, in this case with the exception of adding a prefix and suffix of `/`. You can get this effect with by setting `WikiLinkExtension.LINK_PREFIX` option to `/` and `WikiLinkExtension.LINK_FILE_EXTENSION` option to `/`. The file extension is really just a suffix to the page reference.

There is no option to add a class but if needed it can be added either in the extension or via a custom attribute provider.
