### ISSUE TITLE
target option for anchor rendering

### ISSUE THREAD

**Issue by mnlipp** [vsch/flexmark-java#64]
I'm writing a markdown document that is going to be shown in a frame of a frameset. In my case, all links "[...](...)" are references to external pages (outside the frameset), which means that I need 'target="_top"' in the anchor links.

I wonder if this is a general use case that could be supported "out of the box", maybe even with the possibility to choose between 'target="_top"' and 'target="_blank"'. Maybe by an option that allows to freely define the `target` attribute for links rendered from "[...](...)".

**Comment by mnlipp** [comment]
I knew that adding an extension of my own was an option. Despite the examples provided as "official" extensions, it's a bit hard to get started, though. So thanks for the code.

**Comment by vsch** [comment]
@mnlipp, as an option

**Comment by vsch** [comment]
@mnlipp, as an alternative you can give me more details on what plain text rendering would result then I can quickly throw it together for you.

**Comment by vsch** [comment]
@mnlipp, sorry wrong issue. 😊

**Comment by vsch** [comment]
@mnlipp, the repo has a [`flexmark-java-samples`](https://github.com/vsch/flexmark-java/tree/master/flexmark-java-samples) which as a few extension types


![image](https://cloud.githubusercontent.com/assets/10299086/23411587/b996e5e8-fda0-11e6-9aef-2176344806cd.png)

**Comment by mnlipp** [comment]
@vsch Thanks for the link to the samples. I completely overlooked this. Maybe you should add this link in the [Extension points section](https://github.com/vsch/flexmark-java#extension-points-in-the-api-are-many-and-numerous).

In case somebody comes across this, [here](https://github.com/mnlipp/jdrupes-mdoclet/blob/master/mdoclet/src/org/jdrupes/mdoclet/processors/flexmark/TopAnchorLinkExtension.java)'s my final solution:
```java
/**
 * Provides an extension that adds "`target='_top'`" to all anchor links.
 */
public class TopAnchorLinkExtension implements HtmlRenderer.HtmlRendererExtension {

	/**
	 * Called with all options. Currently this extension has no options and
	 * does nothing.
	 */
	@Override
	public void rendererOptions(MutableDataHolder options) {
	}

	/**
	 * This method is called once when the builder for the output is created.
	 * It must modify the passed in builder as required by the extension.  
	 */
	@Override
	public void extend(Builder rendererBuilder, String rendererType) {
		rendererBuilder.attributeProviderFactory(new IndependentAttributeProviderFactory() {
			
			@Override
			public AttributeProvider create(NodeRendererContext context) {
				return new AttributeProvider() {

					@Override
					public void setAttributes(Node node, AttributablePart part, 
							Attributes attributes) {
						if (node instanceof Link && part == AttributablePart.LINK) {
				            attributes.replaceValue("target", "_top");
				        }
					}
					
				};
			}
		});
	}
	
	/**
	 * Extensions are added by providing a class to flexmark. Flexmark then
	 * invokes the extension's static `create` method through reflection.
	 * 
	 * @return an instance of the extension
	 */
	public static Extension create() {
		return new TopAnchorLinkExtension();
	}
}
```
