### ISSUE TITLE
Add come comments

### ISSUE THREAD

**Issue by mnlipp** [vsch/flexmark-java#65]
Some comments that would have helped me when writing my first extension:

 * `Extention`
    ...
    Implementations of this interface should provide a method `static Extension create()` that returns
    an instance of the extension. This method is invoked by flexmark for extension classes set
    as `Parser.EXTENSION`s using reflection.

 * `HtmlRenderer.HtmlRendererExtension#extend`
    This method is called once when the builder for the output is created.
    It must configure the passed in builder as required by the extension.

 * `HtmlRenderer.Builder`
    A builder is configured by adding factories for various aspects of the build process. The factories
    provide general information about the changes to be made and create the objects that do the 
    actual work on the HTML tree.

At least, this is what I have understood.

**Comment by vsch** [comment]
@mnlipp, thanks for the feedback. I will add it.

**Comment by vsch** [comment]
@mnlipp, added comments to `Extension`, `Parser.ParserExtension`,
`Parser.ReferenceHoldingExtension` and `HtmlRenderer.HtmlRendererExtension`
