### ISSUE TITLE
Detach the fork from commonmark-java

### ISSUE THREAD

**Issue by dmikurube** [vsch/flexmark-java#68]
Hi,

I'm seeing this project is still a (GitHub) fork from atlassian/commonmark-java, but I guess this is now an independent project from that. What do you think about detaching the GitHub fork?

See:
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

Thanks for this nice Markdown library. I think to use the library for my project. :)

**Comment by vsch** [comment]
@dmikurube, it is a good idea to detach the fork. I will contact GitHub support.

**Comment by dmikurube** [comment]
@vsch It looks detached. Nice!

**Comment by vsch** [comment]
@dmikurube, thank you for the suggestion. I did not even consider the possibility.
