### ISSUE TITLE
parse failed for angle quotes if the end angle quote follows with a line feed or a carriage return

### ISSUE THREAD

**Issue by huapeng01016** [vsch/flexmark-java#70]
using pegdown 

```
      static DataHolder OPTIONS = PegdownOptionsAdapter.flexmarkOptions( 
			Extensions.ALL
			);
	
	static Parser PARSER = Parser.builder(OPTIONS).build();
	static HtmlRenderer RENDERER = HtmlRenderer.builder(OPTIONS).build();
```

The following code failed

```
       System.out.println("here0");
	Node document = PARSER.parse("<<test>>\n");
	System.out.println("here1");			
```		

"\<\<test\>\>\r" failed as well.

Both "\<\<test\>\>\r\n" and "\<\<test\>\>\n\n" worked fine.

**Comment by vsch** [comment]
@huapeng01016, thank you for reporting this. It is a bug in the TypographicExtension code. 

As a workaround use `(Extensions.ALL & ~Extensions.QUOTES)` instead of ALL. I will post an update when I have a fix released. Should be shortly.

**Comment by vsch** [comment]
@huapeng01016, repo updated. Maven release in progress.

**Comment by huapeng01016** [comment]
@vsch, thanks for your prompt reply. My project does reply on the QUOTES extension. I am using a temporary work around which checks if the source string ends with "\>\>\n" or "\>\>\r", if it does, 
I add an extra "\n" or "\r" to the source.  It works ok but a proper fix would be highly appreciated. 

Thanks again.

**Comment by huapeng01016** [comment]
Thanks again. I will test it shortly.
