### ISSUE TITLE
Can't nest code blocks in ordered list

### ISSUE THREAD

**Issue by unsaved** [vsch/flexmark-java#73]
I wrote the subject line presumptuously, just to be succinct.  If there is a way to accomplish this now, please tell.

Is there a way to nest \```code blocks\``` in an ordered list and keep the same list going?  With every combination I have tried, the code block ends the previous ordered list and a new list starts.  So even though I am continuing what I want to be the same list, the numbering resets and starts at one again.

My work-around is to use the great feature where the first number of the resumed list is honored, but it still causes problems for me because I import my HTML into MS word and the numbering gets all screwed up because Word sees that it is a different list.

**Comment by vsch** [comment]
it appears that GitHub Doc list processing has a bug for code fence processing nested fenced code elements.

GitHub and CommonMark both use list item content column as the indentation level. GitHub Doc has a bug and does not work. Temporarily switch to CommonMark. I will address this in the parser library and release a fix.

    * item
  
      ```
      fenced code 
      ```

![Screenshot_Parser_Lists](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Parser_Lists.png)

**Comment by vsch** [comment]
@unsaved, for ordered lists you need to indent to the item content:

    1. item
  
       ```
       fenced code 
       ```

**Comment by vsch** [comment]
@unsaved, repo updated. Maven release in progress, may take a bit for the central update.

**Comment by vsch** [comment]
@unsaved, was this the issue you were having or was it something else?

**Comment by unsaved** [comment]
Ty for work-around and upcoming permanent fix.  I had tried indenting the fence with CommonMark, but I indented only the content, not the back-tick lines (which I incorrectly thought needed to stay at column 1).

Works great when I mark up correctly with CommonMark.

**Comment by vsch** [comment]
@unsaved, thank you for reporting this. 

It worked by accident since the fix for embedded heading in code fence in list item fix. Tests and code fixed now and Maven updated but may take time to reflect in the central index.
