### ISSUE TITLE
Angle quotes again :)

### ISSUE THREAD

**Issue by huapeng01016** [vsch/flexmark-java#74]
With 0.17.3, the following angle quotes are not handled ideally

```
    Source: "<<test>>abcd<</test1>>"
    Flexmark:
    <p>&laquo;test&raquo;abcd&lt;&lt;/test1&gt;&gt;</p>
    Pegdown:
    <p>&laquo;test&raquo;abcd&laquo;/test1&raquo;</p>

    Source: <<test>>abcd<<:test1>>"
    Flexmark:
    <p>&laquo;test&raquo;abcd&lt;&lt;:test1&gt;&gt;</p>
    Pegdown:
    <p>&laquo;test&raquo;abcd&laquo;:test1&raquo;</p>
```

**Comment by vsch** [comment]
@huapeng01016, this time it is a limitation of delimiter processors. I am making a new API breaking release that adds methods to DelimiterProcessor to allow customizing where a delimiter can open or close.

In the case of angle brackets its everywhere.

**Comment by huapeng01016** [comment]
Yeah, that's what I guessed and thanks a lot. Will test soon.
