### ISSUE TITLE
Incorrect footnote link

### ISSUE THREAD

**Issue by zhenyuluo** [vsch/flexmark-java#75]
Hi,

I found that when line separator is ```\r\n```, the footnote link can't be rendered correctly.

Below is my test:

```java
public static String toHtml(String raw) {
        MutableDataHolder options = new MutableDataSet();
        List<Extension> extensions = Lists.newArrayList();
        options.set(Parser.EXTENSIONS, extensions);

        // change soft break to hard break
        options.set(HtmlRenderer.SOFT_BREAK, "<br/>");

        Parser parser = Parser.builder(options).build();
        Node document = parser.parse(raw);
        HtmlRenderer renderer = HtmlRenderer.builder(options).build();
        return renderer.render(document);
    }

    public static void main(String[] args) {
        String str = "Incorrect: [amazon][2]\r\n" +
                "\r\n" +
                "[1]: http://www.google.com/\r\n" +
                "[2]: http://www.amazon.com/";
        System.out.println(toHtml(str));
    }
```

the output is:

```
<p>Incorrect: [amazon][2]</p>
<p>[1]: http://www.google.com/<br/>[2]: http://www.amazon.com/</p>
```

If the line separator is ```\n```, then everything is fine.

**Comment by vsch** [comment]
@zhenyuluo, thank you for reporting this. It seems to be a bug in reference definition parsing when EOL is `\r\n`.

However, these are references not footnotes. Footnotes use `[^` ***`id`*** `]` 

I will release a fix shortly.

**Comment by vsch** [comment]
@zhenyuluo, thank you for catching this. It was a much bigger issue with many regular expressions using `\n` for the expected EOL rather than `\r\n|\r|\n`. A left over from the original commonmark-java that converted input to `\n' EOL before parsing.

Repo updated. Maven release may take a bit to update the central index.

**Comment by steveluo** [comment]
@vsch as always thank you so much for the prompt response!!
