### ISSUE TITLE
How to escape html tag?

### ISSUE THREAD

**Issue by zhenyuluo** [vsch/flexmark-java#79]
Hi,

Is it possible to escape some html tag, or in another word, is it possible to only process some specified html tags? For example, I have below markdown:
```
<script>alert('hello');</script> script tag
<tag> unknown tag
<img src="abc.png" />
```

the html generated is:
```
<script>alert('hello');</script> script tag\n
<p><tag> unknown tag</p>
<img src="abc.png" />
```

while I'm expecting to get result like:
```
&lt;script&gt; alert('hello');&lt;/script&gt; script tag\n
<p>&lt;tag&gt; unknown tag</p>
<img src="abc.png" />
```

It would be great if there is an option to tell Flexmark to only process some specified tags, like img, a, but escape all others.

Best regards

**Comment by vsch** [comment]
e including HTML in markdown that you do not want to be rendered in HTML output is to use fenced code element or indented code:

    <script>alert('hello');</script> script tag\n
    <p><tag> unknown tag</p>
    <img src="abc.png" />

Alternately you can escape the opening `<` of every tag:

    \<script>alert('hello');\</script> script tag\n  
    \<p>\<tag> unknown tag\</p>  
    \<img src="abc.png" />

to get:

\<script>alert('hello');\</script> script tag\n
\<p>\<tag> unknown tag\</p>
\<img src="abc.png" />

**Comment by zhenyuluo** [comment]
@vsch, thank you for the answer.

I know I can use either a fenced code or  a `\` to escape, but most of my customers don't. That is why I ask if I can escape some tags programmatically.

Is there any interface or extension which I can use to escape the tags I don't want manually?

**Comment by vsch** [comment]
@zhenyuluo, there is a way to escape HTML blocks or inline HTML or comments. There is no mechanism to select individual tags to escaped.

Defined in `HtmlRenderer` class:

| Static Field                | Default Value                 | Description                                       |
|-----------------------------|-------------------------------|---------------------------------------------------|
| ESCAPE_HTML                 | `false`                       | escape all html found in the document             |
| ESCAPE_HTML_BLOCKS          | value of `ESCAPE_HTML`        | escape html blocks found in the document          |
| ESCAPE_HTML_COMMENT_BLOCKS  | value of `ESCAPE_HTML_BLOCKS` | escape html comment blocks found in the document. |
| ESCAPE_INLINE_HTML          | value of `ESCAPE_HTML`        | escape inline html found in the document          |
| ESCAPE_INLINE_HTML_COMMENTS | value of `ESCAPE_HTML_BLOCKS` | escape inline html found in the document          |

To escape only inline HTML then set `HtmlRenderer.ESCAPE_INLINE_HTML` to `true` in options that are passed to `HtmlRenderer.builder(DataHolder)`

To customize rendering of HTML blocks or inline HTML tags you would need to create an extension with a custom renderer that renders `HtmlBlock` or `HtmlInline` nodes.

I added a `NodeRendererSample` to `flexmark-java-samples` module with all the HTML rendering copied from `CoreNodeRenderer` so you can use this as a start.

**Comment by zhenyuluo** [comment]
@vsch thank you very much for the detailed instructions.

I'd prefer to pre-process the raw markdown first and then pass it to flexmark to generate html.

You may close this issue now and again, thank you very much!

**Comment by vsch** [comment]
@zhenyuluo, processing raw markdown may seem easier but you will have to take care of the Markdown context, which is not trivial. Just looking for the HTML pattern will not work except for most trivial cases.

Nothing stops you from doing the pattern search but in the custom node renderer to decide if you should render the node normal or escaped.

The [sample code](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/NodeRendererSample.java#L83-L89) already passes an `escape` boolean to tell the method to escape the HTML. All you would need to do is add some code to modify this parameter using the node content `node.getChars()` which returns a `CharSequence`. Simply pass true for `escape` for any HTML you want to escape.

**Comment by zhenyuluo** [comment]
@vsch, thanks for the sample code, I have tried and it works.

Below is what I modified to only support render img tag, and I want to know how to get the the tag name of a node? It seems that there is no API like `node.getTagName()`, right?

```java
public void renderInlineHtml(HtmlInlineBase node, NodeRendererContext context, HtmlWriter html, boolean suppress, boolean escape) {
            if (suppress) return;

            String chars = node.getChars().normalizeEOL();

            if (chars.startsWith("<img ")) { // "img".equals(node.getTagName()) would be more reasonable
                html.rawPre(chars);
            } else {
                html.text(chars);
            }
        }
```

**Comment by vsch** [comment]
@zhenyuluo, the HTML nodes are not distinguished by their content. The node text is passed through as is. Therefore the only way to implement what you want is to parse the node text. You can use regular expressions to make it manageable.

You can use the RegEx in [`com.vladsch.flexmark.ast.util.Parsing`](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/ast/util/Parsing.java) and [`com.vladsch.flexmark.internal.HtmlBlockParser`](https://github.com/vsch/flexmark-java/blob/master/flexmark/src/main/java/com/vladsch/flexmark/internal/HtmlBlockParser.java) as examples or as is.

**Comment by zhenyuluo** [comment]
@vsch thank you very much, for your awesome library and awesome support!

**Comment by nanodeath** [comment]
Hey, sorry for hijacking but I have a quick followup question. What's the difference between HTML, HTML blocks, and inline HTML?

**Comment by vsch** [comment]
@nanodeath, HTML applies to all HTML elements: block, block comments, inline and inline comments.

Markdown block HTML consists of HTML block tags that start a paragraph, inline HTML is any HTML that is part of a paragraph.

Block HTML: http://spec.commonmark.org/0.27/#html-blocks

```markdown
<div>
     <p>test</p>
</div>
```

inline HTML: http://spec.commonmark.org/0.27/#raw-html

```markdown
This paragraph has inline HTML <kbd>Keyboard</kbd>
```

**Comment by ssikuro** [comment]
Sorry to doubly hijacking the thread. I noticed, in addition to HtmlInline, HtmlInlineComment, HtmlBlock, and HtmlCommentBlock, there are HtmlInnerBlock and HtmlInnerBlockComment node classes. What are these inner things? When will they be used?

**Comment by vsch** [comment]
@ssikuro, I use the library for my [Markdown Navigator] plugin for [IntelliJ IDEA] and other JetBrains IDEs. They have a nice ToDo work window that gathers todo comments into a list. Only comments are processed so I had to make sure that HTML comments would be a separate node in the AST. CommonMark treats the whole HTML block as a single piece. I added an option to have the outer block as is, with children breaking out the comment and non-comment blocks. These are the inner counterparts. 

They are different AST Node classes because most of the selection and binding in flexmark-java is based on the node class, having these as separate classes means they can be handled with the standard functions.


[JetBrains plugin page]: https://plugins.jetbrains.com/plugin?pr=&pluginId=7896
[IntelliJ IDEA]: http://www.jetbrains.com/idea
[Markdown Navigator]: http://vladsch.com/product/markdown-navigator

**Comment by ssikuro** [comment]
Thank you, @vsch, but I'm not sure if I understood your response correctly. Do you mean those inner classes are for use from the IntelliJ IDEA plugins, and won't be in the node tree in the default setting? I'm mainly concerned with how to test my code.

**Comment by vsch** [comment]
@ssikuro, if memory serves correctly, default settings don't produce these. I try to keep defaults to standard stuff. All my extensions I add as options.

When in doubt, you could use the same class used in the tests to dump the AST as text.

```
    public String ast(Node node) {
        return new AstCollectingVisitor().collectAndGetAstText(node);
    }

```

Here is what a test case for HTML blocks with inner parsing looks like. The ast you see is from the `AstCollectingVisitor` above

<img width="849" alt="screen shot 2018-02-26 at 1 04 08 pm" src="https://user-images.githubusercontent.com/10299086/36686798-90b4adf4-1af5-11e8-9c24-d27cb7634997.png">

**Comment by vmassol** [comment]
@vsch Hello from XWiki! I've been trying to escape any usage of the `<script>` HTML tag. For that I've copied your code from https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/NodeRendererSample.java

However, I can see that the extension is correctly added to the list of extensions but its `extend()` method is not called. Any idea what I could be missing?

My code:

```
    private static final List<Class<?>> DEFAULT_EXTENSIONS = Arrays.asList(
        WikiLinkExtension.class,
        AutolinkExtension.class,
        DefinitionExtension.class,
        TablesExtension.class,
        StrikethroughSubscriptExtension.class,
        SuperscriptExtension.class,
        AbbreviationExtension.class,
        MacroExtension.class,
        SecureHTMLRendererExtension.class
    );
...
    protected MutableDataHolder getDefaultOptions(ParserEmulationProfile parserEmulationProfile,
        List<Class<?>> additionalExtensionClasses)
    {
        // Configure Parser Family
        MutableDataHolder options = new MutableDataSet();
        options.setFrom(parserEmulationProfile);

        // Configure extensions
        List<Extension> extensions = new ArrayList<>();
        List<Class<?>> resolvedExensionClasses = new ArrayList<>();
        resolvedExensionClasses.addAll(DEFAULT_EXTENSIONS);
        resolvedExensionClasses.addAll(additionalExtensionClasses);
        for (Class<?> extensionClass : resolvedExensionClasses) {
            try {
                Method method = extensionClass.getMethod("create");
                Extension extension = (Extension) method.invoke(null);
                extensions.add(extension);
            } catch (Exception e) {
                // Invalid extension, skip it
                getLogger().warn("Invalid extension: [{}]. Root cause: [{}]", extensionClass.getName(),
                    ExceptionUtils.getRootCauseMessage(e));
            }
        }
        options.set(Parser.EXTENSIONS, extensions);

        return options;
    }
```

And:

```
public class SecureHTMLRendererExtension implements HtmlRenderer.HtmlRendererExtension
{
    @Override
    public void rendererOptions(MutableDataHolder options)
    {
        // Add any configuration settings to options you want to apply to everything, here
    }

    @Override
    public void extend(HtmlRenderer.Builder htmlRendererBuilder, String rendererType)
    {
        htmlRendererBuilder.nodeRendererFactory(new SecureNodeRenderer.Factory());
    }

    public static SecureHTMLRendererExtension create()
    {
        return new SecureHTMLRendererExtension();
    }
}
```

(I'm not showing the code for `SecureNodeRenderer` since it's failing to be called)

Thanks a lot!

PS: Maybe there's a better way to do this now in 2023?

**Comment by the-red-herring** [comment]
> [@zhenyuluo](https://github.com/zhenyuluo), the right way to handle including HTML in markdown that you do not want to be rendered in HTML output is to use fenced code element or indented code:
> 
> ```
> <script>alert('hello');</script> script tag\n
> <p><tag> unknown tag</p>
> <img src="abc.png" />
> ```
> 
> Alternately you can escape the opening `<` of every tag:
> 
> ```
> \<script>alert('hello');\</script> script tag\n  
> \<p>\<tag> unknown tag\</p>  
> \<img src="abc.png" />
> ```
> 
> to get:
> 
> <script>alert('hello');</script> script tag\n <p><tag> unknown tag</p> <img src="abc.png" />

Is this still the case in 2025? I haven't delved through the code too deeply but I couldn't spot anything that indicates that adding a `\` in front of a HTML will prevent that tag being converted by `FlexmarkHtmlConverter`. This is the case in practice as well, I have something that automatically adds `\` in front of certain HTML tags but when running the text through the converter the tags are converted successfully to markdown instead of being ignored, which just leaves a `\`s in my output text.
