### ISSUE TITLE
Convert css-class as Node's build-in attribute

### ISSUE THREAD

**Issue by sunnymix** [vsch/flexmark-java#80]
I just wondering is it possible to parse css-class, something looks like `.<css-class>`, as Node's build-in attribute, so that can be used while Node's rendering?

For example, I have a source markdown text like:

```
#.alert.primary Header with css-class
```

and expecting convert to:

```
<h1 class="alert primary">Header with css-class</h1>
```

Keynotes:

- position: right after basic nodes' symbol
- start char: `\dot`
- end char: `\space`

**Comment by vsch** [comment]
@sunnymix, this would require a custom parser to handle it in general. I would guess that it will affect parsing of quite a few elements. For example headings by default require a space after `#`, there is an option to not require a space for headings. For other elements it may require modifying the block parser syntax for the element.

For headings it would only need to allow headings without a space after `#` by setting:

- `Parser.HEADING_NO_ATX_SPACE` : default `false` allow headers without a space between `#` and the header text if true

and implementing a custom node renderer that parses the heading text for a class prefix.

**Comment by vsch** [comment]
@sunnymix, a general [Attributes Extension](https://github.com/vsch/flexmark-java/wiki/Extensions#attributes) was added which allows you to add any attributes including `.class-name` and `#element-id` to any element using the `{attribute=value}` syntax.

Don't know if it will help your case but it is compatible with GitBook and a few other markdown processors for specifying HTML attributes in markdown.
