### ISSUE TITLE
Convert private or package private constructors to protected.

### ISSUE THREAD

**Issue by Erfans** [vsch/flexmark-java#81]
In cases (like my current case) it is necessary to extend Parser or HtmlRenderer to log extra information during the rendering/parsing.
These classes that should be created by builder have private constructors therefore impossible to be extended. By changing the constructors to protected it is possible to extend them as well as force them to be created by builder.

**Comment by vsch** [comment]
@Erfans, can you give me an example of what you want to extend? The extensions are accomplished with the existing API and not through extension of existing classes.

If you can provide information about what you want to accomplish I will be able to help you get this done through the API or see where the API needs to be extended. Extending the class is not an option because it has the potential to be broken with implementation changes in the library.

**Comment by vsch** [comment]
@Erfans, the overview of the API can be found in [Writing-Extensions](https://github.com/vsch/flexmark-java/wiki/Writing-Extensions.md)

**Comment by Erfans** [comment]
The task contains two part:
1. For characters in specific positions in markdown string render Html with extra characters. For example if characters between position 2 and 5 in MD string are `abc` then the rendered html should be `<xx>abc</xx>` instead of `abc`.
2. Reverse procedure, i.e. while converting a specific node (actually any arbitrary node) in an html to md convert it differently and pass the position of rendered characters to a function .E.g. Convert `<xx>abc</xx>` to `abc` and and call function `pos(2,5)`.

**Comment by vsch** [comment]
@Erfans,

1. If the conversion is position specific then the best option is two pre-process the markdown before passing it for parsing by wrapping the text in HTML tags that you want. It seems like the most logical solution. 

   There is no single place where you can override the library functionality that would allow you to parse on an offset basis that would not result in effectively being the same as pre-processing the markdown.

2. The HTML to Markdown module does not have an API for extensions. The only thing I can recommend is make a copy of the module to your own project and make the necessary modifications. At least that way you will have an independent source base that will not be affected by changes made to the library.

**Comment by Erfans** [comment]
Thanks, I did the same.
