### ISSUE TITLE
Question: is there any way to keep every html entities as-is?

### ISSUE THREAD

**Issue by acdcjunior** [vsch/flexmark-java#83]
Consider the following markdown:

```
stuff &Aacute; stuff
```

The `HtmlRenderer` returns:

```
stuff Á stuff
```

If I use `\&Aacute;` it returns:
```
stuff &amp;Aacute; stuff
```

Is there any config to make it return as below?

```
stuff &Aacute; stuff
```

In other words, don't change any HTML Entity at all?

**Comment by vsch** [comment]
@acdcjunior, I added an option to get this effect. Release in a minute.

* add  `HtmlRenderer.UNESCAPE_HTML_ENTITIES`, default `true`. Set to `false` to leave HTML entities  as is in the rendered HTML.

**Comment by vsch** [comment]
@acdcjunior, repo updated. Maven updated, may take the usual maven delay to update indices.

**Comment by vsch** [comment]
@acdcjunior, maven central updated. Let me know if you need more information to get it working for your project.

**Comment by acdcjunior** [comment]
Awesome, I got it working and it is beautiful, thanks a lot!

Now, since we're at it and you are such a nice guy, as payback, here goes a suggestion (no need to reply to this, just take it into consideration):

I have an app that used marked (js) as md->html engine. Earlier today I decided I'd better use a java-based one. Googled it a bit, found pegdown.
But their readme said the project was deprecated and recommended flexmark-java; that's how I came to know your tool.

Now to the problem/suggestion: when evaluating a tool, we usually don't read stuff, the first thing we want is a running example.
I googled for a sample of flexmark-java and found https://github.com/vsch/flexmark-java-sample. Nice, but... actually, that project is a bit frustrating. Though I'm an IntelliJ user, I still expected the project to be a maven (or gradle) one, not a "raw" IntelliJ module.
The referenced libs are 0.4.17 (so old, I noticed later...) and the [`Main`](https://github.com/vsch/flexmark-java-sample/blob/master/src/com/vladsch/Main.java) class has a ton of "detailed" stuff (aka unecessary/too much for me at that moment). Now, of course, when you wrote that class your goal was probably not for it to be a "hello world" class, but bear with me, I'm trying to show you how it felt for me at that point.

The good news is I eventually managed to get it working. What actually helped me a lot was this [`HtmlRendererTest`](https://github.com/vsch/flexmark-java/blob/2c41aeb4badb5ed4f4f36d435ae9f9b1973025d7/flexmark/src/test/java/com/vladsch/flexmark/test/HtmlRendererTest.java) unit test class I stumbled upon. It uses the parser/renderer in a very simple manner (without any additional options) and was perfect for my needs at the moment.

As the day went on I even found your [great wiki and its Usage page](https://github.com/vsch/flexmark-java/wiki/Usage)! When I saw it, I thought: *that* is what I needed in the first place.

So, cutting to the chase, my suggestion is: consider putting a running example as the first thing (or close to the top) of your readme. I reckon the code may take too much space, if you feel that way, place at least a link to the wiki page saying something link "For quick sample and usage examples, click here". I think it would benefit newcomers a lot.

So, that's it. Just a quick report. I hope you don't get it as criticism, because it is not *at all*, your tool is great and I got it working very quickly!
Anyhow, thanks again!! As said, no need to reply, this is just what I thought as a way of saying thank you for your kind feedback on this issue! :) cheers!!

**Comment by vsch** [comment]
@acdcjunior, all suggestions are greatly appreciated. Especially ones from first time users. 

I am still surprised by how little feedback I get from users about their experience and what would help them get started. I keep adding their suggestions as they come in.

I will add a simple working sample at the top of the read me file with links to the Wiki in bold so  first time users cannot miss it. I don't think that a basic sample will take too much space. I will add instructions on flexmark-all dependency which will add all core and extensions so there is no need to fiddle with individual modules to reduce start up complexity. Setting up a working project should be simple in any environment.
