### ISSUE TITLE
Usage in Clojure

### ISSUE THREAD

**Issue by clartaq** [vsch/flexmark-java#84]
I've recently switched to using flexmark as a markdown processor in a Clojure program. Setting up the "plain vanilla" processor works great. But I'm having an issue activating extensions. Here's some code that doesn't quite work.

```clojure
(def parser ^Parser$Builder (let [options (MutableDataSet.)
                                  st (StrikethroughExtension/create)
                                  al (ArrayList. [st]) ]
                              (.set options Parser/EXTENSIONS al)
                              (.build (Parser/builder options))))

(def renderer ^HtmlRenderer$Builder (.build (HtmlRenderer/builder)))

(defn convert-markdown-to-html
  "Convert the markdown formatted input string to html
  and return it."
  [mkdn]
  (let [out (->> mkdn
                 (.parse parser)
                 (.render renderer))]
    out))
```

This code produces no warnings or errors. The type hints are to quiet a reflection warning from the IDE. The code works the same with or without them. I know this is not particularly idiomatic Clojure. I've expanded it like this to aid in my (fruitless) debugging attempts.

This input:

```
    Here is normal text

    <del>Here is strikthrough with the "del" tag.</del>

    ~~Here is strikethrough with double tildes.~~

```

produces this HTML:
```
<p>Here is normal text</p>
<p><del>Here is strikthrough with the &quot;del&quot; tag.</del></p>
<p></p>
```

I've tried some of the test case text and observed similar results. (Don't have Java 7 installed yet to actually run the tests.)

Am I mis-using/configuring the extension somehow?

**Comment by vsch** [comment]
@clartaq, I don't know Clojure but it looks like you are only passing the options to Parser.builder() and not to HtmlRenderer.builder().  If you look at the samples in Java the options are created and the same instance is passed to both parser and renderer builders to make sure both have the same extensions and settings.

The missing extension in the renderer causes the missing strikethrough text since the custom node is missing a renderer it is not rendered in the HTML.

**Comment by clartaq** [comment]
That was the issue. I didn't realize that if the options only contain parser extensions that you had to use them for the renderer too.

Thanks for the help and quick response.

**Comment by vsch** [comment]
@clartaq, extensions can register all possible extension points in the API. For now this is parser, renderer and formatter. This allows an extension to customize all aspects of the library.

Options passed to the builder are available in the Document node and renderer context. You can pass anything you want through the options mechanism to your extension implementation.

The options were deliberately made universal to allow them to contain all configuration and context information for complete flexibility of configuring core and extensions. Passing context to extension implementation code without intervening code needing to know about it makes it much easier to implement functionality not envisioned by the library.
