### ISSUE TITLE
how can use definition extension correctly ?

### ISSUE THREAD

**Issue by firm1** [vsch/flexmark-java#86]
Hi,

I use flexmark and i have a problem with definition extension.

This is my markdown text : 

```
Definition 1
: My name is john
:
: **John riley**

Definition 2
: And you ?
:
: Me ? really ?
```

After processing, i have this html render

```html
<dl>
<dt>Definition 1</dt>
<dd>My name is john</dd>
<dd>
<dd><strong>John riley</strong></dd>
</dd>
<dt>Definition 2</dt>
<dd>And you ?</dd>
<dd>
<dd>Me ? really ?</dd>
</dd>
</dl>
```

I would like something like that

```html
<dl>
<dt>Definition 1</dt>
<dd>My name is john</dd>
<dd><strong>John riley</strong></dd>
</dl>
<dl>
<dt>Definition 2</dt>
<dd>And you ?</dd>
<dd>Me ? really ?</dd>
</dl>
```

Means, two blocks of `<dl>` instead one, and no double `<dd>` for second line of definition content.

This is my java code : 

```java
static final MutableDataHolder OPTIONS = new MutableDataSet()
            //.set(Parser.REFERENCES_KEEP, KeepType.LAST)
            .set(HtmlRenderer.INDENT_SIZE, 0)
            .set(HtmlRenderer.PERCENT_ENCODE_URLS, true)
            .set(Parser.EXTENSIONS, Arrays.asList(
                    AbbreviationExtension.create(),
                    TablesExtension.create(),
                    FootnoteExtension.create(),
                    AnchorLinkExtension.create(),
                    TypographicExtension.create(),
                    SuperscriptExtension.create(),
                    StrikethroughSubscriptExtension.create(),
                    EmojiExtension.create(),
                    AutolinkExtension.create(),
                    DefinitionExtension.create()

            ));

    public static final Parser PARSER = Parser.builder(OPTIONS).build();
    public static final HtmlRenderer RENDERER = HtmlRenderer.builder(OPTIONS).build();

    Node doc = markdown.PARSER.parse(md); // md is String of markdown content
    System.out.println(markdown.RENDERER.render(doc));
```

Can you explain me Definition Extension options ?

**Comment by vsch** [comment]
@firm1, you don't need the empty `:` lines. You can delete those lines or just replace them with blank lines.

If you want two dl lists then you need to add an HTML comment between the definitions to break the list, just like bullet and numbered lists.

![image](https://cloud.githubusercontent.com/assets/10299086/24730181/2556d4a4-1a30-11e7-90ba-9ff675875bf4.png)

The other configurations are:

![image](https://cloud.githubusercontent.com/assets/10299086/24730196/38f1ed5a-1a30-11e7-9129-19eb3e1868b2.png)

![image](https://cloud.githubusercontent.com/assets/10299086/24730208/4483c936-1a30-11e7-9dff-d404521d4ce7.png)

**Comment by firm1** [comment]
Thank for return.

But, I want to learn from this definition extension to build another extension in which the `<!-- -->` is optionnal for break the list.

It's possible ? If yes how ?

**Comment by vsch** [comment]
@firm1, you can take a look at the source for the extension in the `flexmark-ext-definition` module.

The parsing process first handles definition item parsing for lines starting with `:`.

After parsing of the document is done, the list item block pre processor converts preceding paragraph lines to definition terms and puts both of these in definition lists.

Definition list block pre-processor handles auto-loose definition list item spacing.

You can make a copy of the module and add code to handle two or more blank lines between definition terms as a definition list break by starting a new definition list.

**Comment by firm1** [comment]
Hello,

Despite my research I didn't find how to tell the AST will close the block when it sees that there's a blank line between the end of a definition and the beginning of a term definition.

Will you be able to tell me how modify exactly the code of the definition extension to get there ?

I guess it has to be done in the [DefinitionItemBlockParser](https://github.com/vsch/flexmark-java/blob/490e562edf805f64b50d00ba03616c1c9b2015f8/flexmark-ext-definition/src/main/java/com/vladsch/flexmark/ext/definition/internal/DefinitionItemBlockParser.java), but I can not figure out or ?

Thank a lot.

**Comment by vsch** [comment]
@firm1, you need to add logic to `DefinitionListItemBlockPreProcessor.preProcess()` where it sets the flag `hadPreviousList` to set it to false if the space between previous paragraph and the definition item contains two or more blank lines. Below I wrote the code but not tested to replace the `hadPreviousList`

```java
// intervening characters between definition item and previous paragraph
final BasedSequence interSpace = BasedSequenceImpl.of(previous.getChars().baseSubSequence(previous.getChars().getEndOffset(), definitionItem.getChars().getStartOffset()).normalizeEOL());

final boolean hadPreviousList = paragraphPrevious instanceof DefinitionList && interSpace.countChars('\n') < 2;
```

The first line gets the characters between the end of previous node and the definition item and normalizes EOL (from \r\n and \r to \n). The second line will cause the code not to use the previous definition list if there are two or more blank lines between the nodes.

You may need to debug the code.

**Comment by vsch** [comment]
@firm1, decided to test the code because I have no confidence in memory based coding.

These are the lines that will work:

```java
                // intervening characters between previous paragraph and definition terms
                final BasedSequence interSpace = paragraphPrevious == null ? BasedSequence.NULL : BasedSequenceImpl.of(paragraphPrevious.getChars().baseSubSequence(paragraphPrevious.getChars().getEndOffset(), paragraph.getChars().getStartOffset()).normalizeEOL());

                final boolean hadPreviousList = paragraphPrevious instanceof DefinitionList && interSpace.countChars('\n') < 2;
```

I also added an option to DefinitionExtension to allow enabling this behaviour for the next release. Set `DefinitionExtension.DOUBLE_BLANK_LINE_BREAKS_LIST` to true.

**Comment by vsch** [comment]
@firm1, repo updated. Maven update in progress

**Comment by firm1** [comment]
@vsch Thank's a lot for your commit.

Now I'm looking for a parameter that i can't find.

I would like the blanklines between the terms to be significant. For example, I would like the following markdown :

```text
Term 1
:   Definition 1 (paragraph)

:   Text out of definition (paragraph)
```

Give me this html : 

```html
<dl>
  <dt>Term 1</dt>
  <dd>Definition 1 (paragraph)</dd>
</dl>
<p>:  Text out of definition (paragraph)</p>
```

Can you tell me what option to adjust for this behavior ?

**Comment by vsch** [comment]
@firm1, I added the logic to `DefinitionItemBlockParser` to ignore definition terms spaced two or more blank lines from previous element when `DefinitionExtension.DOUBLE_BLANK_LINE_BREAKS_LIST` is true. 

The two or more blank lines condition makes it consistent with the option to break lists and also does not conflict with having a single blank line being used to mark a loose definition list (ie. text wrapped in `p` tags).

The example you gave should be changed to: 

```markdown
Term 1
:   Definition 1 (paragraph)


:   Text out of definition (paragraph)
```

The original is interpreted as a term with two definitions loosely spaced.

Repo updated. Maven update in progress.

**Comment by firm1** [comment]
Hello @vsch ,

Sorry for my questions, but I'm trying to make an extension that is inspired by the definition extension.

I tried with the definition extension this :

```
Term 1
:   Definition 1 (paragraph)


:   Text out of definition (paragraph)
```

But ` Text out of definition (paragraph)` stay always in block. I would like to get this : 

```html
<dl>
  <dt>Term 1</dt>
  <dd>Definition 1 (paragraph)</dd>
</dl>
<p>:  Text out of definition (paragraph)</p>
```

with this markdown content : 

```
Term 1
:   Definition 1 (paragraph)


:   Text out of definition (paragraph)
```

**Comment by vsch** [comment]
@firm1, I do not understand why the current implementation of definition list extension with `DefinitionExtension.DOUBLE_BLANK_LINE_BREAKS_LIST` option set to `true` does not give you what you want. I modified the implementation to handle your case. 

Here is a test case with you exact text and resulting HTML and AST:

    With multiple terms, broken into two lists:
    
    ```````````````````````````````` example(Definition List Extension: 15) options(break-list)
    Term 1
    :   Definition 1 (paragraph)
    
    
    :   Text out of definition (paragraph)
    .
    <dl>
      <dt>Term 1</dt>
      <dd>Definition 1 (paragraph)</dd>
    </dl>
    <p>:   Text out of definition (paragraph)</p>
    .
    Document[0, 76]
      DefinitionList[0, 36] isTight
        DefinitionTerm[0, 7]
          Paragraph[0, 7]
            Text[0, 6] chars:[0, 6, "Term 1"]
        DefinitionItem[7, 36] open:[7, 8, ":"] isTight hadBlankLineAfter
          Paragraph[11, 36] isTrailingBlankLine
            Text[11, 35] chars:[11, 35, "Defin … raph)"]
      Paragraph[38, 76]
        Text[38, 76] chars:[38, 76, ":   T … raph)"]
    ````````````````````````````````
