### ISSUE TITLE
Markdown to plain text (and/or using ANSI terminal codes)

### ISSUE THREAD

**Issue by tfenne** [vsch/flexmark-java#87]
I'm interested in parsing markdown and generating well-formatted plain text, and possibly also text for display at a terminal that uses ANSI terminal codes to provide some minimal formatting (e.g. emphasis).  My goal in doing so is to be able to use Markdown to write the usage/help information for command line programs, and then a) process the MarkDown to plain text or something close to it for display at the terminal and b) process it into HTML for generation of a documentation website.

I see that another user was asking about this in #63 that was closed.  I wasn't sure if I should re-open that issue, or open a new one, so apologies if I did the wrong thing.

I took a look at the various documentation and the rendering/writing classes for HTML and didn't get a clear picture of what a minimal implementation would look like, such that I could start on one myself.  Any of the following would be great:

1. A fully realized implementation that writes plain text using just whitespace and symbols for layout and styling
2. A shell of a renderer that I could take and start customizing to do the layout (which I'd be happy to walk away with, or contribute back when I'm done)
3. Just some clear guidance around what an implementation would look like as I'm having trouble piecing that together by myself

In the closed issue you asked about how to style various things.  I'd be more than happy to take a crack at answering those questions and others if you're still interested in answers.  The only things I think would be rather tricky would be:

* Tables (do-able, but a lot of effort to lay out nicely)
* Line wrapping for indented lines (since my goal is to produce nice output on a terminal it's critical to be able to set a line-length limit and wrap appropriately)

I'd appreciate any help or guidance you can give.  Thanks!

**Comment by vsch** [comment]
@tfenne,  what you need to create is a custom Formatter that will strip out markdown markers and convert them to plain text.

The easiest thing is to create a custom formatter, start with the `flexmark-formatter` CoreNodeFormatter and modify the rendering of nodes to only output text part of the node.

You will also need to include custom extension nodes that you want to support such as `flexmark-ext-tables`. Formatting tables is handled by the extension so you can use that code as a starting point.

The `flexmark-java-samples` module contains a few samples of custom extensions, including formatter.

**Comment by tfenne** [comment]
Thanks @vsch - I ended up doing a different direction and implementing something akin to your visitor stuff to traverse the AST and output plain text.  I found the Formatter/Renderer APIs difficult to understand, but doing a top-down AST traversal seemed relatively simple.  

I'm also working in scala, which makes some of the recursive pattern matching simpler.  If you're curious where I ended up here's my work in progress: https://github.com/fulcrumgenomics/dagr/pull/279/files

**Comment by vsch** [comment]
@tfenne, I am adding tests and fixes for the missing text elements for inline code and fenced code.

This means that Code and FencedCode nodes will now have a Text node with the text for these elements.

This is potentially an API breaking change because the issue is caused by the AST for these elements missing a Text child node that contains the element's text like is done for emphasis and strong emphasis nodes.

Note that the new release 0.19 will have these changes.

**Comment by icoloma** [comment]
@vsch I was trying to build a custom formatter and found the process -- a lot of work, but -- quite straightforward, but I hit a dead end with `NodeRendererContext`. It's not obvious what the implementation should look like, current implementation for HTML cannot be reused, and most of the methods are not documented.

I'm going to try a similar thing to @tfenne.

**Comment by glaforge** [comment]
For reference, for the next time I also want to output markdown on the console with ANSI escape codes, I ended up taking a simple and naive regex replacement approach, as explained in this [article](https://glaforge.dev/posts/2025/02/27/pretty-print-markdown-on-the-console/). Obviously, this is limited, and won't handle advanced cases like nesting of structures, or tables, etc. But it's good enough for my simple needs right now.
