### ISSUE TITLE
Guide for handling untrusted inputs

### ISSUE THREAD

**Issue by nanodeath** [vsch/flexmark-java#88]
Howdy. This is a spiritual followup to #79, but would it be possible to write a guide on various flags and considerations for running flexmark on untrusted (read: user-provided) inputs?

**Comment by vsch** [comment]
@nanodeath, the only thing I can thing of is to either ESCAPE or SUPPRESS HTML rendering.

See: https://github.com/vsch/flexmark-java/wiki/Extensions#renderer

To Suppress all HTML set `HtmlRenderer. SUPPRESS_HTML` to true, to escape all HTML  set `HtmlRenderer. ESCAPE_HTML` to true.  Suppress will not render the HTML, escape will convert it to text by escaping all HTML special characters.

You can control different types of HTML by using the more granular options, for example blocks but not inline html.

**Comment by nanodeath** [comment]
Didn't see the suppress options before -- I should really read that wiki you linked. I still think mentioning this use case in an FAQ might not be a bad idea; it's likely to be pretty common, I'd suspect. Thanks!

**Comment by nanodeath** [comment]
So escaping HTML does prevent XSS/CSRF sort of unpleasantness, but it doesn't block other...unsavory content. My two other concerns are links and images. Confusingly, *both* are solved by setting `HtmlRenderer.DO_NOT_RENDER_LINKS`. The link text remains, but is not a link, and images are...entirely suppressed. Is that expected?

**Comment by vsch** [comment]
@nanodeath, the `HtmlRenderer.DO_NOT_RENDER_LINKS` is used to get text without links under special circumstances like getting the heading text for table of contents entry and what you are seeing is expected.

It sounds like you need to implement a custom renderer for links and images where you can apply your own rules to what is safe and what is not.

You can take a look at the `flexmark-java-samples` module for examples of custom node renderers, custom nodes like `YouTubeLinkSample` and custom link resolvers.

You can create a custom node renderer and take `Link` and `Image` node rendering methods from the `CoreNodeRenderer` in the `flexmark` core module as a starting point.

**Comment by Elmervc** [comment]
@nanodeath Another approach is to post-process the rendered HTML with a filter like jsoup. Advantage of this approach is that you get good control over what to (dis)allow, also on attribute level of HTML-tags.
You can look at our impl here: https://github.com/webdsl/webdsl/blob/master/java-runtime/src/org/webdsl/tools/WikiFormatter.java
