### ISSUE TITLE
Anchor link id is not being populated

### ISSUE THREAD

**Issue by robinshine** [vsch/flexmark-java#89]
I am using the anchorlink extension to generate anchor links for headers, and specify option 	**HtmlRenderer.GENERATE_HEADER_ID** and **AnchorLinkExtension.ANCHORLINKS_SET_ID**, however the generated anchor link does not contain id attribute.

**Comment by vsch** [comment]
@robinshine, can you post the code you use to set options and also the markdown and html result so I can try to figure out what is going on.
