### ISSUE TITLE
What's the equivalent to Pegdown's LinkRenderer?

### ISSUE THREAD

**Issue by weavejester** [vsch/flexmark-java#90]
I'm looking to switch from Pegdown to Flexmark-Java, but I've hit a stumbling block around Pegdown's [LinkRenderer](http://www.decodified.com/pegdown/api/org/pegdown/LinkRenderer.html) class. In Pegdown, I could transform the way links were handled, allowing wikilinks to match partial names, and ensuring that links to markdown files were converted into links to the rendered HTML files.

I haven't been able to find an equivalent class in Flexmark-Java, yet. The Flexmark parser produces an AST, so presumably I could manually transform it, but I was wondering if there was a more straightforward way.

**Comment by vsch** [comment]
@weavejester, I added a pegdown sample with custom link renderer which is used to resolve all links. In it you can override the markdown URL used in HTML rendering.

[PegdownCustomLinkResolverOptions](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/samples/PegdownCustomLinkResolverOptions.java)

**Comment by weavejester** [comment]
Thanks a lot! That's really helpful!
