### ISSUE TITLE
Adding TextCollectingVisitor class handlers

### ISSUE THREAD

**Issue by myFree** [vsch/flexmark-java#93]
Running the below (scala!)

```
val textCollectingVisitor = new TextCollectingVisitor()
textCollectingVisitor.collectAndGetSegments(document)
```

Against this markdown

~~~~~~~~~~~~~~~~~~~~~~~~~~~
Use `git status`

Git commands
```
git status
git add
git commit
```

This site was built using [GitHub Pages](https://pages.github.com/).
~~~~~~~~~~~~~~~~~~~~~~~~~~~

I get the below strings extracted (which; by the way - was a really huge start on exactly what I was trying to get to!)

"Use",
"Git commands",
"This site was built using",
"GitHub Pages"

I would also like to extract the content of the below strings.

"git status",
"git status
git add
git commit",
"https://pages.github.com/"

1.) Would the right way to approach this be to add additional `VisitHandler`s to the `NodeVisitor` in an updated version of `TextCollectingVisitor`?

2.) Any suggestions on how I can figure out what classes the strings that did not get extracted are parsed into? Not sure if that question is understandable. For example; does `git status` get parsed as a `com.vladsch.flexmark.ast.Code` element in the AST? Could I override some method and add a line of logging for it to tell me what AST node is being processed?

3.) I'm looking to extract all "human readable text" in an md document; just stripping out content which relates to formatting. I'm not sure if my question is clear enough to be able to answer; but here goes - how many of the classes under https://github.com/vsch/flexmark-java/tree/master/flexmark/src/main/java/com/vladsch/flexmark/ast should I provide a handlers for in order to achieve that?

Sorry again if some of my questions are unclear!

Thanks,
Brent

**Comment by vsch** [comment]
@myFree, I think #87 has the solution you are looking for already implemented in Scala.

**Comment by vsch** [comment]
@myFree, I am adding tests and fixes for the missing text elements for inline code and fenced code.

This means that Code and FencedCode nodes will now have a Text node with the text for these elements.

This is potentially an API breaking change because the issue is caused by the AST for these elements missing a Text child node that contains the element's text like is done for emphasis and strong emphasis nodes.

**Comment by vsch** [comment]
@myFree, repo updated. Maven update in progress.

**Comment by vsch** [comment]
@myFree, you can create a custom text collecting visitor that will customize how you convert each type of node to text by adding more node classes to the `NodeVisitor` handler map.

Start with a copy of `TextCollectingVisitor` and modify it.

For each type of node add the text you want to represent the node. For `Code` add `"` then `myVisitor.visitChildren(node)` to append text for the node, then add another `"`. Similarly for `FencedCodeBlock`.

Nothing stops you from creating multiple containers for information in your visitor so you can collect the text and also any other information about the elements traversed.

**Comment by myFree** [comment]
I have read through  #87 and reviewed and reviewed the code tfenne linked to. So will keep it in mind as an alternative.

With the updates in 0.19.0; all the content I require is accessible with `TextCollectingVisitor ` - which I really like; as it feels like a good way to leverage existing functionality in the library.
