### ISSUE TITLE
html to markdown: br tag translated to two spaces plus line break

### ISSUE THREAD

**Issue by david-mas** [vsch/flexmark-java#96]
I am trying to get FlexmarkHtmlParser to parse <br> as I need it, as a single \n. However I always get two spaces and after that the '\n' ('  \n').
I ended up looking at the test suites, and I see this two space prefix is the intended result.
My question is: is it possible to get <br> translated to just '\n' ?
Also I'd like to know what is the reason behind the 2 spaces preceding the \n.

Thank you.

**Comment by vsch** [comment]
@david-mas, and EOL prefixed with two or more spaces is treated in Markdown as a Hard Line Break and will be rendered as `<br>\n` by default.

You can change the HTML used for hard and soft breaks by setting the appropriate options: `HtmlRenderer.HARD_BREAK` and `HtmlRenderer.SOFT_BREAK`

Options for `HtmlRenderer` are listed in the Wiki: https://github.com/vsch/flexmark-java/wiki/Extensions#renderer
