### ISSUE TITLE
Specify css when converting to pdf

### ISSUE THREAD

**Issue by mkanada** [vsch/flexmark-java#98]
How can I specify a custom css file to be used in a pdf conversion?

**Comment by vsch** [comment]
@mkanada, since the PDF converter takes HTML you can add the CSS to the HTML before passing it to the exportToPdf method by wrapping the rendered HTML in `<html><head>....</head><body>` and `</body>` with CSS given by:

    <link rel="stylesheet" href="file://....">

or

    <link rel="stylesheet" href="http://....">

or by using `<style>....</style>` to embed the CSS into the HTML.
